import { describe, expect, it } from "vitest";
import { mesocycleById } from "@/domain/training/mesocycle-library";
import { resolveCurrentHypertrophyLowerBProgrammeGuidance, resolveCurrentHypertrophyLowerProgrammeGuidance, resolveCurrentHypertrophyProgrammeGuidance, resolveCurrentHypertrophyUpperBProgrammeGuidance } from "@/domain/training/current-hypertrophy-programme-guidance-policy";
import { certifyCurrentHypertrophyBaseProgrammePolicy } from "@/domain/training/current-hypertrophy-base-programme-policy-certification";
const base: any = { schemaVersion:"v1",goal:"build_muscle",experienceLevel:"intermediate",trainingDays:4,split:"upper_lower",mesocyclePurpose:"hypertrophy",microcyclePriority:"normal_productive",equipmentCapabilities:["full_gym"],constructionPolicyVersion:"v1",guidancePolicyVersion:"hypertrophy_programme_guidance_v1" };
const results: any[] = [resolveCurrentHypertrophyProgrammeGuidance({...base,sessionRole:"Upper",sessionIdentity:"upper-a"}),resolveCurrentHypertrophyLowerProgrammeGuidance({...base,sessionRole:"Lower",sessionIdentity:"lower-a"}),resolveCurrentHypertrophyUpperBProgrammeGuidance({...base,sessionRole:"Upper",sessionIdentity:"upper-b"}),resolveCurrentHypertrophyLowerBProgrammeGuidance({...base,sessionRole:"Lower",sessionIdentity:"lower-b"})];
const defs = results.flatMap(r=>r.status==="resolved"?r.definitions:[]);
const input = () => ({ certificationVersion:"v1" as const,purpose:mesocycleById("hypertrophy_base")!,policyId:"certified_upper_lower_hypertrophy_v1" as const,policyVersion:"v1" as const,programmeFamilyId:"intermediate_four_day_full_gym_upper_lower" as const,templateOrder:["upper-a","lower-a","upper-b","lower-b"],slotOrdinals:defs.map(x=>x.ordinal),targets:[...new Set([...defs.map(x=>x.target.id),"knee_dominant","hip_hinge","knee_flexion","calves"])],purposes:defs.map(x=>x.purpose),totals:[{min:16,max:23},{min:13,max:19},{min:16,max:23},{min:13,max:19}],optionalOrdinals:["06-elbow-flexion","07-elbow-extension","06-trunk"],substitutionPolicies:defs.map(x=>x.constraints.substitutionPolicy),equipmentCapabilities:["full_gym"],microcyclePriority:"normal_productive",evidenceCompatibility:"planned_roles_and_exact_targets" as const,successorNeutral:true });
describe("hypertrophy base programme-policy equivalence",()=>{it("certifies exact real policy outputs",()=>{expect(results.map(x=>x.status)).toEqual(["resolved","resolved","resolved","resolved"]);expect(certifyCurrentHypertrophyBaseProgrammePolicy(input()).status).toBe("certified_equivalent");});it.each([["templateOrder",["upper-a"],"not_equivalent_session_roles"],["targets",["horizontal_press"],"not_equivalent_structure"],["totals",[{min:1,max:2}],"not_equivalent_set_guidance"],["optionalOrdinals",[],"not_equivalent_optionality"],["equipmentCapabilities",["dumbbells"],"not_equivalent_constraints"],["microcyclePriority","deload","not_equivalent_evidence_assumptions"]] as const)("rejects %s mismatch",(field,value,status)=>expect(certifyCurrentHypertrophyBaseProgrammePolicy({...input(),[field]:value} as any).status).toBe(status));});
