import { describe, expect, it } from "vitest";
import { extractExactTargetFacts } from "@/domain/training/current-exact-target-evidence";
import type { WorkoutSession } from "@/domain/training/models";

function session(overrides: Partial<WorkoutSession> = {}): WorkoutSession { return { id: "session-1", userId: "u", name: "Push", startedAt: "2026-07-11T10:00:00.000Z", completedAt: "2026-07-11T11:00:00.000Z", updatedAt: "2026-07-11T11:00:00.000Z", syncState: "local", sessionKind: "planned", planMesocycleId: "hypertrophy_base", planMicrocycleNumber: 2, planSessionIndex: 0, exercises: [{ id: "log-1", exerciseId: "press", exerciseName: "Press", load: 100, loadKnown: true, status: "complete", origin: "planned", settings: { unit: "kg", repRange: { min: 1, max: 20 }, requiredWorkSets: 2, loadIncrease: 2.5, dropOffPercent: 15 }, prescribedSetTargets: [8, 10], sets: [{ id: "set-1", setNumber: 1, reps: 8, load: 100, loggedAt: "x", type: "work" }, { id: "set-2", setNumber: 2, reps: 11, load: 100, loggedAt: "x", type: "work" }] }], ...overrides }; }
describe("current exact target evidence", () => {
  it("uses each stored ordinal target and excludes non-planned sessions", () => { const result = extractExactTargetFacts([session(), session({ id: "custom", sessionKind: "custom" })], { mesocycleId: "hypertrophy_base", microcycleNumber: 2 }); expect(result.facts.map((fact) => fact.completion)).toEqual(["met", "exceeded"]); expect(result.ignoredNonPlannedIds).toEqual(["custom"]); });
  it("keeps missing and stopped planned evidence explicit", () => { const stopped = session(); stopped.exercises[0]!.status = "shutdown"; const result = extractExactTargetFacts([stopped, session({ id: "missing", exercises: [{ ...stopped.exercises[0]!, id: "missing-log", prescribedSetTargets: undefined }] })], { mesocycleId: "hypertrophy_base", microcycleNumber: 2 }); expect(result.facts[0]?.completion).toBe("stopped"); expect(result.invalidWorkoutIds).toContain("missing"); });
});
