import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { CERTIFIED_UPPER_LOWER_PROGRAMME_FAMILY, CERTIFIED_UPPER_LOWER_TEMPLATE_FAMILY, CURRENT_MESOCYCLE_PROGRAMME_POLICY_REGISTRY, canConstructCurrentProgrammeSpecification, copyCurrentMesocycleProgrammePolicyMappingResult, currentHypertrophyMesocyclePurposeRegistry, fingerprintCurrentMesocycleProgrammePolicyMappingInput, resolveCurrentMesocycleProgrammePolicyMapping } from "@/domain/training/current-mesocycle-programme-policy-mapping";
import { mesocycleLibrary } from "@/domain/training/mesocycle-library";

const input: any = { schemaVersion: "v1", registryVersion: CURRENT_MESOCYCLE_PROGRAMME_POLICY_REGISTRY, goal: "build_muscle", experienceLevel: "intermediate", trainingDays: 4, split: "upper_lower", mesocyclePurpose: "hypertrophy_base", equipmentCapabilities: ["full_gym"], programmeFamilyId: CERTIFIED_UPPER_LOWER_PROGRAMME_FAMILY, sessionTemplateFamilyId: CERTIFIED_UPPER_LOWER_TEMPLATE_FAMILY };
describe("current mesocycle programme-policy mapping", () => {
  it("returns the exact certified base policy and enables only construction-safe capability", () => { const result = resolveCurrentMesocycleProgrammePolicyMapping(input); expect(result).toMatchObject({ status: "supported", reason: "policy_certified_for_exact_purpose", policy: { policyId: "certified_upper_lower_hypertrophy_v1", certificationId: "hypertrophy_base_upper_lower_equivalence_v1", supportedPurpose: "hypertrophy_base" }, compatibilityConsequence: "continue_compatibility_plan" }); expect(result.capabilities).toEqual({ mayResolveSlots: true, mayConstructProgrammeSpecification: true, mayPersistCurrentProgramme: false, mayApplyCurrentGuidanceAdjustment: false }); expect(canConstructCurrentProgrammeSpecification(result)).toBe(true); });
  it("projects only the exact certified calibration policy with persistence and adjustment still disabled", () => { const result = resolveCurrentMesocycleProgrammePolicyMapping({ ...input, mesocyclePurpose: "hypertrophy_calibration" }); expect(result).toMatchObject({ status: "supported", policy: { policyId: "intermediate_upper_lower_hypertrophy_calibration_v1", certificationId: "hypertrophy_calibration_upper_lower_certification_v1", supportedPurpose: "hypertrophy_calibration" } }); expect(result.capabilities).toEqual({ mayResolveSlots: true, mayConstructProgrammeSpecification: true, mayPersistCurrentProgramme: false, mayApplyCurrentGuidanceAdjustment: false }); });
  it("keeps volume and every other unimplemented hypertrophy purpose explicit", () => { expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, mesocyclePurpose: "hypertrophy_volume" })).toMatchObject({ status: "dedicated_policy_required", reason: "volume_requires_dedicated_guidance_policy" }); expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, mesocyclePurpose: "hypertrophy_specialisation" })).toMatchObject({ status: "dedicated_policy_required", reason: "specialisation_policy_not_implemented" }); });
  it("rejects similarity, unknown purposes and non-certified families without fallback", () => { expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, mesocyclePurpose: "hypertrophy" }).status).toBe("unsupported_mesocycle_purpose"); expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, mesocyclePurpose: "hypertrophy_baseline" }).status).toBe("unsupported_mesocycle_purpose"); expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, experienceLevel: "beginner" }).status).toBe("unsupported_programme_family"); expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, equipmentCapabilities: ["dumbbells"] }).status).toBe("unsupported_programme_family"); expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, goal: "build_strength", mesocyclePurpose: "strength_general" }).status).toBe("invalid_input"); });
  it("requires exact registry/schema and preserves deterministic defensive copies", () => { expect(resolveCurrentMesocycleProgrammePolicyMapping({ ...input, registryVersion: "unknown" }).status).toBe("unsupported_registry"); const first = fingerprintCurrentMesocycleProgrammePolicyMappingInput({ ...input, equipmentCapabilities: ["barbell", "full_gym"] }); const second = fingerprintCurrentMesocycleProgrammePolicyMappingInput({ ...input, equipmentCapabilities: ["full_gym", "barbell"] }); expect(first).toBe(second); const result = resolveCurrentMesocycleProgrammePolicyMapping(input); const copy = copyCurrentMesocycleProgrammePolicyMappingResult(result); expect(copy).toEqual(result); expect(copy.capabilities).not.toBe(result.capabilities); });
  it("requires one explicit registry row for every hypertrophy catalogue purpose", () => { const cataloguePurposes = mesocycleLibrary.filter((purpose) => purpose.engine === "hypertrophy").map((purpose) => purpose.id).sort(); expect([...currentHypertrophyMesocyclePurposeRegistry].sort()).toEqual(cataloguePurposes); });
  it("stays a classification-only boundary", () => { const source = readFileSync("src/domain/training/current-mesocycle-programme-policy-mapping.ts", "utf8"); for (const forbidden of ["current-hypertrophy-programme-guidance-policy", "current-programme-specification-construction", "active-training-plan-repository", "TrainingBlock", "annual-planner", "exercise-selector", "planned-workout", "exact-target"]) expect(source).not.toContain(forbidden); });
});
