import { describe, expect, it } from "vitest";
import { projectCanonicalProgressDashboard } from "@/domain/training/canonical-progress-dashboard-projection";
import { resolveCanonicalProgressDashboardEvidence } from "@/domain/training/canonical-progress-dashboard-evidence-contract";
import { resolveCanonicalMesocycleRecoveryPolicy } from "@/domain/training/canonical-mesocycle-recovery-policy";
import { evaluateCanonicalRecoveryPolicyIntervention } from "@/domain/training/canonical-recovery-phase-intervention-evaluator";
import { resolveCanonicalMesocycleVolumePolicy } from "@/domain/training/canonical-mesocycle-volume-policy";
import { resolveCanonicalMicrocycleRotationPolicy } from "@/domain/training/canonical-microcycle-rotation-policy";
import { projectCanonicalSessionConstructionDisplay } from "@/domain/training/canonical-session-construction-display-projection";

const base = { contractVersion: "canonical_current_progress_context_v1" as const, planId: "plan:dashboard", planRevision: 2, macrocycle: { id: "macro:dashboard", route: "build_muscle", strategy: "productive" }, mesocycle: { id: "meso:dashboard", purpose: "hypertrophy_base", policyId: "canonical_mesocycle_v1" }, microcycle: { id: "micro:dashboard", order: 1, priority: "normal", rotation: "retain", stress: "normal" }, evidence: { ids: ["e:dashboard"], freshness: "fresh" as const, completeness: "complete" as const }, evaluation: { id: "eval:dashboard", version: "canonical_progress_evaluation_v2", outcome: "continue", reasons: ["canonical_facts"] }, recordedProgress: { completedSessions: 2, performedSets: 4, evidencePending: false } };

describe("canonical Progress dashboard unit coverage", () => {
  it("projects current context and bounded history", () => { const result = projectCanonicalProgressDashboard({ ...base, history: { windowId: "recent", recordedSessions: 2, completed: 2, partial: 0, missed: 0, performedSets: 4, prescribedSets: 4, substitutions: 0, evidencePending: 0 } }); expect(result.context.route).toBe("build_muscle"); expect(result.history?.performedSets).toBe(4); });
  it("excludes zero-work history and preserves empty history", () => { const result = projectCanonicalProgressDashboard({ ...base, recordedProgress: { completedSessions: 0, performedSets: 0, evidencePending: false }, history: { windowId: "recent", recordedSessions: 1, completed: 0, partial: 0, missed: 1, performedSets: 0, prescribedSets: 2, substitutions: 0, evidencePending: 0 } }); expect(result.history?.performedSets).toBe(0); expect(projectCanonicalProgressDashboard({ ...base, history: { windowId: "recent", recordedSessions: 0, completed: 0, partial: 0, missed: 0, performedSets: 0, prescribedSets: 0, substitutions: 0, evidencePending: 0 } }).history?.recordedSessions).toBe(0); });
  it("fails closed for insufficient, stale, conflicting, and malformed evidence", () => { const insufficient = resolveCanonicalProgressDashboardEvidence({ planId: base.planId, planRevision: 2, cycleIds: ["macro:dashboard", "meso:dashboard", "micro:dashboard"], completedSessions: 1, plannedSessions: 2, extraSessions: 3, requiredCompletedSessions: 2, freshness: "fresh", completeness: "complete" }); expect(projectCanonicalProgressDashboard({ ...base, evidence: { ids: ["e"], freshness: "stale", completeness: "incomplete" }, evidenceSufficiency: insufficient }).status).toBe("insufficient_evidence"); expect(() => projectCanonicalProgressDashboard({ ...base, microcycle: { ...base.microcycle, legacy: { blocks: [] } } } as never)).toThrow(); });
  it("projects local recovery review without creating an action", () => { const policy = resolveCanonicalMesocycleRecoveryPolicy({ planId: base.planId, mesocycleId: base.mesocycle.id, purpose: "hypertrophy_base", method: "standard", evidenceIds: ["e:dashboard"], freshness: "fresh", completeness: "complete", fatigue: "local", recovery: "constrained" }); const intervention = evaluateCanonicalRecoveryPolicyIntervention({ policy, evaluationId: "eval:dashboard", operationId: "op:local", evidenceVersions: { "e:dashboard": "v1" }, macrocycleId: base.macrocycle.id, microcycleId: base.microcycle.id, planRevision: 2 }); const result = projectCanonicalProgressDashboard({ ...base, recoveryIntervention: intervention }); expect(result.action.allowed).toBe(false); });
  it("projects systemic recovery as review-only", () => { const policy = resolveCanonicalMesocycleRecoveryPolicy({ planId: base.planId, mesocycleId: base.mesocycle.id, purpose: "hypertrophy_base", method: "standard", evidenceIds: ["e:dashboard"], freshness: "fresh", completeness: "complete", fatigue: "systemic", recovery: "constrained" }); expect(policy.disposition).toBe("review_stress_reduction"); });
  it("projects volume review and rotation review without mutation", () => { const volume = resolveCanonicalMesocycleVolumePolicy({ planId: base.planId, mesocycleId: base.mesocycle.id, purpose: "hypertrophy_base", policyProgression: "increase", recoveryAdjustment: "permitted", evidenceIds: ["e:dashboard"], evidenceState: "fresh", fatigue: "stable" }); const rotation = resolveCanonicalMicrocycleRotationPolicy({ microcycleId: base.microcycle.id, mesocycleId: base.mesocycle.id, macrocycleId: base.macrocycle.id, frequency: 4, roleSignature: ["upper"], stressSignature: ["normal"], approvedEdges: [], evidenceIds: ["e:dashboard"], evidenceState: "fresh", fatigue: "stable", requestedAdvance: true, compatible: true }); expect(volume.disposition).toBe("review_required"); expect(rotation.disposition).toBe("unsupported_policy"); });
  it("projects canonical session labels from catalogue metadata", () => { const snapshot = { schemaVersion: "canonical_session_snapshot_v2", sessionId: "session:dashboard", role: "upper", provenance: { inputVersion: "v1" }, slots: [{ index: 0, exerciseId: "exercise:bench", method: "straight_sets", loadingMode: "bodyweight" }] } as never; const result = projectCanonicalSessionConstructionDisplay(snapshot, [{ id: "exercise:bench", name: "Bench Press" } as never]); expect(result.status === "ready" && result.projection.slots[0]?.exerciseName).toBe("Bench Press"); });
  it("keeps unsupported action descriptors non-actionable", () => { const result = projectCanonicalProgressDashboard({ ...base, evidence: { ids: ["e"], freshness: "stale", completeness: "incomplete" }, decision: { id: "d", kind: "review_required", status: "blocked" } }); expect(result.action.allowed).toBe(false); });
});
