import { describe, expect, it } from "vitest";
import { resolveRecommendedSetGuidanceTarget, type ApplyRecommendedSetGuidanceAdjustmentCommand, type RecommendedSetGuidanceResolverReads } from "@/application/training/recommended-set-guidance-target-resolver";

const command: ApplyRecommendedSetGuidanceAdjustmentCommand = { schemaVersion: "v1", adjustmentRecordId: "adjustment-1", adjustmentKind: "raise_range", expectedActivePlanId: "plan-1", target: { planId: "plan-1", programmeId: "programme-1", mesocycleId: "meso-1", microcycleNumber: 2, sessionIdentity: "push", guidanceField: "recommended_set_count" }, requestedAt: "2026-07-12T10:00:00.000Z", policyVersion: "legacy_programme_guidance_v1" };
const reads = (references: ReturnType<RecommendedSetGuidanceResolverReads["findPlannedWorkoutReferences"]> = []): RecommendedSetGuidanceResolverReads => ({ findAdjustment: () => ({ id: "adjustment-1", action: "raise_range", status: "applied" }), findActivePlan: () => ({ id: "plan-1" }), findGuidanceTarget: () => [{ identity: command.target, kind: "future_active_plan_guidance" }], findPlannedWorkoutReferences: () => references });
describe("recommended set guidance target resolver", () => {
  it("resolves future guidance but leaves timing to the application boundary", () => { const result = resolveRecommendedSetGuidanceTarget(command, reads()); expect(result.status).toBe("resolved_future_guidance_target"); if (result.status === "resolved_future_guidance_target") { expect(result.lifecycle.status).toBe("additional_timing_policy_required"); expect(result.nextRequiredBoundary).toBe("timing_policy"); } });
  it("passes authoritative open and completed reference facts into the lifecycle guard", () => { const open = resolveRecommendedSetGuidanceTarget(command, reads([{ workoutId: "workout-1", planId: "plan-1", mesocycleId: "meso-1", microcycleNumber: 2, sessionIdentity: "push", lifecycle: "open", hasExactTargetCoverage: true }])); const completed = resolveRecommendedSetGuidanceTarget(command, reads([{ workoutId: "workout-2", planId: "plan-1", mesocycleId: "meso-1", microcycleNumber: 2, sessionIdentity: "push", lifecycle: "completed", hasExactTargetCoverage: false }])); expect(open.status === "resolved_future_guidance_target" && open.lifecycle.status).toBe("blocked_open_planned_exact_authority"); expect(completed.status === "resolved_future_guidance_target" && completed.lifecycle.status).toBe("blocked_completed_historical_authority"); });
  it("does not guess incomplete target identity or mutate a read model", () => { const incomplete = resolveRecommendedSetGuidanceTarget({ ...command, target: { ...command.target, programmeId: "" } }, reads()); expect(incomplete.status).toBe("incomplete_target_identity"); });
});
