import { validateMacrocycleTimeline } from "@/domain/training/macrocycle-engine";
import type { Equipment, ExperienceLevel, MovementPattern, UnitSystem } from "@/domain/training/models";
import { resolveCanonicalProgrammeFramework } from "@/domain/training/programme-framework-rules";
import type { PreferredSplit, RecoveryCardioPreference, TrainingSetupGoal } from "@/domain/training/plan-setup";

export const CANONICAL_ADAPTIVE_PLANNING_SYSTEM_VERSION = "canonical_adaptive_planning_system_v1" as const;

export type CanonicalPlanningLevel = "Macrocycle" | "Mesocycle" | "Microcycle" | "Session Construction" | "Set Prescription" | "Progress" | "Presentation";
export type CanonicalPlanningEffect = "structure" | "dosage" | "exercise_selection" | "scheduling" | "load" | "recovery" | "presentation" | "evidence_only";
export type CanonicalPlanningTiming = "immediate_display" | "next_set" | "next_session" | "next_microcycle" | "next_mesocycle" | "next_macrocycle" | "recorded_history_only";

export type CanonicalPlanningInputRegistryEntry = Readonly<{
  id: string;
  sourceOfTruth: string;
  availability: "onboarding" | "settings" | "canonical_construction" | "recorded_ledger" | "progress_evidence" | "cycle_state" | "catalogue" | "not_currently_supported";
  domain: string;
  validValues: string;
  defaultValue: string;
  validation: string;
  mayAffect: readonly CanonicalPlanningLevel[];
  mustNotAffect: readonly CanonicalPlanningLevel[];
  effects: readonly CanonicalPlanningEffect[];
  applies: CanonicalPlanningTiming;
  precedence: string;
}>;

const input = (value: CanonicalPlanningInputRegistryEntry) => value;
export const canonicalPlanningInputRegistry: readonly CanonicalPlanningInputRegistryEntry[] = [
  input({ id: "goal", sourceOfTruth: "onboarding TrainingSetupGoal", availability: "onboarding", domain: "build_muscle | build_strength | build_muscle_and_strength | athletic_performance | get_leaner", validValues: "five production goals", defaultValue: "build_muscle", validation: "goal strategy and framework compatibility must resolve", mayAffect: ["Macrocycle", "Mesocycle", "Microcycle", "Session Construction"], mustNotAffect: ["Presentation"], effects: ["structure", "dosage", "exercise_selection", "recovery"], applies: "next_macrocycle", precedence: "below safety/event; above preference" }),
  input({ id: "experience", sourceOfTruth: "onboarding/AppSettings ExperienceLevel", availability: "onboarding", domain: "beginner | intermediate | advanced", validValues: "three declared levels", defaultValue: "intermediate", validation: "must be eligible for selected Mesocycle and exercises", mayAffect: ["Mesocycle", "Microcycle", "Session Construction", "Set Prescription"], mustNotAffect: ["Presentation"], effects: ["dosage", "exercise_selection", "load"], applies: "next_mesocycle", precedence: "below safety/goal; above variety" }),
  input({ id: "days_per_week", sourceOfTruth: "onboarding TrainingDaysPerWeek", availability: "onboarding", domain: "integer 2..6", validValues: "2,3,4,5,6", defaultValue: "5", validation: "frequency/framework pair must have a deterministic sequence", mayAffect: ["Microcycle", "Session Construction"], mustNotAffect: ["Macrocycle"], effects: ["scheduling", "dosage"], applies: "next_microcycle", precedence: "below equipment; above split preference" }),
  input({ id: "framework_preference", sourceOfTruth: "onboarding PreferredSplit", availability: "onboarding", domain: "three customer-facing framework preferences", validValues: "push_pull_legs, upper_lower, full_body (frequency compatible only)", defaultValue: "frequency-specific ASC preselection", validation: "frequency truth table rejects incompatibility before plan creation; internal asymmetric/lift strategies remain Microcycle-owned", mayAffect: ["Microcycle", "Session Construction"], mustNotAffect: ["Macrocycle", "Mesocycle"], effects: ["structure", "scheduling", "exercise_selection"], applies: "next_microcycle", precedence: "preference intent is preserved while phase/safety/recovery may morph delivery" }),
  input({ id: "commitment", sourceOfTruth: "onboarding TrainingCommitment", availability: "onboarding", domain: "continuous_development | event_driven", validValues: "rolling or fixed deadline", defaultValue: "continuous_development", validation: "event-driven requires compatible type and valid target date", mayAffect: ["Macrocycle"], mustNotAffect: ["Set Prescription"], effects: ["structure", "scheduling"], applies: "next_macrocycle", precedence: "deadline above goal delivery preference" }),
  input({ id: "event_type", sourceOfTruth: "onboarding TrainingEventType", availability: "onboarding", domain: "goal-compatible event type", validValues: "powerlifting, athletic, physique, holiday/photoshoot, custom", defaultValue: "none", validation: "compatibility registry", mayAffect: ["Macrocycle", "Mesocycle"], mustNotAffect: ["Set Prescription"], effects: ["structure", "scheduling"], applies: "next_macrocycle", precedence: "below safety; above goal pathway defaults" }),
  input({ id: "target_date", sourceOfTruth: "canonical Macrocycle input", availability: "canonical_construction", domain: "ISO date", validValues: "future date with enough minimum phase time", defaultValue: "none (rolling)", validation: "typed impossible timeline rejection", mayAffect: ["Macrocycle", "Mesocycle"], mustNotAffect: ["Set Prescription"], effects: ["structure", "scheduling"], applies: "next_macrocycle", precedence: "deadline constraint" }),
  input({ id: "equipment", sourceOfTruth: "canonical construction command", availability: "canonical_construction", domain: "non-empty Equipment[]", validValues: "catalogue equipment enum", defaultValue: "onboarding currently supplies complete catalogue capability", validation: "every selected exercise must have available equipment", mayAffect: ["Session Construction"], mustNotAffect: ["Macrocycle", "Mesocycle"], effects: ["exercise_selection"], applies: "next_session", precedence: "above preferences" }),
  input({ id: "units", sourceOfTruth: "AppSettings UnitSystem", availability: "settings", domain: "kg | lb", validValues: "kg, lb", defaultValue: "kg", validation: "display conversion only; canonical base load remains kg", mayAffect: ["Presentation"], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle", "Session Construction"], effects: ["presentation"], applies: "immediate_display", precedence: "presentation only" }),
  input({ id: "load_increment_profile", sourceOfTruth: "AppSettings LoadIncrementProfile", availability: "settings", domain: "positive equipment/exercise increments", validValues: "normalised factual increments", defaultValue: "equipment defaults", validation: "positive and factual equipment resolution", mayAffect: ["Set Prescription", "Presentation"], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle"], effects: ["load", "presentation"], applies: "next_session", precedence: "rounding after prescription" }),
  input({ id: "recovery_cardio_preference", sourceOfTruth: "onboarding/AppSettings", availability: "onboarding", domain: "recommended | minimal | off", validValues: "three modes", defaultValue: "recommended", validation: "canonical concurrent-training policy creates exact bounded sessions without changing lifting-session count", mayAffect: ["Microcycle", "Progress", "Presentation"], mustNotAffect: ["Macrocycle", "Set Prescription"], effects: ["recovery", "scheduling", "presentation"], applies: "next_microcycle", precedence: "below safety, sport workload and recovery evidence" }),
  input({ id: "exercise_catalogue", sourceOfTruth: "canonical exercise catalogue plus custom exercise repository", availability: "catalogue", domain: "versioned factual Exercise[]", validValues: "validated metadata", defaultValue: "bundled catalogue", validation: "role, movement, stimulus, suitability and equipment metadata", mayAffect: ["Session Construction"], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle"], effects: ["exercise_selection"], applies: "next_session", precedence: "factual candidate pool" }),
  input({ id: "exercise_preferences", sourceOfTruth: "canonical learned ExercisePreferenceRecord", availability: "progress_evidence", domain: "versioned preferred/avoided exercise facts", validValues: "persistent or temporary records", defaultValue: "none", validation: "cannot override limitation, equipment, slot role or stimulus", mayAffect: ["Session Construction"], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle"], effects: ["exercise_selection"], applies: "next_session", precedence: "below safety/equipment/programme role" }),
  input({ id: "limitations", sourceOfTruth: "canonical construction constraints", availability: "canonical_construction", domain: "typed exclusion tokens", validValues: "exclude_exercise, exclude_movement, exclude_equipment", defaultValue: "none", validation: "unknown/free-text medical limitations fail closed", mayAffect: ["Session Construction"], mustNotAffect: ["Macrocycle"], effects: ["exercise_selection"], applies: "next_session", precedence: "highest safety constraint" }),
  input({ id: "established_loads", sourceOfTruth: "canonical Progress evidence", availability: "progress_evidence", domain: "positive base-kg loads linked to exercise evidence", validValues: "fresh compatible evidence", defaultValue: "absent", validation: "exercise identity/freshness/calibration linkage", mayAffect: ["Set Prescription"], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle", "Session Construction"], effects: ["load"], applies: "next_session", precedence: "evidence above display preference" }),
  input({ id: "performed_work", sourceOfTruth: "canonical recorded-session ledger", availability: "recorded_ledger", domain: "immutable performed-work events", validValues: "validated versioned events", defaultValue: "none", validation: "session/slot/prescription linkage", mayAffect: ["Progress"], mustNotAffect: ["Macrocycle", "Session Construction"], effects: ["evidence_only"], applies: "recorded_history_only", precedence: "factual evidence" }),
  input({ id: "adherence_and_missed_sessions", sourceOfTruth: "ledger completion/missed facts", availability: "progress_evidence", domain: "session-level evidence", validValues: "completed, partial, missed, interrupted", defaultValue: "no evidence", validation: "calendar absence alone is not fatigue", mayAffect: ["Microcycle", "Progress"], mustNotAffect: ["Macrocycle"], effects: ["scheduling", "evidence_only"], applies: "next_microcycle", precedence: "preserve sequence unless higher intervention approved" }),
  input({ id: "performance_trend", sourceOfTruth: "canonical Progress evaluation", availability: "progress_evidence", domain: "comparable improvement/regression evidence", validValues: "sufficient, stale, conflicting, insufficient", defaultValue: "insufficient", validation: "identity/version/freshness", mayAffect: ["Progress", "Mesocycle"], mustNotAffect: ["Session Construction"], effects: ["evidence_only", "dosage"], applies: "next_mesocycle", precedence: "persistent evidence, not one set" }),
  input({ id: "rep_drop_off", sourceOfTruth: "performed work plus canonical stop rule", availability: "recorded_ledger", domain: "set-local percentage against authorised threshold", validValues: "below/at/above policy threshold", defaultValue: "none", validation: "same exercise/session prescription", mayAffect: ["Set Prescription", "Progress"], mustNotAffect: ["Macrocycle"], effects: ["dosage", "evidence_only"], applies: "next_set", precedence: "session stop rule first; future change requires Progress" }),
  input({ id: "fatigue_readiness", sourceOfTruth: "canonical Progress/recovery evidence", availability: "progress_evidence", domain: "fresh complete non-conflicting evidence", validValues: "ready, restricted, review, insufficient", defaultValue: "insufficient", validation: "policy identity and evidence freshness", mayAffect: ["Mesocycle", "Microcycle", "Progress"], mustNotAffect: ["Presentation"], effects: ["recovery", "dosage", "scheduling"], applies: "next_microcycle", precedence: "below safety; above preference/variety" }),
  input({ id: "active_cycle_state", sourceOfTruth: "canonical active-plan carrier", availability: "cycle_state", domain: "macro/meso/micro identities and revisions", validValues: "validated lineage", defaultValue: "none before activation", validation: "parent/revision/lineage consistency", mayAffect: ["Macrocycle", "Mesocycle", "Microcycle", "Session Construction"], mustNotAffect: ["Presentation"], effects: ["structure", "scheduling"], applies: "next_session", precedence: "current canonical authority" }),
  input({ id: "previous_mesocycles", sourceOfTruth: "canonical cycle lineage and persisted decisions", availability: "cycle_state", domain: "immutable predecessor identities", validValues: "validated lineage", defaultValue: "none", validation: "successor edge and decision linkage", mayAffect: ["Mesocycle", "Progress"], mustNotAffect: ["Set Prescription"], effects: ["structure", "evidence_only"], applies: "next_mesocycle", precedence: "approved successors only" }),
  input({ id: "custom_movements", sourceOfTruth: "custom exercise repository", availability: "catalogue", domain: "validated Exercise metadata", validValues: "complete role/movement/equipment/prescription metadata", defaultValue: "none", validation: "incomplete or incompatible custom movement rejected", mayAffect: ["Session Construction"], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle"], effects: ["exercise_selection"], applies: "next_session", precedence: "same suitability rules as bundled catalogue" }),
  input({ id: "session_duration_constraint", sourceOfTruth: "none", availability: "not_currently_supported", domain: "not in production onboarding/settings/command", validValues: "unsupported", defaultValue: "allocator feasibility cap only", validation: "must not be inferred", mayAffect: [], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle", "Session Construction", "Set Prescription"], effects: [], applies: "next_session", precedence: "requires a future owned contract" }),
  input({ id: "sport_workload", sourceOfTruth: "recorded cardio/session evidence only", availability: "progress_evidence", domain: "factual recent workload", validValues: "where recorded", defaultValue: "absent", validation: "must not be inferred from athletic goal", mayAffect: ["Microcycle", "Progress"], mustNotAffect: ["Macrocycle", "Set Prescription"], effects: ["recovery", "scheduling"], applies: "next_microcycle", precedence: "fresh factual workload" }),
  input({ id: "body_metrics", sourceOfTruth: "recorded factual metrics", availability: "progress_evidence", domain: "optional factual observations", validValues: "validated records", defaultValue: "absent", validation: "cannot prove fat loss alone", mayAffect: ["Progress"], mustNotAffect: ["Macrocycle", "Mesocycle", "Microcycle", "Session Construction", "Set Prescription"], effects: ["evidence_only", "presentation"], applies: "recorded_history_only", precedence: "context only" }),
] as const;

export type CanonicalGoalStrategy = Readonly<{
  goal: Exclude<TrainingSetupGoal, "powerlifting_meet">;
  strategyId: string;
  success: readonly string[];
  pathway: readonly string[];
  priorities: readonly string[];
  conditioning: string;
  methods: readonly string[];
  prohibited: readonly string[];
}>;

export const canonicalGoalStrategies: readonly CanonicalGoalStrategy[] = [
  { goal: "build_muscle", strategyId: "canonical_goal_hypertrophy_v1", success: ["recoverable direct muscle stimulus", "comparable rep/load progression"], pathway: ["calibration", "accumulation", "consolidation", "transition"], priorities: ["stable exercise execution", "muscle frequency", "recoverable volume"], conditioning: "low-cost recovery/capacity support", methods: ["straight sets", "back-off sets", "authorised hypertrophy methods"], prohibited: ["fatigue without target coverage", "strength peaking as default"] },
  { goal: "build_strength", strategyId: "canonical_goal_strength_v1", success: ["specific lift/pattern performance", "repeatable high-force exposure"], pathway: ["general preparation", "strength accumulation", "transmutation", "intensification", "taper", "transition"], priorities: ["specific practice", "force capacity", "fatigue control"], conditioning: "support recovery without degrading heavy output", methods: ["straight sets", "back-off sets", "phase-authorised heavy practice"], prohibited: ["body-part-only delivery", "AMRAP in taper"] },
  { goal: "build_muscle_and_strength", strategyId: "canonical_goal_powerbuilding_v1", success: ["main-lift progression", "recoverable muscle stimulus"], pathway: ["foundation", "hypertrophy bias", "strength accumulation", "intensification", "realisation", "transition"], priorities: ["coordinate heavy anchors and volume", "retain S/B/D exposure"], conditioning: "low interference", methods: ["straight sets", "back-off sets", "phase-authorised strength methods"], prohibited: ["maximise volume and intensity simultaneously", "random specialist methods"] },
  { goal: "athletic_performance", strategyId: "canonical_goal_athletic_v1", success: ["high-quality power exposure", "strength support", "managed concurrent fatigue"], pathway: ["general preparation", "specific preparation", "pre-competition", "transition"], priorities: ["power quality", "movement pattern strength", "sport workload spacing"], conditioning: "integrated with factual sport/cardio load", methods: ["velocity intent", "straight strength support"], prohibited: ["bodybuilding renamed as athletic work", "grinding power sets"] },
  { goal: "get_leaner", strategyId: "canonical_goal_getting_lean_v1", success: ["preserved muscle and useful strength", "sustainable training consistency"], pathway: ["calibration", "accumulation", "consolidation", "transition"], priorities: ["retain resistance stimulus", "manage recovery", "coordinate easy conditioning"], conditioning: "supports energy expenditure/recovery without turning lifting into calorie chasing", methods: ["stable resistance training", "low-cost conditioning"], prohibited: ["automatic lighter weights", "arbitrary set deletion", "fat-loss claims from training alone"] },
] as const;

export const canonicalPlanningAuthority = [
  { owner: "Macrocycle", owns: ["goal strategy", "event horizon", "phase pathway", "approved mesocycle families"], cannotOwn: ["exercise", "set", "load"] },
  { owner: "Mesocycle", owns: ["phase purpose", "volume/intensity emphasis", "methods", "progression/exit", "successors"], cannotOwn: ["calendar navigation", "exact exercise"] },
  { owner: "Microcycle", owns: ["rotation", "session order", "frequency distribution", "recovery spacing", "missed-session reflow"], cannotOwn: ["goal strategy", "exact load"] },
  { owner: "Session Construction", owns: ["exercise slots", "selection", "order", "sets", "reps", "rest", "load state", "stop rules"], cannotOwn: ["macro strategy", "progress decision"] },
  { owner: "Set Prescription", owns: ["exact executable target", "set-local stop condition"], cannotOwn: ["phase", "rotation"] },
  { owner: "Progress", owns: ["evidence", "evaluation", "bounded intervention", "decision/application coordination"], cannotOwn: ["exact future prescription", "arbitrary successor"] },
] as const;

export const canonicalPlanningPrecedence = ["safety_or_limitation", "event_or_deadline", "goal_and_phase", "recovery_and_fatigue", "equipment", "availability", "framework_preference", "exercise_preference", "variety"] as const;

export type CanonicalPlanningValidationInput = Readonly<{ goal: TrainingSetupGoal; experience: ExperienceLevel; daysPerWeek: number; preferredSplit: PreferredSplit; equipment: readonly Equipment[]; units: UnitSystem; createdAt: string; targetDate?: string; limitations?: readonly string[] }>;
export type CanonicalPlanningValidation = Readonly<{ status: "valid"; resolvedSplit: PreferredSplit; reasonCodes: readonly string[] }> | Readonly<{ status: "invalid"; reason: "unsupported_input_combination" | "missing_required_strategy" | "impossible_event_timeline" | "unsafe_limitation_conflict" | "invalid_units" | "missing_equipment"; detail: string }>;

export function validateCanonicalPlanningActivation(input: CanonicalPlanningValidationInput): CanonicalPlanningValidation {
  if (!canonicalGoalStrategies.some((strategy) => strategy.goal === input.goal || (input.goal === "powerlifting_meet" && strategy.goal === "build_strength"))) return { status: "invalid", reason: "missing_required_strategy", detail: input.goal };
  if (!input.equipment.length) return { status: "invalid", reason: "missing_equipment", detail: "equipment_required" };
  if (input.units !== "kg" && input.units !== "lb") return { status: "invalid", reason: "invalid_units", detail: String(input.units) };
  const framework = resolveCanonicalProgrammeFramework({ goal: input.goal, sessionsPerWeek: input.daysPerWeek, requested: input.preferredSplit });
  if (framework.status !== "resolved") return { status: "invalid", reason: "unsupported_input_combination", detail: framework.reason };
  const timeline = validateMacrocycleTimeline(input.goal, input.experience, input.targetDate, input.createdAt);
  if (timeline.status !== "valid") return { status: "invalid", reason: "impossible_event_timeline", detail: timeline.reason };
  const invalidLimitation = (input.limitations ?? []).find((limitation) => !parseCanonicalLimitation(limitation));
  if (invalidLimitation) return { status: "invalid", reason: "unsafe_limitation_conflict", detail: invalidLimitation };
  return { status: "valid", resolvedSplit: framework.requested === "let_app_choose" ? preferredSplitForResolvedFramework(framework.framework) : preferredSplitForResolvedFramework(framework.framework), reasonCodes: [`framework:${framework.framework}`, `framework_reason:${framework.reason}`, `goal_strategy:${input.goal}`, `experience:${input.experience}`, `frequency:${input.daysPerWeek}`] };
}

export type CanonicalLimitation = Readonly<{ kind: "exercise"; value: string } | { kind: "movement"; value: MovementPattern } | { kind: "equipment"; value: Equipment }>;
export function parseCanonicalLimitation(value: string): CanonicalLimitation | null {
  const [kind, raw, extra] = value.split(":");
  if (!raw || extra !== undefined) return null;
  if (kind === "exclude_exercise") return { kind: "exercise", value: raw };
  if (kind === "exclude_movement" && (["horizontal_push", "vertical_push", "horizontal_pull", "vertical_pull", "squat", "hinge", "lunge", "hip_thrust", "isolation", "carry", "core"] as string[]).includes(raw)) return { kind: "movement", value: raw as MovementPattern };
  if (kind === "exclude_equipment" && (["barbell", "dumbbell", "machine", "cable", "smith", "bodyweight", "bands", "other"] as string[]).includes(raw)) return { kind: "equipment", value: raw as Equipment };
  return null;
}

function preferredSplitForResolvedFramework(framework: string): PreferredSplit { return framework === "chest_back_shoulders_arms_legs" ? "body_part_split" : framework as PreferredSplit; }
