import type { PerformanceWindowResult, WindowDirection } from "@/domain/training/current-performance-window";
export type MultiWindowTrend = "improving" | "stable" | "mixed" | "declining" | "severe_acute_collapse" | "insufficient_evidence" | "insufficient_policy" | "invalid";
export type Rebound = "none_needed" | "full_rebound" | "partial_rebound" | "no_rebound" | "insufficient_evidence" | "insufficient_policy" | "invalid";
export type TrendSeriesPolicy = { positiveWindows: number; negativeWindows: number; severeNegativeWindow: number };
export function derivePerformanceTrendSeries(input: PerformanceWindowResult, policy?: TrendSeriesPolicy): { trend: MultiWindowTrend; rebound: Rebound; trace: { positive: string[]; negative: string[]; maintained: string[]; mixed: string[] } } {
  if (input.status === "insufficient_policy") return { trend:"insufficient_policy", rebound:"insufficient_policy", trace: empty() }; if (input.status !== "ready") return { trend: input.status === "insufficient_evidence" ? "insufficient_evidence" : "invalid", rebound: input.status === "insufficient_evidence" ? "insufficient_evidence" : "invalid", trace: empty() }; if (!policy || policy.positiveWindows <= 1 || policy.negativeWindows <= 1 || policy.severeNegativeWindow <= 0) return { trend:"insufficient_policy", rebound:"insufficient_policy", trace: empty() };
  const directions = input.windows.map((item) => ({ id:item.window.id, direction:item.direction })); const trace={ positive:ids(directions,"positive"), negative:ids(directions,"negative"), maintained:ids(directions,"maintained"), mixed:ids(directions,"mixed") }; const tail = directions.at(-1)?.direction; const negativeRun = run(directions,"negative"); const rebound: Rebound = trace.negative.length >= 2 && (tail === "positive" || tail === "maintained") ? "full_rebound" : trace.negative.length >= 2 ? "no_rebound" : "none_needed";
  if (directions.some((d) => d.direction === "invalid")) return { trend:"invalid", rebound:"invalid", trace }; if (negativeRun >= policy.severeNegativeWindow && tail === "negative") return { trend:"severe_acute_collapse", rebound, trace }; if (negativeRun >= policy.negativeWindows && rebound !== "full_rebound") return { trend:"declining", rebound, trace }; if (trace.positive.length >= policy.positiveWindows && trace.negative.length === 0) return { trend:"improving", rebound, trace }; if (trace.positive.length && trace.negative.length) return { trend:"mixed", rebound, trace }; return { trend:"stable", rebound, trace };
}
function ids(values: {id:string;direction:WindowDirection}[], direction: WindowDirection) { return values.filter((value)=>value.direction===direction).map((value)=>value.id); } function run(values: {id:string;direction:WindowDirection}[], direction:WindowDirection) { let n=0; for(let i=values.length-1;i>=0&&values[i]!.direction===direction;i--) n++; return n; } function empty(){return {positive:[],negative:[],maintained:[],mixed:[]};}
