import type { CreateCurrentProgrammeSpecificationInput } from "@/domain/training/current-programme-specification-construction";

export type CurrentProgrammeGuidancePolicyInput = Readonly<{ schemaVersion: "v1"; goal: string; experienceLevel: "beginner" | "intermediate" | "advanced"; trainingDays: number; split: string; mesocyclePurpose: "hypertrophy" | "strength" | "power" | "deload"; microcyclePriority: string; sessionRole: string; sessionIdentity: string; equipmentCapabilities: readonly string[]; constructionPolicyVersion: string; guidancePolicyVersion: string; weakPointTarget?: string; mandatoryMovement?: string }>;
export type CurrentPrescriptionSemanticTarget = Readonly<{ domain: "muscle_group" | "movement_pattern"; id: string }>;
export type CurrentSlotPurpose = "primary_compound" | "secondary_compound" | "primary_hypertrophy" | "secondary_hypertrophy" | "isolation" | "supporting_accessory" | "weak_point";
export type CurrentExerciseSelectionConstraints = Readonly<{ allowedMuscles: readonly string[]; allowedMovementPatterns: readonly string[]; exerciseClass: "compound" | "isolation" | "either"; equipmentCapabilities: readonly string[]; minimumExperience?: "beginner" | "intermediate" | "advanced"; substitutionPolicy: "preserve_target_and_movement" | "preserve_target" | "preserve_exercise_class" | "fixed_exercise_only" | "intervention_approved"; prohibitedExerciseIds: readonly string[] }>;
export type CurrentPrescriptionSlotDefinition = Readonly<{ schemaVersion: "v1"; target: CurrentPrescriptionSemanticTarget; purpose: CurrentSlotPurpose; ordinal: string; recommendedMinSets: number; recommendedMaxSets: number; constraints: CurrentExerciseSelectionConstraints; requirement: "required" | "conditional" | "optional"; omissionPolicy: "never_omit" | "omit_when_session_capacity_exceeded" | "omit_when_target_covered_elsewhere" | "omit_when_equipment_unavailable" | "omit_for_beginner_complexity"; guidancePolicyVersion: string; constructionPolicyVersion: string; rationaleCode?: string }>;
export type CurrentProgrammeGuidancePolicyResult = Readonly<{ status: "resolved"; definitions: readonly CurrentPrescriptionSlotDefinition[]; policyFingerprint: string }> | Readonly<{ status: "unsupported_goal" | "unsupported_mesocycle_purpose" | "unsupported_split" | "unsupported_session_role" | "unsupported_experience_level" | "invalid_input" | "insufficient_policy" | "equipment_incompatible" | "invalid_slot_definition"; reason: string }>;

export function validateCurrentPrescriptionSlotDefinition(definition: CurrentPrescriptionSlotDefinition): string | null { if (!definition.target.id || !definition.ordinal || definition.recommendedMinSets < 0 || definition.recommendedMaxSets < definition.recommendedMinSets) return "invalid_target_or_range"; if (definition.constraints.exerciseClass === "compound" && definition.purpose === "isolation") return "purpose_constraint_conflict"; if (definition.requirement === "required" && definition.omissionPolicy !== "never_omit") return "required_slot_cannot_be_omittable"; if (!definition.guidancePolicyVersion || !definition.constructionPolicyVersion) return "missing_policy_version"; return null; }
export function copyCurrentPrescriptionSlotDefinitions(definitions: readonly CurrentPrescriptionSlotDefinition[]): readonly CurrentPrescriptionSlotDefinition[] { return definitions.map((definition) => ({ ...definition, target: { ...definition.target }, constraints: { ...definition.constraints, allowedMuscles: [...definition.constraints.allowedMuscles].sort(), allowedMovementPatterns: [...definition.constraints.allowedMovementPatterns].sort(), equipmentCapabilities: [...definition.constraints.equipmentCapabilities].sort(), prohibitedExerciseIds: [...definition.constraints.prohibitedExerciseIds].sort() } })); }
export function fingerprintCurrentProgrammeGuidancePolicy(input: CurrentProgrammeGuidancePolicyInput): string { return [input.goal, input.experienceLevel, input.trainingDays, input.split, input.mesocyclePurpose, input.microcyclePriority, input.sessionRole, input.sessionIdentity, [...input.equipmentCapabilities].sort().join(","), input.guidancePolicyVersion, input.constructionPolicyVersion, input.weakPointTarget ?? "", input.mandatoryMovement ?? ""].join("|"); }
export function mapPolicySlotToD2Input(definition: CurrentPrescriptionSlotDefinition, id: string): CreateCurrentProgrammeSpecificationInput["sessionTemplates"][number]["prescriptionSlots"][number] { const reason = validateCurrentPrescriptionSlotDefinition(definition); if (reason) throw new Error(reason); return { id, ordinal: definition.ordinal, targetDomain: definition.target.domain === "muscle_group" ? "muscle" : "movement_pattern", targetId: definition.target.id, purpose: definition.purpose, recommendedMinSets: definition.recommendedMinSets, recommendedMaxSets: definition.recommendedMaxSets, guidancePolicyVersion: definition.guidancePolicyVersion, selectionConstraints: [...definition.constraints.allowedMuscles, ...definition.constraints.allowedMovementPatterns, definition.constraints.exerciseClass, definition.constraints.substitutionPolicy].filter(Boolean) }; }
