import { hydrateCurrentMesocycleProgrammeSpecification, type CurrentMesocycleProgrammeSpecification, type CurrentMicrocycleProgrammeReference } from "@/domain/training/current-programme-specification";

export type CreateCurrentProgrammeSpecificationInput = Readonly<{ planId: string; mesocycleId: string; mesocyclePurpose: string; programmeId: string; sessionTemplates: readonly Readonly<{ id: string; orderingKey: string; sessionRole: string; purpose: string; constructionPolicyVersion: string; prescriptionSlots: readonly Readonly<{ id: string; ordinal: string; targetDomain: "muscle" | "movement_pattern" | "exercise_slot"; targetId: string; purpose: string; recommendedMinSets: number; recommendedMaxSets: number; guidancePolicyVersion: string; selectionConstraints: readonly string[] }> [] }> []; purposePolicyVersion: string; firstMicrocycleNumber?: number; creationSource: "new_current_plan" | "new_current_mesocycle" }>;
export type CurrentProgrammeConstructionResult = Readonly<{ status: "created"; specification: CurrentMesocycleProgrammeSpecification; initialMicrocycleReference?: CurrentMicrocycleProgrammeReference }> | Readonly<{ status: "invalid_input" | "duplicate_identity" | "insufficient_slot_definition" | "invalid_programme"; reason: string }>;

/** Pure construction from approved pre-exercise intent and supplied identities. */
export function constructCurrentProgrammeSpecification(input: CreateCurrentProgrammeSpecificationInput): CurrentProgrammeConstructionResult {
  if (!input.planId || !input.mesocycleId || !input.programmeId || !input.mesocyclePurpose || !input.purposePolicyVersion) return { status: "invalid_input", reason: "missing_programme_identity" };
  const templateIds = new Set<string>(); const slotIds = new Set<string>();
  for (const template of input.sessionTemplates) { if (!template.id || !template.orderingKey || !template.sessionRole || !template.purpose || templateIds.has(template.id)) return { status: "duplicate_identity", reason: "template_identity_invalid" }; templateIds.add(template.id); for (const slot of template.prescriptionSlots) { if (!slot.id || !slot.ordinal || !slot.targetId || !slot.purpose || slotIds.has(slot.id)) return { status: "duplicate_identity", reason: "slot_identity_invalid" }; if (slot.recommendedMinSets < 0 || slot.recommendedMaxSets < slot.recommendedMinSets || slot.selectionConstraints.length === 0) return { status: "insufficient_slot_definition", reason: "slot_guidance_or_constraints_invalid" }; slotIds.add(slot.id); } }
  const specification: CurrentMesocycleProgrammeSpecification = { schemaVersion: "v1", planId: input.planId, mesocycleId: input.mesocycleId, programmeId: input.programmeId, version: 1, purposePolicyVersion: input.purposePolicyVersion, creationReason: "initial", sourceAdjustmentIds: [], sessionTemplates: input.sessionTemplates.map((template) => ({ schemaVersion: "v1", id: template.id, programmeId: input.programmeId, programmeVersion: 1, orderingKey: template.orderingKey, sessionRole: template.sessionRole, purpose: template.purpose, constructionPolicyVersion: template.constructionPolicyVersion, prescriptionSlots: template.prescriptionSlots.map((slot) => ({ schemaVersion: "v1", id: slot.id, programmeId: input.programmeId, programmeVersion: 1, sessionTemplateId: template.id, ordinal: slot.ordinal, targetDomain: slot.targetDomain, targetId: slot.targetId, purpose: slot.purpose, recommendedMinSets: slot.recommendedMinSets, recommendedMaxSets: slot.recommendedMaxSets, targetVersion: 1, guidancePolicyVersion: slot.guidancePolicyVersion, selectionConstraints: [...slot.selectionConstraints] })) })) };
  const hydrated = hydrateCurrentMesocycleProgrammeSpecification(specification); if (hydrated.status !== "hydrated_current_programme") return { status: "invalid_programme", reason: hydrated.reason };
  const initialMicrocycleReference = input.firstMicrocycleNumber ? { schemaVersion: "v1" as const, planId: input.planId, mesocycleId: input.mesocycleId, microcycleNumber: input.firstMicrocycleNumber, programmeId: input.programmeId, programmeVersion: 1, bindingLifecycle: "bound" as const, policyVersion: input.purposePolicyVersion } : undefined;
  return { status: "created", specification: hydrated.specification, initialMicrocycleReference };
}
