import type { MultiWindowTrend, Rebound } from "@/domain/training/current-performance-trend-series";
export type PerformanceFatigueState = "normal" | "watch" | "deload_eligible" | "deload_required" | "insufficient_evidence" | "insufficient_policy" | "invalid";
export type FatiguePolicy = { version: 1; id: string; watchNegativeWindows: number; eligibleNegativeWindows: number; requiredNegativeWindows?: number; allowSevereAcute: boolean; reboundClearsWatch: boolean };
export type LowStressSuccessorContext = { status: "available" | "unavailable" | "unknown"; candidateIds: readonly string[] };
export function classifyPerformanceFatigue(input: { trend: MultiWindowTrend; rebound: Rebound; negativeWindows: number; policy?: FatiguePolicy; lowStressSuccessor: LowStressSuccessorContext }): { state: PerformanceFatigueState; trace: { reason: string; negativeWindows: number; lowStressSuccessor: LowStressSuccessorContext } } {
  const trace = (state: PerformanceFatigueState, reason: string) => ({ state, trace: { reason, negativeWindows: input.negativeWindows, lowStressSuccessor: input.lowStressSuccessor } });
  if (!input.policy) return trace("insufficient_policy", "missing_policy"); const p=input.policy; if (p.version!==1 || p.watchNegativeWindows<=0 || p.eligibleNegativeWindows<p.watchNegativeWindows || (p.requiredNegativeWindows != null && p.requiredNegativeWindows<p.eligibleNegativeWindows)) return trace("invalid","invalid_policy");
  if (input.trend === "invalid") return trace("invalid","invalid_trend"); if (input.trend === "insufficient_evidence" || input.trend === "insufficient_policy") return trace("insufficient_evidence","insufficient_trend"); if (input.rebound === "full_rebound" && p.reboundClearsWatch) return trace("normal","full_performance_rebound");
  if (input.trend === "severe_acute_collapse") return trace(p.allowSevereAcute ? "deload_eligible" : "watch","severe_performance_collapse"); if (input.trend === "declining" && input.negativeWindows >= (p.requiredNegativeWindows ?? Number.POSITIVE_INFINITY)) return trace("deload_required","sustained_converging_decline"); if (input.trend === "declining" && input.negativeWindows >= p.eligibleNegativeWindows) return trace("deload_eligible","sustained_decline"); if ((input.trend === "declining" || input.trend === "mixed") && input.negativeWindows >= p.watchNegativeWindows) return trace("watch","concerning_performance_evidence"); return trace("normal","no_converging_performance_evidence");
}
