import { mesocycleById, type MesocycleId } from "@/domain/training/mesocycle-library";

export const CURRENT_MESOCYCLE_PROGRAMME_POLICY_MAPPING_SCHEMA = "v1" as const;
export const CURRENT_MESOCYCLE_PROGRAMME_POLICY_REGISTRY = "current_mesocycle_programme_policy_registry_v1" as const;
export const CERTIFIED_UPPER_LOWER_PROGRAMME_FAMILY = "intermediate_four_day_full_gym_upper_lower" as const;
export const CERTIFIED_UPPER_LOWER_TEMPLATE_FAMILY = "upper_lower_ab_v1" as const;

export type CurrentProgrammeFamilyId = typeof CERTIFIED_UPPER_LOWER_PROGRAMME_FAMILY;
export type CurrentProgrammeTemplateFamilyId = typeof CERTIFIED_UPPER_LOWER_TEMPLATE_FAMILY;
export type CurrentMesocycleProgrammePolicyMappingInput = Readonly<{ schemaVersion: typeof CURRENT_MESOCYCLE_PROGRAMME_POLICY_MAPPING_SCHEMA; registryVersion: typeof CURRENT_MESOCYCLE_PROGRAMME_POLICY_REGISTRY | string; goal: string; experienceLevel: "beginner" | "intermediate" | "advanced"; trainingDays: number; split: string; mesocyclePurpose: MesocycleId | string; equipmentCapabilities: readonly string[]; programmeFamilyId: CurrentProgrammeFamilyId | string; sessionTemplateFamilyId: CurrentProgrammeTemplateFamilyId | string; constructionPolicyVersion?: string }>;
export type CurrentProgrammeGuidancePolicyReference = Readonly<{ policyId: "certified_upper_lower_hypertrophy_v1"; policyVersion: "v1"; structuralTemplateFamilyId: CurrentProgrammeTemplateFamilyId; certificationId: "hypertrophy_base_upper_lower_equivalence_v1"; certificationVersion: "v1"; supportedGoal: "build_muscle"; supportedPurpose: "hypertrophy_base"; supportedProgrammeFamily: CurrentProgrammeFamilyId }>;
export type CurrentProgrammePolicyCapabilities = Readonly<{ mayResolveSlots: boolean; mayConstructProgrammeSpecification: boolean; mayPersistCurrentProgramme: boolean; mayApplyCurrentGuidanceAdjustment: boolean }>;
export type CurrentMesocycleProgrammePolicyMappingStatus = "supported" | "candidate_pending_certification" | "dedicated_policy_required" | "unsupported_programme_family" | "unsupported_mesocycle_purpose" | "invalid_input" | "unsupported_registry";
export type CurrentMesocycleProgrammePolicyMappingResult = Readonly<{ status: "supported"; reason: "policy_certified_for_exact_purpose"; policy: CurrentProgrammeGuidancePolicyReference; capabilities: CurrentProgrammePolicyCapabilities; compatibilityConsequence: "continue_compatibility_plan"; inputFingerprint: string; resultFingerprint: string }> | Readonly<{ status: "candidate_pending_certification"; reason: "base_policy_requires_field_equivalence_certification"; policy: CurrentProgrammeGuidancePolicyReference; capabilities: CurrentProgrammePolicyCapabilities; compatibilityConsequence: "continue_compatibility_plan"; inputFingerprint: string; resultFingerprint: string }> | Readonly<{ status: "dedicated_policy_required"; reason: "calibration_requires_conservative_programme_policy" | "volume_requires_dedicated_guidance_policy" | "specialisation_policy_not_implemented" | "consolidation_policy_not_implemented" | "transition_policy_not_implemented"; capabilities: CurrentProgrammePolicyCapabilities; compatibilityConsequence: "continue_compatibility_plan"; inputFingerprint: string; resultFingerprint: string }> | Readonly<{ status: "unsupported_programme_family"; reason: "programme_family_not_certified"; capabilities: CurrentProgrammePolicyCapabilities; compatibilityConsequence: "continue_compatibility_plan"; inputFingerprint: string; resultFingerprint: string }> | Readonly<{ status: "unsupported_mesocycle_purpose"; reason: "purpose_not_registered"; capabilities: CurrentProgrammePolicyCapabilities; compatibilityConsequence: "continue_compatibility_plan"; inputFingerprint: string; resultFingerprint: string }> | Readonly<{ status: "invalid_input"; reason: "mapping_input_conflict"; capabilities: CurrentProgrammePolicyCapabilities; compatibilityConsequence: "block_invalid_input"; inputFingerprint: string; resultFingerprint: string }> | Readonly<{ status: "unsupported_registry"; reason: "mapping_schema_or_registry_not_supported"; capabilities: CurrentProgrammePolicyCapabilities; compatibilityConsequence: "block_unsupported_schema"; inputFingerprint: string; resultFingerprint: string }>;

const noCapabilities: CurrentProgrammePolicyCapabilities = Object.freeze({ mayResolveSlots: false, mayConstructProgrammeSpecification: false, mayPersistCurrentProgramme: false, mayApplyCurrentGuidanceAdjustment: false });
const certifiedBasePolicy: CurrentProgrammeGuidancePolicyReference = Object.freeze({ policyId: "certified_upper_lower_hypertrophy_v1", policyVersion: "v1", structuralTemplateFamilyId: CERTIFIED_UPPER_LOWER_TEMPLATE_FAMILY, certificationId: "hypertrophy_base_upper_lower_equivalence_v1", certificationVersion: "v1", supportedGoal: "build_muscle", supportedPurpose: "hypertrophy_base", supportedProgrammeFamily: CERTIFIED_UPPER_LOWER_PROGRAMME_FAMILY });
const dedicatedReasons: Readonly<Record<"hypertrophy_calibration" | "hypertrophy_volume" | "hypertrophy_specialisation" | "hypertrophy_consolidation" | "hypertrophy_transition", Extract<CurrentMesocycleProgrammePolicyMappingResult, { status: "dedicated_policy_required" }> ["reason"]>> = Object.freeze({ hypertrophy_calibration: "calibration_requires_conservative_programme_policy", hypertrophy_volume: "volume_requires_dedicated_guidance_policy", hypertrophy_specialisation: "specialisation_policy_not_implemented", hypertrophy_consolidation: "consolidation_policy_not_implemented", hypertrophy_transition: "transition_policy_not_implemented" });

export function copyCurrentMesocycleProgrammePolicyMappingInput(input: CurrentMesocycleProgrammePolicyMappingInput): CurrentMesocycleProgrammePolicyMappingInput { return { ...input, equipmentCapabilities: [...input.equipmentCapabilities].sort() }; }
export function fingerprintCurrentMesocycleProgrammePolicyMappingInput(input: CurrentMesocycleProgrammePolicyMappingInput): string { const copy = copyCurrentMesocycleProgrammePolicyMappingInput(input); return [copy.schemaVersion, copy.registryVersion, copy.goal, copy.experienceLevel, copy.trainingDays, copy.split, copy.mesocyclePurpose, copy.equipmentCapabilities.join(","), copy.programmeFamilyId, copy.sessionTemplateFamilyId, copy.constructionPolicyVersion ?? ""].join("|"); }
export function copyCurrentMesocycleProgrammePolicyMappingResult(result: CurrentMesocycleProgrammePolicyMappingResult): CurrentMesocycleProgrammePolicyMappingResult { return { ...result, capabilities: { ...result.capabilities }, ...("policy" in result ? { policy: { ...result.policy } } : {}) } as CurrentMesocycleProgrammePolicyMappingResult; }
export function canConstructCurrentProgrammeSpecification(result: CurrentMesocycleProgrammePolicyMappingResult): boolean { return result.status === "supported" && result.capabilities.mayConstructProgrammeSpecification; }

export function resolveCurrentMesocycleProgrammePolicyMapping(input: CurrentMesocycleProgrammePolicyMappingInput): CurrentMesocycleProgrammePolicyMappingResult {
  const fingerprint = fingerprintCurrentMesocycleProgrammePolicyMappingInput(input);
  const result = (status: CurrentMesocycleProgrammePolicyMappingResult["status"], reason: string, compatibilityConsequence: "continue_compatibility_plan" | "block_invalid_input" | "block_unsupported_schema", policy?: CurrentProgrammeGuidancePolicyReference): CurrentMesocycleProgrammePolicyMappingResult => {
    const resultFingerprint = [fingerprint, status, reason, policy?.policyId ?? "", policy?.policyVersion ?? ""].join("|");
    return policy ? { status: "supported", reason: "policy_certified_for_exact_purpose", policy: { ...policy }, capabilities: { mayResolveSlots: true, mayConstructProgrammeSpecification: true, mayPersistCurrentProgramme: false, mayApplyCurrentGuidanceAdjustment: false }, compatibilityConsequence: "continue_compatibility_plan", inputFingerprint: fingerprint, resultFingerprint } : { status: status as Exclude<CurrentMesocycleProgrammePolicyMappingResult["status"], "candidate_pending_certification">, reason: reason as never, capabilities: { ...noCapabilities }, compatibilityConsequence, inputFingerprint: fingerprint, resultFingerprint } as CurrentMesocycleProgrammePolicyMappingResult;
  };
  if (input.schemaVersion !== CURRENT_MESOCYCLE_PROGRAMME_POLICY_MAPPING_SCHEMA || input.registryVersion !== CURRENT_MESOCYCLE_PROGRAMME_POLICY_REGISTRY) return result("unsupported_registry", "mapping_schema_or_registry_not_supported", "block_unsupported_schema");
  const purpose = mesocycleById(input.mesocyclePurpose as MesocycleId);
  if (!purpose) return result("unsupported_mesocycle_purpose", "purpose_not_registered", "continue_compatibility_plan");
  if (purpose.engine !== "hypertrophy" || input.goal !== "build_muscle" || !Number.isInteger(input.trainingDays) || input.trainingDays < 1 || !input.split || !input.equipmentCapabilities.length) return result("invalid_input", "mapping_input_conflict", "block_invalid_input");
  const certifiedFamily = input.experienceLevel === "intermediate" && input.trainingDays === 4 && input.split === "upper_lower" && input.equipmentCapabilities.includes("full_gym") && input.programmeFamilyId === CERTIFIED_UPPER_LOWER_PROGRAMME_FAMILY && input.sessionTemplateFamilyId === CERTIFIED_UPPER_LOWER_TEMPLATE_FAMILY;
  if (!certifiedFamily) return result("unsupported_programme_family", "programme_family_not_certified", "continue_compatibility_plan");
  if (purpose.id === "hypertrophy_base") return result("supported", "policy_certified_for_exact_purpose", "continue_compatibility_plan", certifiedBasePolicy);
  return result("dedicated_policy_required", dedicatedReasons[purpose.id as keyof typeof dedicatedReasons] ?? "transition_policy_not_implemented", "continue_compatibility_plan");
}

export const currentHypertrophyMesocyclePurposeRegistry: readonly MesocycleId[] = Object.freeze(["hypertrophy_calibration", "hypertrophy_base", "hypertrophy_volume", "hypertrophy_specialisation", "hypertrophy_consolidation", "hypertrophy_transition"]);
