export type RecommendedSetGuidanceTargetIdentity = Readonly<{ schemaVersion: "v1"; planId: string; mesocycleId: string; parentProgrammeId: string; parentProgrammeVersion: string; guidanceSlotId: string; targetDomain: "programme_guidance_slot"; guidancePolicyVersion: string }>;
export type RecommendedSetGuidanceEffectiveTiming = Readonly<{ schemaVersion: "v1"; planId: string; mesocycleId: string; effectiveMicrocycleNumber: number; timingPolicyVersion: "next_eligible_normal_microcycle_v1" }>;
export type CurrentRecommendedSetGuidanceAdjustmentRecord = Readonly<{ id: string; schemaVersion: "v1"; kind: "raise_range" | "lower_range"; direction: "raise" | "lower"; magnitude: number; target: RecommendedSetGuidanceTargetIdentity; expectedTargetVersion: string; normalizationPolicyVersion: string; timing: Readonly<{ state: "unresolved_pending_decision" } | { state: "resolved_next_normal_microcycle"; effective: RecommendedSetGuidanceEffectiveTiming }>; lifecycle: "proposed" | "ready" | "applied" | "stale" | "superseded" | "failed"; semanticIdempotencyKey: string; createdAt: string; evidenceIds: readonly string[] }>;
export type CurrentGuidanceRecordHydration = Readonly<{ status: "hydrated_current"; record: CurrentRecommendedSetGuidanceAdjustmentRecord }> | Readonly<{ status: "hydrated_legacy_compatibility" | "invalid_record" | "unsupported_schema"; reason: string }>;
export type CurrentGuidanceRecordInput = Omit<CurrentRecommendedSetGuidanceAdjustmentRecord, "semanticIdempotencyKey">;

export function createCurrentRecommendedSetGuidanceAdjustmentRecord(input: CurrentGuidanceRecordInput): CurrentGuidanceRecordHydration {
  const validation = validate(input);
  if (validation) return { status: "invalid_record", reason: validation };
  return { status: "hydrated_current", record: { ...input, target: { ...input.target }, timing: input.timing.state === "resolved_next_normal_microcycle" ? { state: input.timing.state, effective: { ...input.timing.effective } } : { state: input.timing.state }, evidenceIds: [...input.evidenceIds], semanticIdempotencyKey: semanticIdempotencyKey(input) } };
}
export function hydrateRecommendedSetGuidanceAdjustmentRecord(value: unknown): CurrentGuidanceRecordHydration {
  if (!value || typeof value !== "object") return { status: "invalid_record", reason: "record_not_object" };
  const candidate = value as Partial<CurrentRecommendedSetGuidanceAdjustmentRecord>;
  if (candidate.schemaVersion !== "v1") return candidate && "blockId" in candidate ? { status: "hydrated_legacy_compatibility", reason: "legacy_block_scoped_record" } : { status: "unsupported_schema", reason: "unknown_schema" };
  return createCurrentRecommendedSetGuidanceAdjustmentRecord(candidate as CurrentGuidanceRecordInput);
}
export function semanticIdempotencyKey(input: CurrentGuidanceRecordInput): string { const timing = input.timing.state === "resolved_next_normal_microcycle" ? `${input.timing.effective.planId}:${input.timing.effective.mesocycleId}:${input.timing.effective.effectiveMicrocycleNumber}:${input.timing.effective.timingPolicyVersion}` : input.timing.state; return [input.id, input.target.planId, input.target.mesocycleId, input.target.parentProgrammeId, input.target.parentProgrammeVersion, input.target.guidanceSlotId, input.expectedTargetVersion, timing, input.normalizationPolicyVersion].join("|"); }
function validate(input: CurrentGuidanceRecordInput): string | null { if (!input.id || !input.target.planId || !input.target.mesocycleId || !input.target.parentProgrammeId || !input.target.parentProgrammeVersion || !input.target.guidanceSlotId) return "target_identity_incomplete"; if (!Number.isInteger(input.magnitude) || input.magnitude <= 0) return "invalid_magnitude"; if ((input.kind === "raise_range") !== (input.direction === "raise")) return "kind_direction_mismatch"; if (input.lifecycle === "applied" && input.timing.state !== "resolved_next_normal_microcycle") return "applied_requires_resolved_timing"; if (input.timing.state === "resolved_next_normal_microcycle" && (input.timing.effective.planId !== input.target.planId || input.timing.effective.mesocycleId !== input.target.mesocycleId || input.timing.effective.effectiveMicrocycleNumber < 1)) return "invalid_effective_timing"; return null; }
