import { copyCurrentPrescriptionSlotDefinitions, fingerprintCurrentProgrammeGuidancePolicy, type CurrentProgrammeGuidancePolicyInput, type CurrentProgrammeGuidancePolicyResult, type CurrentPrescriptionSlotDefinition } from "@/domain/training/current-programme-guidance-policy-contracts";

const policyVersion = "hypertrophy_programme_guidance_v1";
/** One deliberately narrow representative policy: intermediate, four-day Upper/Lower, normal hypertrophy Upper. */
export function resolveCurrentHypertrophyProgrammeGuidance(input: CurrentProgrammeGuidancePolicyInput): CurrentProgrammeGuidancePolicyResult {
  if (input.goal !== "build_muscle") return { status: "unsupported_goal", reason: "representative_policy_supports_hypertrophy_goal_only" };
  if (input.mesocyclePurpose !== "hypertrophy") return { status: "unsupported_mesocycle_purpose", reason: "purpose_not_implemented" };
  if (input.experienceLevel !== "intermediate") return { status: "unsupported_experience_level", reason: "experience_not_implemented" };
  if (input.trainingDays !== 4 || input.split !== "upper_lower") return { status: "unsupported_split", reason: "representative_policy_supports_four_day_upper_lower_only" };
  if (input.sessionRole !== "Upper" || input.sessionIdentity !== "upper-a") return { status: "unsupported_session_role", reason: "representative_policy_supports_upper_a_only" };
  if (input.microcyclePriority !== "normal_productive") return { status: "insufficient_policy", reason: "microcycle_priority_not_implemented" };
  if (!input.equipmentCapabilities.includes("full_gym")) return { status: "equipment_incompatible", reason: "representative_policy_requires_full_gym_capability" };
  const definitions = slots(input.constructionPolicyVersion); return { status: "resolved", definitions: copyCurrentPrescriptionSlotDefinitions(definitions), policyFingerprint: fingerprintCurrentProgrammeGuidancePolicy(input) };
}
/** Matching Lower-A representative policy; all other Lower variants remain unsupported. */
export function resolveCurrentHypertrophyLowerProgrammeGuidance(input: CurrentProgrammeGuidancePolicyInput): CurrentProgrammeGuidancePolicyResult {
  if (input.goal !== "build_muscle") return { status: "unsupported_goal", reason: "representative_policy_supports_hypertrophy_goal_only" };
  if (input.mesocyclePurpose !== "hypertrophy") return { status: "unsupported_mesocycle_purpose", reason: "purpose_not_implemented" };
  if (input.experienceLevel !== "intermediate") return { status: "unsupported_experience_level", reason: "experience_not_implemented" };
  if (input.trainingDays !== 4 || input.split !== "upper_lower") return { status: "unsupported_split", reason: "representative_policy_supports_four_day_upper_lower_only" };
  if (input.sessionRole !== "Lower" || input.sessionIdentity !== "lower-a") return { status: "unsupported_session_role", reason: "representative_policy_supports_lower_a_only" };
  if (input.microcyclePriority !== "normal_productive") return { status: "insufficient_policy", reason: "microcycle_priority_not_implemented" };
  if (!input.equipmentCapabilities.includes("full_gym")) return { status: "equipment_incompatible", reason: "representative_policy_requires_full_gym_capability" };
  const definitions = lowerSlots(input.constructionPolicyVersion); return { status: "resolved", definitions: copyCurrentPrescriptionSlotDefinitions(definitions), policyFingerprint: fingerprintCurrentProgrammeGuidancePolicy(input) };
}
export function resolveCurrentHypertrophyUpperBProgrammeGuidance(input: CurrentProgrammeGuidancePolicyInput): CurrentProgrammeGuidancePolicyResult { const valid = validateRepresentative(input, "Upper", "upper-b"); if (valid) return valid; return { status: "resolved", definitions: copyCurrentPrescriptionSlotDefinitions(upperBSlots(input.constructionPolicyVersion)), policyFingerprint: fingerprintCurrentProgrammeGuidancePolicy(input) }; }
export function resolveCurrentHypertrophyLowerBProgrammeGuidance(input: CurrentProgrammeGuidancePolicyInput): CurrentProgrammeGuidancePolicyResult { const valid = validateRepresentative(input, "Lower", "lower-b"); if (valid) return valid; return { status: "resolved", definitions: copyCurrentPrescriptionSlotDefinitions(lowerBSlots(input.constructionPolicyVersion)), policyFingerprint: fingerprintCurrentProgrammeGuidancePolicy(input) }; }
function validateRepresentative(input: CurrentProgrammeGuidancePolicyInput, role: string, identity: string): Exclude<CurrentProgrammeGuidancePolicyResult, { status: "resolved" }> | null { if (input.goal !== "build_muscle") return { status: "unsupported_goal", reason: "representative_policy_supports_hypertrophy_goal_only" }; if (input.mesocyclePurpose !== "hypertrophy") return { status: "unsupported_mesocycle_purpose", reason: "purpose_not_implemented" }; if (input.experienceLevel !== "intermediate") return { status: "unsupported_experience_level", reason: "experience_not_implemented" }; if (input.trainingDays !== 4 || input.split !== "upper_lower") return { status: "unsupported_split", reason: "representative_policy_supports_four_day_upper_lower_only" }; if (input.sessionRole !== role || input.sessionIdentity !== identity) return { status: "unsupported_session_role", reason: "representative_policy_session_identity_not_implemented" }; if (input.microcyclePriority !== "normal_productive") return { status: "insufficient_policy", reason: "microcycle_priority_not_implemented" }; if (!input.equipmentCapabilities.includes("full_gym")) return { status: "equipment_incompatible", reason: "representative_policy_requires_full_gym_capability" }; return null; }
function slots(constructionPolicyVersion: string): readonly CurrentPrescriptionSlotDefinition[] { const base = { schemaVersion: "v1" as const, guidancePolicyVersion: policyVersion, constructionPolicyVersion }; const compound = (ordinal: string, targetId: string, purpose: "primary_compound" | "secondary_compound", min: number, max: number, muscle: string, movement: string): CurrentPrescriptionSlotDefinition => ({ ...base, target: { domain: "movement_pattern", id: targetId }, purpose, ordinal, recommendedMinSets: min, recommendedMaxSets: max, constraints: { allowedMuscles: [muscle], allowedMovementPatterns: [movement], exerciseClass: "compound", equipmentCapabilities: ["full_gym"], substitutionPolicy: "preserve_target_and_movement", prohibitedExerciseIds: [] }, requirement: "required", omissionPolicy: "never_omit", rationaleCode: "compound_before_isolation" }); const isolation = (ordinal: string, target: string, movement: string, purpose: "isolation" | "supporting_accessory", min: number, max: number, optional = false): CurrentPrescriptionSlotDefinition => ({ ...base, target: { domain: "muscle_group", id: target }, purpose, ordinal, recommendedMinSets: min, recommendedMaxSets: max, constraints: { allowedMuscles: [target], allowedMovementPatterns: [movement], exerciseClass: "isolation", equipmentCapabilities: ["full_gym"], substitutionPolicy: "preserve_target", prohibitedExerciseIds: [] }, requirement: optional ? "optional" : "required", omissionPolicy: optional ? "omit_when_session_capacity_exceeded" : "never_omit", rationaleCode: optional ? "direct_arm_accessory" : "direct_lateral_deltoid_stimulus" }); return [compound("01-primary-horizontal-press", "horizontal_press", "primary_compound", 3, 4, "chest", "horizontal_press"), compound("02-primary-horizontal-pull", "horizontal_pull", "primary_compound", 3, 4, "upper_back", "horizontal_pull"), compound("03-secondary-vertical-press", "vertical_press", "secondary_compound", 2, 3, "shoulders", "vertical_press"), compound("04-secondary-vertical-pull", "vertical_pull", "secondary_compound", 2, 3, "lats", "vertical_pull"), isolation("05-lateral-deltoid", "lateral_deltoids", "shoulder_abduction", "isolation", 2, 3), isolation("06-elbow-flexion", "biceps", "elbow_flexion", "supporting_accessory", 2, 3, true), isolation("07-elbow-extension", "triceps", "elbow_extension", "supporting_accessory", 2, 3, true)]; }
function lowerSlots(constructionPolicyVersion: string): readonly CurrentPrescriptionSlotDefinition[] { const base = { schemaVersion: "v1" as const, guidancePolicyVersion: policyVersion, constructionPolicyVersion }; const compound = (ordinal: string, targetId: string, purpose: "primary_compound" | "secondary_compound", min: number, max: number, muscle: string): CurrentPrescriptionSlotDefinition => ({ ...base, target: { domain: "movement_pattern", id: targetId }, purpose, ordinal, recommendedMinSets: min, recommendedMaxSets: max, constraints: { allowedMuscles: [muscle], allowedMovementPatterns: [targetId], exerciseClass: "compound", equipmentCapabilities: ["full_gym"], substitutionPolicy: "preserve_target_and_movement", prohibitedExerciseIds: [] }, requirement: "required", omissionPolicy: "never_omit", rationaleCode: "lower_compound_priority" }); const isolation = (ordinal: string, muscle: string, movement: string, min: number, max: number, optional = false): CurrentPrescriptionSlotDefinition => ({ ...base, target: { domain: "muscle_group", id: muscle }, purpose: "isolation", ordinal, recommendedMinSets: min, recommendedMaxSets: max, constraints: { allowedMuscles: [muscle], allowedMovementPatterns: [movement], exerciseClass: "isolation", equipmentCapabilities: ["full_gym"], substitutionPolicy: "preserve_target", prohibitedExerciseIds: [] }, requirement: optional ? "optional" : "required", omissionPolicy: optional ? "omit_when_session_capacity_exceeded" : "never_omit", rationaleCode: "direct_lower_accessory" }); return [compound("01-primary-knee-dominant", "knee_dominant", "primary_compound", 3, 4, "quadriceps"), compound("02-primary-hip-hinge", "hip_hinge", "primary_compound", 2, 3, "hamstrings"), compound("03-secondary-knee-dominant", "unilateral_knee_dominant", "secondary_compound", 2, 3, "quadriceps"), isolation("04-knee-flexion", "hamstrings", "knee_flexion", 2, 3), isolation("05-calf", "calves", "plantar_flexion", 2, 3), isolation("06-trunk", "abdominals", "trunk_stability", 2, 3, true)]; }
function upperBSlots(constructionPolicyVersion: string): readonly CurrentPrescriptionSlotDefinition[] { return reorderUpper(constructionPolicyVersion, ["vertical_pull", "vertical_press", "horizontal_pull", "horizontal_press"]); }
function reorderUpper(constructionPolicyVersion: string, patterns: readonly string[]): readonly CurrentPrescriptionSlotDefinition[] { const source = slots(constructionPolicyVersion); const compounds = patterns.map((pattern, index) => { const found = source.find((slot) => slot.target.domain === "movement_pattern" && slot.target.id === pattern)!; return { ...found, ordinal: `0${index + 1}-${pattern}`, purpose: index < 2 ? "primary_compound" as const : "secondary_compound" as const, recommendedMinSets: index < 2 ? 3 : 2, recommendedMaxSets: index < 2 ? 4 : 3 }; }); return [...compounds, ...source.slice(4)]; }
function lowerBSlots(constructionPolicyVersion: string): readonly CurrentPrescriptionSlotDefinition[] { const source = lowerSlots(constructionPolicyVersion); const hinge = source[1]!; const knee = source[0]!; const quad = { ...source[2]!, ordinal: "03-secondary-knee-dominant", target: { domain: "muscle_group" as const, id: "quadriceps" }, purpose: "isolation" as const, recommendedMinSets: 2, recommendedMaxSets: 3, constraints: { ...source[2]!.constraints, allowedMovementPatterns: ["knee_extension"], exerciseClass: "isolation" as const, substitutionPolicy: "preserve_target" as const } }; return [{ ...hinge, ordinal: "01-primary-hip-hinge", recommendedMinSets: 3, recommendedMaxSets: 4 }, { ...knee, ordinal: "02-secondary-knee-dominant", purpose: "secondary_compound" as const, recommendedMinSets: 2, recommendedMaxSets: 3 }, quad, ...source.slice(3).map((slot) => ({ ...slot }))]; }
