import type { MesocycleId } from "@/domain/training/mesocycle-library";
import type { DecisionEvidenceSummary } from "@/domain/training/current-progression-transition-decision-record";
import type { MesocycleDecisionInput } from "@/domain/training/current-progression-transition-decision";
export const CURRENT_READINESS_SCHEMA = 1 as const;
export type ReadinessState = "ready" | "in_progress" | "insufficient_evidence" | "insufficient_policy" | "blocked" | "disrupted" | "invalid";
export type CurrentReadinessDecisionContext = Readonly<{ evaluatorInput: MesocycleDecisionInput; evidence: DecisionEvidenceSummary }>;
export type CurrentReadinessSnapshot = { schemaVersion: typeof CURRENT_READINESS_SCHEMA; id: string; planId: string; mesocycleId: MesocycleId; microcycleNumber: number; createdAt: string; state: ReadinessState; sourceFingerprint: string; sourceWorkoutIds: readonly string[]; sourceSessionIds: readonly string[]; requiredRoles: readonly string[]; completedRoles: readonly string[]; unresolvedRoles: readonly string[]; blockedRoles: readonly string[]; approvedSuccessors: readonly MesocycleId[]; supersededSnapshotId?: string; decisionContext?: CurrentReadinessDecisionContext };
export function readinessSourceFingerprint(input: Pick<CurrentReadinessSnapshot,"planId"|"mesocycleId"|"microcycleNumber"|"sourceWorkoutIds"|"sourceSessionIds">): string { return [input.planId,input.mesocycleId,String(input.microcycleNumber),...([...input.sourceSessionIds].sort()),...([...input.sourceWorkoutIds].sort())].join("|"); }
export type ReadinessHydration = { status:"hydrated"; snapshot:CurrentReadinessSnapshot } | { status:"unsupported_schema" } | { status:"invalid_record"; issues:readonly string[] };
export function hydrateReadinessSnapshot(value:unknown):ReadinessHydration { const issues=validateReadinessSnapshot(value); if(issues.includes("unsupported_schema"))return{status:"unsupported_schema"}; return issues.length?{status:"invalid_record",issues}:{status:"hydrated",snapshot:copyReadinessSnapshot(value as CurrentReadinessSnapshot)}; }
export function validateReadinessSnapshot(value:unknown):string[]{if(!value||typeof value!=="object")return["malformed"];const v=value as Record<string,unknown>;if(v.schemaVersion!==CURRENT_READINESS_SCHEMA)return["unsupported_schema"];const arrays=["sourceWorkoutIds","sourceSessionIds","requiredRoles","completedRoles","unresolvedRoles","blockedRoles","approvedSuccessors"];const issues:string[]=[];for(const key of arrays)if(!Array.isArray(v[key])||!(v[key] as unknown[]).every((x)=>typeof x==="string"))issues.push(`invalid_${key}`);const completed=Array.isArray(v.completedRoles)?v.completedRoles:[],unresolved=Array.isArray(v.unresolvedRoles)?v.unresolvedRoles:[],blocked=Array.isArray(v.blockedRoles)?v.blockedRoles:[];for(const key of ["id","planId","mesocycleId","createdAt","sourceFingerprint"])if(typeof v[key]!=="string"||!v[key])issues.push(`invalid_${key}`);if(typeof v.microcycleNumber!=="number"||v.microcycleNumber<1)issues.push("invalid_microcycle");if(!["ready","in_progress","insufficient_evidence","insufficient_policy","blocked","disrupted","invalid"].includes(String(v.state)))issues.push("invalid_state");if(completed.some((r)=>unresolved.includes(r)||blocked.includes(r)))issues.push("role_conflict");return issues;}
export function copyReadinessSnapshot(snapshot:CurrentReadinessSnapshot):CurrentReadinessSnapshot{return{...snapshot,sourceWorkoutIds:[...snapshot.sourceWorkoutIds],sourceSessionIds:[...snapshot.sourceSessionIds],requiredRoles:[...snapshot.requiredRoles],completedRoles:[...snapshot.completedRoles],unresolvedRoles:[...snapshot.unresolvedRoles],blockedRoles:[...snapshot.blockedRoles],approvedSuccessors:[...snapshot.approvedSuccessors], ...(snapshot.decisionContext ? { decisionContext: { evaluatorInput: { ...snapshot.decisionContext.evaluatorInput, mesocycle: { ...snapshot.decisionContext.evaluatorInput.mesocycle, nextStates: [...snapshot.decisionContext.evaluatorInput.mesocycle.nextStates], successCriteria: [...snapshot.decisionContext.evaluatorInput.mesocycle.successCriteria] }, approvedSuccessors: [...snapshot.decisionContext.evaluatorInput.approvedSuccessors], approvedPrerequisites: [...snapshot.decisionContext.evaluatorInput.approvedPrerequisites] }, evidence: { ...snapshot.decisionContext.evidence } } } : {})};}
