export type CurrentProgrammeVersion = number;
export type CurrentProgrammePrescriptionSlot = Readonly<{ schemaVersion: "v1"; id: string; programmeId: string; programmeVersion: CurrentProgrammeVersion; sessionTemplateId: string; ordinal: string; targetDomain: "muscle" | "movement_pattern" | "exercise_slot"; targetId: string; purpose: string; recommendedMinSets: number; recommendedMaxSets: number; targetVersion: number; guidancePolicyVersion: string; selectionConstraints: readonly string[] }>;
export type CurrentProgrammeSessionTemplate = Readonly<{ schemaVersion: "v1"; id: string; programmeId: string; programmeVersion: CurrentProgrammeVersion; orderingKey: string; sessionRole: string; purpose: string; prescriptionSlots: readonly CurrentProgrammePrescriptionSlot[]; constructionPolicyVersion: string }>;
export type CurrentMesocycleProgrammeSpecification = Readonly<{ schemaVersion: "v1"; planId: string; mesocycleId: string; programmeId: string; version: CurrentProgrammeVersion; predecessorVersion?: CurrentProgrammeVersion; purposePolicyVersion: string; creationReason: "initial" | "approved_guidance_adjustment"; sourceAdjustmentIds: readonly string[]; sessionTemplates: readonly CurrentProgrammeSessionTemplate[] }>;
export type CurrentMicrocycleProgrammeReference = Readonly<{ schemaVersion: "v1"; planId: string; mesocycleId: string; microcycleNumber: number; programmeId: string; programmeVersion: CurrentProgrammeVersion; bindingLifecycle: "proposed" | "bound" | "construction_started" | "construction_complete"; policyVersion: string }>;
export type CurrentProgrammeLookup<T> = Readonly<{ status: "found"; value: T }> | Readonly<{ status: "not_found" | "ambiguous" | "parent_mismatch" | "version_mismatch" | "invalid_specification"; reason: string }>;
export type CurrentProgrammeHydration = Readonly<{ status: "hydrated_current_programme"; specification: CurrentMesocycleProgrammeSpecification }> | Readonly<{ status: "invalid_programme" | "unsupported_schema"; reason: string }>;

export function hydrateCurrentMesocycleProgrammeSpecification(value: unknown): CurrentProgrammeHydration { if (!value || typeof value !== "object") return { status: "invalid_programme", reason: "not_object" }; const specification = value as CurrentMesocycleProgrammeSpecification; if (specification.schemaVersion !== "v1") return { status: "unsupported_schema", reason: "unknown_schema" }; const reason = validate(specification); return reason ? { status: "invalid_programme", reason } : { status: "hydrated_current_programme", specification: copy(specification) }; }
export function findProgrammeSessionTemplate(specification: CurrentMesocycleProgrammeSpecification, id: string): CurrentProgrammeLookup<CurrentProgrammeSessionTemplate> { const matches = specification.sessionTemplates.filter((template) => template.id === id); return matches.length === 1 ? { status: "found", value: copyTemplate(matches[0]!) } : matches.length === 0 ? { status: "not_found", reason: "template_missing" } : { status: "ambiguous", reason: "duplicate_template_id" }; }
export function findProgrammePrescriptionSlot(specification: CurrentMesocycleProgrammeSpecification, templateId: string, slotId: string): CurrentProgrammeLookup<CurrentProgrammePrescriptionSlot> { const template = findProgrammeSessionTemplate(specification, templateId); if (template.status !== "found") return template; const matches = template.value.prescriptionSlots.filter((slot) => slot.id === slotId); return matches.length === 1 ? { status: "found", value: { ...matches[0]!, selectionConstraints: [...matches[0]!.selectionConstraints] } } : matches.length === 0 ? { status: "not_found", reason: "slot_missing" } : { status: "ambiguous", reason: "duplicate_slot_id" }; }
export function createNextCurrentProgrammeVersion(input: Readonly<{ existing: CurrentMesocycleProgrammeSpecification; expectedVersion: number; updates: readonly Readonly<{ templateId: string; slotId: string; recommendedMinSets: number; recommendedMaxSets: number }> []; nextVersion: number; sourceAdjustmentIds: readonly string[] }>): CurrentProgrammeLookup<CurrentMesocycleProgrammeSpecification> { if (input.existing.version !== input.expectedVersion) return { status: "version_mismatch", reason: "expected_version_mismatch" }; if (input.nextVersion !== input.existing.version + 1) return { status: "invalid_specification", reason: "next_version_not_monotonic" }; const keys = new Set<string>(); for (const update of input.updates) { const key = `${update.templateId}:${update.slotId}`; if (keys.has(key) || update.recommendedMinSets < 0 || update.recommendedMaxSets < update.recommendedMinSets) return { status: "invalid_specification", reason: "duplicate_or_invalid_update" }; keys.add(key); }
  let unmatched = 0; const sessionTemplates = input.existing.sessionTemplates.map((template) => ({ ...template, programmeVersion: input.nextVersion, prescriptionSlots: template.prescriptionSlots.map((slot) => { const update = input.updates.find((candidate) => candidate.templateId === template.id && candidate.slotId === slot.id); if (!update) return { ...slot, programmeVersion: input.nextVersion, selectionConstraints: [...slot.selectionConstraints] }; unmatched += 1; return { ...slot, programmeVersion: input.nextVersion, recommendedMinSets: update.recommendedMinSets, recommendedMaxSets: update.recommendedMaxSets, targetVersion: slot.targetVersion + 1, selectionConstraints: [...slot.selectionConstraints] }; }) }));
  if (unmatched !== input.updates.length) return { status: "not_found", reason: "update_slot_missing" }; const next = { ...input.existing, version: input.nextVersion, predecessorVersion: input.existing.version, creationReason: "approved_guidance_adjustment" as const, sourceAdjustmentIds: [...input.sourceAdjustmentIds].sort(), sessionTemplates }; const reason = validate(next); return reason ? { status: "invalid_specification", reason } : { status: "found", value: copy(next) }; }
export function validateMicrocycleProgrammeReference(reference: CurrentMicrocycleProgrammeReference): string | null { if (!reference.planId || !reference.mesocycleId || !reference.programmeId || !Number.isInteger(reference.microcycleNumber) || reference.microcycleNumber < 1 || !Number.isInteger(reference.programmeVersion) || reference.programmeVersion < 1) return "invalid_reference_identity"; if (reference.bindingLifecycle === "construction_started" || reference.bindingLifecycle === "construction_complete") return null; return null; }
function validate(specification: CurrentMesocycleProgrammeSpecification): string | null { if (!specification.planId || !specification.mesocycleId || !specification.programmeId || !Number.isInteger(specification.version) || specification.version < 1) return "invalid_programme_identity"; if (specification.predecessorVersion !== undefined && (specification.predecessorVersion < 1 || specification.predecessorVersion >= specification.version)) return "invalid_lineage"; const templateIds = new Set<string>(); const slotIds = new Set<string>(); for (const template of specification.sessionTemplates) { if (!template.id || template.programmeId !== specification.programmeId || template.programmeVersion !== specification.version || templateIds.has(template.id)) return "invalid_template_identity"; templateIds.add(template.id); for (const slot of template.prescriptionSlots) { if (!slot.id || slotIds.has(slot.id) || slot.programmeId !== specification.programmeId || slot.programmeVersion !== specification.version || slot.sessionTemplateId !== template.id || slot.recommendedMinSets < 0 || slot.recommendedMaxSets < slot.recommendedMinSets || !Number.isInteger(slot.targetVersion) || slot.targetVersion < 1) return "invalid_slot_identity"; slotIds.add(slot.id); } } return null; }
function copy(specification: CurrentMesocycleProgrammeSpecification): CurrentMesocycleProgrammeSpecification { return { ...specification, sourceAdjustmentIds: [...specification.sourceAdjustmentIds], sessionTemplates: specification.sessionTemplates.map(copyTemplate) }; }
function copyTemplate(template: CurrentProgrammeSessionTemplate): CurrentProgrammeSessionTemplate { return { ...template, prescriptionSlots: template.prescriptionSlots.map((slot) => ({ ...slot, selectionConstraints: [...slot.selectionConstraints] })) }; }
