import type { ExperienceLevel } from "@/domain/training/models";
import type { MacrocycleEngineId } from "@/domain/training/macrocycle-engine";

export type MesocycleId =
  | "hypertrophy_calibration" | "hypertrophy_base" | "hypertrophy_volume" | "hypertrophy_specialisation" | "hypertrophy_consolidation" | "hypertrophy_transition"
  | "powerbuilding_foundation" | "powerbuilding_hypertrophy" | "powerbuilding_strength" | "powerbuilding_intensification" | "powerbuilding_realisation" | "powerbuilding_transition"
  | "strength_general" | "strength_accumulation" | "strength_specific" | "strength_intensification" | "strength_taper" | "strength_transition"
  | "athletic_general" | "athletic_force" | "athletic_power" | "athletic_transition";

export interface MesocycleSpec {
  id: MesocycleId; engine: MacrocycleEngineId; adaptation: string; eligibility: ExperienceLevel[];
  minimumWeeks: number; defaultWeeks: number; maximumWeeks: number; primaryStimulus: string; maintenanceStimuli: string[];
  successCriteria: string[]; exitCriteria: string[]; failureRoute: string; nextStates: MesocycleId[];
}

const spec = (value: MesocycleSpec) => value;
export const mesocycleLibrary: readonly MesocycleSpec[] = [
  spec({ id:"hypertrophy_calibration",engine:"hypertrophy",adaptation:"Establish reproducible exercise, load and recovery baselines",eligibility:["beginner","intermediate","advanced"],minimumWeeks:1,defaultWeeks:2,maximumWeeks:3,primaryStimulus:"Conservative stable training",maintenanceStimuli:["Technique","joint tolerance"],successCriteria:["Credible baselines"],exitCriteria:["Main movement and muscle data exists"],failureRoute:"Replace unsuitable exercise or reduce complexity",nextStates:["hypertrophy_base"] }),
  spec({ id:"hypertrophy_base",engine:"hypertrophy",adaptation:"Build recoverable muscle stimulus",eligibility:["beginner","intermediate","advanced"],minimumWeeks:3,defaultWeeks:6,maximumWeeks:10,primaryStimulus:"Stable progressive muscle-specific work",maintenanceStimuli:["Strength","joint tolerance"],successCriteria:["Priority-muscle rep/load progression"],exitCriteria:["Broad slowing, fatigue or duration limit"],failureRoute:"Consolidate or adjust local muscle dose",nextStates:["hypertrophy_volume","hypertrophy_specialisation","hypertrophy_consolidation"] }),
  spec({ id:"hypertrophy_volume",engine:"hypertrophy",adaptation:"Find productive additional volume for selected muscles",eligibility:["intermediate","advanced"],minimumWeeks:3,defaultWeeks:4,maximumWeeks:8,primaryStimulus:"Small local volume increases",maintenanceStimuli:["Other muscles","recovery"],successCriteria:["Improved target response"],exitCriteria:["Dose identified or recovery ceiling"],failureRoute:"Return to prior dose",nextStates:["hypertrophy_consolidation"] }),
  spec({ id:"hypertrophy_specialisation",engine:"hypertrophy",adaptation:"Prioritise one to three muscles",eligibility:["intermediate","advanced"],minimumWeeks:4,defaultWeeks:6,maximumWeeks:10,primaryStimulus:"Priority-muscle volume and placement",maintenanceStimuli:["Non-priority muscle"],successCriteria:["Priority development without unacceptable regression"],exitCriteria:["Target reached, stall or fatigue"],failureRoute:"Reassess exercise fit and dose",nextStates:["hypertrophy_consolidation"] }),
  spec({ id:"hypertrophy_consolidation",engine:"hypertrophy",adaptation:"Dissipate fatigue while retaining muscle",eligibility:["beginner","intermediate","advanced"],minimumWeeks:2,defaultWeeks:3,maximumWeeks:5,primaryStimulus:"Maintenance volume and familiar work",maintenanceStimuli:["Strength"],successCriteria:["Performance rebound"],exitCriteria:["Recovery normalises"],failureRoute:"Transition",nextStates:["hypertrophy_base","hypertrophy_transition"] }),
  spec({ id:"hypertrophy_transition",engine:"hypertrophy",adaptation:"Restore readiness",eligibility:["beginner","intermediate","advanced"],minimumWeeks:1,defaultWeeks:1,maximumWeeks:2,primaryStimulus:"Low structured volume",maintenanceStimuli:[],successCriteria:["Readiness restored"],exitCriteria:["Next goal selected"],failureRoute:"Continue low stress briefly",nextStates:["hypertrophy_base"] }),
  spec({ id:"powerbuilding_foundation",engine:"powerbuilding",adaptation:"Establish repeatable squat, bench and deadlift",eligibility:["beginner","intermediate","advanced"],minimumWeeks:2,defaultWeeks:3,maximumWeeks:8,primaryStimulus:"Submaximal main-lift practice",maintenanceStimuli:["General hypertrophy"],successCriteria:["Stable technique"],exitCriteria:["Progressive loading is stable"],failureRoute:"Reduce complexity",nextStates:["powerbuilding_hypertrophy"] }),
  spec({ id:"powerbuilding_hypertrophy",engine:"powerbuilding",adaptation:"Add muscle while retaining S/B/D",eligibility:["beginner","intermediate","advanced"],minimumWeeks:4,defaultWeeks:6,maximumWeeks:10,primaryStimulus:"High assistance allocation with regular main lifts",maintenanceStimuli:["S/B/D skill"],successCriteria:["Assistance progress and maintained lifts"],exitCriteria:["Development achieved or fatigue"],failureRoute:"Consolidate",nextStates:["powerbuilding_strength"] }),
  spec({ id:"powerbuilding_strength",engine:"powerbuilding",adaptation:"Convert capacity into stronger main lifts",eligibility:["beginner","intermediate","advanced"],minimumWeeks:4,defaultWeeks:5,maximumWeeks:8,primaryStimulus:"Submaximal lift-specific volume",maintenanceStimuli:["Muscle"],successCriteria:["Improving estimated strength"],exitCriteria:["Testing, fatigue or maximum"],failureRoute:"Return to hypertrophy bias",nextStates:["powerbuilding_intensification","powerbuilding_hypertrophy"] }),
  spec({ id:"powerbuilding_intensification",engine:"powerbuilding",adaptation:"Heavy main-lift expression",eligibility:["intermediate","advanced"],minimumWeeks:3,defaultWeeks:4,maximumWeeks:6,primaryStimulus:"High-specificity heavy work",maintenanceStimuli:["Low-cost muscle work"],successCriteria:["Stable heavy performance"],exitCriteria:["Ready to test or fatigue"],failureRoute:"Consolidate",nextStates:["powerbuilding_realisation","powerbuilding_transition"] }),
  spec({ id:"powerbuilding_realisation",engine:"powerbuilding",adaptation:"Express strength",eligibility:["intermediate","advanced"],minimumWeeks:1,defaultWeeks:2,maximumWeeks:2,primaryStimulus:"Low-volume familiar main lifts",maintenanceStimuli:[],successCriteria:["Best available test performance"],exitCriteria:["Test complete"],failureRoute:"Transition",nextStates:["powerbuilding_transition"] }),
  spec({ id:"powerbuilding_transition",engine:"powerbuilding",adaptation:"Recover after expression",eligibility:["beginner","intermediate","advanced"],minimumWeeks:1,defaultWeeks:1,maximumWeeks:2,primaryStimulus:"Low fatigue",maintenanceStimuli:[],successCriteria:["Readiness restored"],exitCriteria:["Next cycle chosen"],failureRoute:"Extend briefly",nextStates:["powerbuilding_hypertrophy"] }),
  spec({ id:"strength_general",engine:"strength",adaptation:"Build work capacity and movement tolerance",eligibility:["beginner","intermediate","advanced"],minimumWeeks:3,defaultWeeks:4,maximumWeeks:6,primaryStimulus:"General strength and muscle",maintenanceStimuli:["Competition lift skill"],successCriteria:["Prepared for lift-specific work"],exitCriteria:["Capacity established"],failureRoute:"Reduce complexity",nextStates:["strength_accumulation"] }),
  spec({ id:"strength_accumulation",engine:"strength",adaptation:"Build maximal-force capacity",eligibility:["beginner","intermediate","advanced"],minimumWeeks:4,defaultWeeks:6,maximumWeeks:10,primaryStimulus:"Lift-specific back-off volume",maintenanceStimuli:["Assistance"],successCriteria:["Repeatable strength improvement"],exitCriteria:["Specificity required or fatigue"],failureRoute:"Reassess dose",nextStates:["strength_specific"] }),
  spec({ id:"strength_specific",engine:"strength",adaptation:"Transfer strength to target lifts",eligibility:["intermediate","advanced"],minimumWeeks:3,defaultWeeks:4,maximumWeeks:7,primaryStimulus:"High-specificity lift work",maintenanceStimuli:["Limitations work"],successCriteria:["Specific heavy performance improves"],exitCriteria:["Peak or fatigue"],failureRoute:"Return to accumulation",nextStates:["strength_intensification","strength_accumulation"] }),
  spec({ id:"strength_intensification",engine:"strength",adaptation:"Heavy specific practice",eligibility:["intermediate","advanced"],minimumWeeks:2,defaultWeeks:3,maximumWeeks:5,primaryStimulus:"High intensity declining volume",maintenanceStimuli:["Technique"],successCriteria:["Stable heavy work"],exitCriteria:["Taper or regression"],failureRoute:"Taper",nextStates:["strength_taper"] }),
  spec({ id:"strength_taper",engine:"strength",adaptation:"Express strength with reduced fatigue",eligibility:["intermediate","advanced"],minimumWeeks:1,defaultWeeks:2,maximumWeeks:2,primaryStimulus:"Reduced volume and retained intensity",maintenanceStimuli:[],successCriteria:["Best available strength"],exitCriteria:["Test complete"],failureRoute:"Transition",nextStates:["strength_transition"] }),
  spec({ id:"strength_transition",engine:"strength",adaptation:"Physical and psychological recovery",eligibility:["beginner","intermediate","advanced"],minimumWeeks:1,defaultWeeks:2,maximumWeeks:3,primaryStimulus:"Low structured loading",maintenanceStimuli:[],successCriteria:["Readiness restored"],exitCriteria:["Next goal selected"],failureRoute:"Extend briefly",nextStates:["strength_general"] }),
  spec({ id:"athletic_general",engine:"athletic_performance",adaptation:"General athletic preparation",eligibility:["beginner","intermediate","advanced"],minimumWeeks:4,defaultWeeks:6,maximumWeeks:10,primaryStimulus:"General strength, capacity and low-dose power",maintenanceStimuli:["Movement quality"],successCriteria:["Improved tolerance and capacity"],exitCriteria:["Ready for force or power work"],failureRoute:"Remain general",nextStates:["athletic_force","athletic_power"] }),
  spec({ id:"athletic_force",engine:"athletic_performance",adaptation:"General force development",eligibility:["intermediate","advanced"],minimumWeeks:4,defaultWeeks:6,maximumWeeks:10,primaryStimulus:"Technically controlled strength",maintenanceStimuli:["Power quality"],successCriteria:["Strength improves without output loss"],exitCriteria:["Returns decline or power priority"],failureRoute:"Return to general preparation",nextStates:["athletic_power","athletic_transition"] }),
  spec({ id:"athletic_power",engine:"athletic_performance",adaptation:"General power and speed development",eligibility:["intermediate","advanced"],minimumWeeks:3,defaultWeeks:4,maximumWeeks:8,primaryStimulus:"Low-rep maximal-intent work",maintenanceStimuli:["Strength"],successCriteria:["Output improves without availability loss"],exitCriteria:["Stall or fatigue"],failureRoute:"Return to force/general",nextStates:["athletic_transition","athletic_force"] }),
  spec({ id:"athletic_transition",engine:"athletic_performance",adaptation:"Restore general athletic readiness",eligibility:["beginner","intermediate","advanced"],minimumWeeks:1,defaultWeeks:2,maximumWeeks:4,primaryStimulus:"Reduced formal stress",maintenanceStimuli:[],successCriteria:["Readiness restored"],exitCriteria:["Next block selected"],failureRoute:"Extend briefly",nextStates:["athletic_general"] }),
];

export function selectMesocycles(engine: MacrocycleEngineId, experience: ExperienceLevel): MesocycleSpec[] {
  const eligible = mesocycleLibrary.filter((item) => item.engine === engine && item.eligibility.includes(experience));
  if (experience === "beginner") return eligible.filter((item) => !item.id.includes("volume") && !item.id.includes("specialisation") && !item.id.includes("intensification") && !item.id.includes("realisation") && !item.id.includes("taper"));
  return eligible;
}

export function mesocycleById(id: MesocycleId): MesocycleSpec | undefined {
  return mesocycleLibrary.find((item) => item.id === id);
}
