export interface MovementGuide {
  setup: string[];
  steps: string[];
  cues: string[];
  commonMistakes: string[];
  regressions?: string[];
  progressions?: string[];
  avoid?: string[];
}

const commonControlledAvoid = ["Stop if it causes pain.", "Use a comfortable range and keep the work controlled."];

const pulloverGuide: MovementGuide = {
  setup: ["Lie on a bench or floor with a light weight or band.", "Keep ribs down and arms slightly bent."],
  steps: ["Reach the arms back only as far as you can control.", "Pause briefly.", "Pull back to the start without flaring the ribs."],
  cues: ["Move slowly.", "Feel the shoulders and lats open.", "Keep the range easy."],
  commonMistakes: ["Arching the lower back.", "Using a heavy weight.", "Letting the elbows bend into a press."],
  regressions: ["Use a band.", "Use a shorter range."],
  progressions: ["Use a slightly longer controlled range.", "Use a small weight only if control stays clean."],
  avoid: commonControlledAvoid,
};

const backExtensionGuide: MovementGuide = {
  setup: ["Set the pad so your hips can fold freely.", "Brace lightly and keep the ribs stacked over the pelvis."],
  steps: ["Hinge down through the hips.", "Drive the hips into the pad to return.", "Stop when your body is roughly straight."],
  cues: ["Move through the hips.", "Keep the neck neutral.", "Use smooth reps."],
  commonMistakes: ["Overextending at the top.", "Rushing the bottom position.", "Turning it into a low-back-only movement."],
  regressions: ["Use bodyweight only.", "Shorten the range."],
  progressions: ["Add reps first.", "Hold a light load only when reps stay repeatable."],
  avoid: commonControlledAvoid,
};

const reverseHyperGuide: MovementGuide = {
  setup: ["Lie on the reverse hyper bench or stable surface.", "Hold the handles and let the legs hang under control."],
  steps: ["Lift the legs by squeezing the glutes.", "Pause briefly near the top.", "Lower under control without swinging hard."],
  cues: ["Control the swing.", "Keep the trunk quiet.", "Use hips, not momentum."],
  commonMistakes: ["Throwing the legs up.", "Letting the pelvis bounce.", "Using a range you cannot control."],
  regressions: ["Use bodyweight.", "Use one short controlled set."],
  progressions: ["Add reps first.", "Add a small load only when the motion stays controlled."],
  avoid: commonControlledAvoid,
};

const guides: Record<string, MovementGuide> = {
  "Cat-Camel": {
    setup: ["Start on hands and knees.", "Place hands under shoulders and knees under hips."],
    steps: ["Slowly round the back.", "Slowly extend to a comfortable arch.", "Move back and forth without forcing range."],
    cues: ["Move gently.", "Breathe normally.", "Treat this as motion, not stretching hard."],
    commonMistakes: ["Forcing end range.", "Moving too fast.", "Holding your breath."],
    regressions: ["Use a smaller range.", "Do fewer reps."],
    progressions: ["Make the movement smoother before adding reps."],
    avoid: commonControlledAvoid,
  },
  "McGill Curl-Up": {
    setup: ["Lie on your back with one knee bent and one leg straight.", "Place hands under the low back to keep a neutral position."],
    steps: ["Brace gently.", "Lift the head and shoulders slightly.", "Hold briefly, then lower with control."],
    cues: ["Keep the motion small.", "Do not crunch hard.", "Breathe behind the brace."],
    commonMistakes: ["Pulling on the neck.", "Flattening the low back aggressively.", "Chasing a high sit-up."],
    regressions: ["Use shorter holds.", "Reduce the lift height."],
    progressions: ["Add hold time before adding reps."],
    avoid: commonControlledAvoid,
  },
  "McGill Curl Up": {
    setup: ["Lie on your back with one knee bent and one leg straight.", "Place hands under the low back to keep a neutral position."],
    steps: ["Brace gently.", "Lift the head and shoulders slightly.", "Hold briefly, then lower with control."],
    cues: ["Keep the motion small.", "Do not crunch hard.", "Breathe behind the brace."],
    commonMistakes: ["Pulling on the neck.", "Flattening the low back aggressively.", "Chasing a high sit-up."],
    regressions: ["Use shorter holds.", "Reduce the lift height."],
    progressions: ["Add hold time before adding reps."],
    avoid: commonControlledAvoid,
  },
  "Side Plank": {
    setup: ["Start on your side with elbow under shoulder.", "Stack the feet or stagger them for balance."],
    steps: ["Brace and lift the hips.", "Hold a straight line from head to feet.", "Lower before form shakes apart."],
    cues: ["Push the floor away.", "Keep ribs down.", "Stay tall through the head."],
    commonMistakes: ["Letting hips sag.", "Shrugging into the neck.", "Holding past clean form."],
    regressions: ["Bend the knees.", "Use shorter holds."],
    progressions: ["Use longer clean holds.", "Use a full side plank if starting from knees."],
    avoid: commonControlledAvoid,
  },
  "Dead Bug": {
    setup: ["Lie on your back with arms up and knees bent.", "Keep ribs down and low back controlled."],
    steps: ["Brace gently.", "Reach one arm and the opposite leg away.", "Return slowly and switch sides."],
    cues: ["Move slowly.", "Keep ribs stacked.", "Stop before the back arches."],
    commonMistakes: ["Rushing reps.", "Letting the ribs flare.", "Reaching farther than you can control."],
    regressions: ["Move only the legs.", "Use a shorter reach."],
    progressions: ["Use a longer controlled reach.", "Pause briefly at full reach."],
    avoid: commonControlledAvoid,
  },
  "Front Plank": {
    setup: ["Set elbows under shoulders.", "Step feet back and create a straight line."],
    steps: ["Brace gently.", "Hold without sagging or piking.", "Stop before position shakes apart."],
    cues: ["Ribs down.", "Squeeze glutes lightly.", "Breathe behind the brace."],
    commonMistakes: ["Letting hips sag.", "Holding too long.", "Shrugging into the neck."],
    regressions: ["Use knees down.", "Use a shorter hold."],
    progressions: ["Use longer clean holds.", "Move from knees to full plank."],
    avoid: commonControlledAvoid,
  },
  "Pallof Press": {
    setup: ["Stand side-on to a light cable or band.", "Hold the handle at the chest with feet steady."],
    steps: ["Brace gently.", "Press the hands straight out.", "Pause, then return without rotating."],
    cues: ["Stay tall.", "Resist rotation.", "Use light tension."],
    commonMistakes: ["Using too much resistance.", "Twisting through the torso.", "Rushing the pause."],
    regressions: ["Use a lighter band.", "Stand closer to the anchor."],
    progressions: ["Add reps first.", "Step slightly farther from the anchor."],
    avoid: commonControlledAvoid,
  },
  "Bird Dog": {
    setup: ["Start on hands and knees.", "Keep ribs down and spine neutral."],
    steps: ["Reach opposite arm and leg away.", "Pause briefly.", "Return slowly and switch sides."],
    cues: ["Move slowly.", "Do not twist.", "Keep hips level."],
    commonMistakes: ["Arching the lower back.", "Rushing reps.", "Lifting the leg too high."],
    regressions: ["Move only the legs.", "Move only the arms."],
    progressions: ["Pause longer.", "Use a slightly longer reach without losing position."],
    avoid: commonControlledAvoid,
  },
  "Hip Hinge Drill": {
    setup: ["Stand tall with soft knees.", "Use a dowel or hands on hips if helpful."],
    steps: ["Push hips back.", "Keep the torso long.", "Stand by driving the hips through."],
    cues: ["Hips back first.", "Shins mostly quiet.", "Brace before each rep."],
    commonMistakes: ["Squatting instead of hinging.", "Rounding hard.", "Reaching with the head."],
    regressions: ["Hinge to a wall.", "Use a shorter range."],
    progressions: ["Hold a light weight close to the body.", "Use a slower tempo."],
    avoid: commonControlledAvoid,
  },
  "Glute Bridge": {
    setup: ["Lie on your back with knees bent.", "Place feet flat and hip-width."],
    steps: ["Brace gently.", "Drive through the feet and lift the hips.", "Pause, then lower under control."],
    cues: ["Finish through the hips.", "Keep ribs down.", "Feel glutes do the work."],
    commonMistakes: ["Overarching the back.", "Pushing through the toes only.", "Rushing the top."],
    regressions: ["Use a smaller range.", "Pause less."],
    progressions: ["Add a longer pause.", "Use single-leg only when control is solid."],
    avoid: commonControlledAvoid,
  },
  "Back Extension Hold": {
    setup: ["Set up on a back extension bench.", "Reach a straight-body position without overextending."],
    steps: ["Brace and hold the top position.", "Breathe steadily.", "Step down before control fades."],
    cues: ["Own the top.", "Stay long.", "Keep effort moderate."],
    commonMistakes: ["Leaning past straight.", "Holding until form breaks.", "Shrugging the neck."],
    regressions: ["Shorten the hold.", "Use hands across the chest."],
    progressions: ["Add time before adding load."],
    avoid: commonControlledAvoid,
  },
  "Side Bend": {
    setup: ["Stand tall with a light dumbbell or cable in one hand.", "Keep feet steady."],
    steps: ["Bend sideways through a controlled range.", "Return to tall posture.", "Repeat without twisting."],
    cues: ["Move like a hinge to the side.", "Keep the range smooth.", "Control the return."],
    commonMistakes: ["Twisting.", "Using too much load.", "Bouncing out of the bottom."],
    regressions: ["Use bodyweight.", "Use a shorter range."],
    progressions: ["Add reps first.", "Add load gradually."],
    avoid: commonControlledAvoid,
  },
  "Reverse Hyper": reverseHyperGuide,
  "Single-Leg Reverse Hyper": {
    ...reverseHyperGuide,
    setup: ["Lie on the reverse hyper bench or stable surface.", "Work one leg at a time while keeping the pelvis steady."],
    cues: ["Keep hips level.", "Use a shorter range than the two-leg version.", "Control each rep."],
  },
  "Back Extension": backExtensionGuide,
  "45 Degree Back Extension": backExtensionGuide,
  "Horizontal Back Extension": backExtensionGuide,
  "Weighted Back Extension": {
    ...backExtensionGuide,
    setup: ["Set up on the back extension bench.", "Hold a light load close to the chest."],
    cues: ["Reps first, load second.", "Keep the load close.", "Stop at a straight-body top position."],
    progressions: ["Add reps first.", "Increase load only when the same range stays clean."],
  },
  "Iso Hold Back Extension": {
    ...backExtensionGuide,
    steps: ["Reach a straight-body position.", "Hold with steady breathing.", "Step down before position breaks."],
  },
  "Single-Leg Back Extension": {
    ...backExtensionGuide,
    setup: ["Set up on the back extension bench.", "Bias one leg while keeping the pelvis level."],
    cues: ["Keep hips square.", "Use clean reps only.", "Reduce range before losing control."],
  },
  "Pull Through": {
    setup: ["Stand facing away from a low cable.", "Hold the rope between the legs and step forward."],
    steps: ["Hinge the hips back.", "Keep arms long.", "Drive hips through to stand tall."],
    cues: ["Hips back.", "Cable pulls you into the hinge.", "Finish with glutes, not a back lean."],
    commonMistakes: ["Squatting the movement.", "Overextending at the top.", "Letting the cable yank you back."],
    regressions: ["Use a lighter stack.", "Shorten the hinge."],
    progressions: ["Add reps first.", "Add load only when position stays repeatable."],
    avoid: commonControlledAvoid,
  },
  "Hip Thrust": {
    setup: ["Set upper back on a bench.", "Place feet where shins are roughly vertical at the top."],
    steps: ["Brace and drive hips up.", "Pause at the top.", "Lower under control."],
    cues: ["Chin tucked.", "Ribs down.", "Finish through the hips."],
    commonMistakes: ["Overarching at the top.", "Feet too far away.", "Bouncing reps."],
    regressions: ["Use a glute bridge.", "Use bodyweight."],
    progressions: ["Add reps first.", "Add load gradually."],
    avoid: commonControlledAvoid,
  },
  "Suitcase Carry": {
    setup: ["Hold one weight at your side.", "Stand tall with shoulders level."],
    steps: ["Walk with steady steps.", "Keep the torso upright.", "Switch sides after the planned distance."],
    cues: ["Walk tall.", "Do not lean into the weight.", "Breathe behind the brace."],
    commonMistakes: ["Rushing.", "Leaning sideways.", "Choosing a load that changes posture."],
    regressions: ["Use a lighter weight.", "Use a shorter distance."],
    progressions: ["Add distance before load.", "Add load only when posture stays clean."],
    avoid: commonControlledAvoid,
  },
  "Farmer Carry": {
    setup: ["Hold matched weights at your sides.", "Stand tall before walking."],
    steps: ["Walk with controlled steps.", "Keep shoulders down and ribs stacked.", "Set the weights down with control."],
    cues: ["Brace and breathe.", "Walk tall.", "Use quiet steps."],
    commonMistakes: ["Rushing.", "Shrugging hard.", "Letting posture collapse."],
    regressions: ["Use lighter weights.", "Shorten the distance."],
    progressions: ["Add distance before load.", "Add load when posture stays consistent."],
    avoid: commonControlledAvoid,
  },
  "Cuban Press": {
    setup: ["Use very light dumbbells or no load.", "Stand tall with elbows lifted comfortably."],
    steps: ["Rotate the forearms up under control.", "Press lightly if comfortable.", "Return through the same path."],
    cues: ["Light and smooth.", "Own the rotation.", "Keep shoulders away from ears."],
    commonMistakes: ["Going too heavy.", "Forcing range.", "Rushing the rotation."],
    regressions: ["Use no load.", "Do only the rotation portion."],
    progressions: ["Add reps before load.", "Use slightly more range only if it stays easy."],
    avoid: commonControlledAvoid,
  },
  "External Rotation": {
    setup: ["Use a band or cable set light.", "Keep elbow close to the side or supported."],
    steps: ["Rotate the hand away from the body.", "Pause briefly.", "Return slowly."],
    cues: ["Small controlled range.", "Elbow stays quiet.", "Shoulder stays down."],
    commonMistakes: ["Twisting the torso.", "Letting the elbow drift.", "Using too much resistance."],
    regressions: ["Use a lighter band.", "Shorten the range."],
    progressions: ["Add reps before resistance."],
    avoid: commonControlledAvoid,
  },
  "Trap 3 Raise": {
    setup: ["Lie chest-supported or hinge with both hands free.", "Thumbs point up."],
    steps: ["Raise both hands on a diagonal.", "Pause briefly.", "Lower slowly."],
    cues: ["Reach long with both hands.", "Keep the shoulder blades controlled.", "Use light load."],
    commonMistakes: ["Shrugging.", "Swinging.", "Turning it into a heavy raise."],
    regressions: ["Use no load.", "Use a smaller range."],
    progressions: ["Add reps first.", "Use a very small load increase."],
    avoid: commonControlledAvoid,
  },
  "Band Pull Apart": {
    setup: ["Hold a light band at chest height.", "Keep ribs down and arms long but not locked hard."],
    steps: ["Pull the band apart under control.", "Pause briefly with shoulder blades set.", "Return slowly."],
    cues: ["Light tension.", "Shoulders down.", "Smooth reps."],
    commonMistakes: ["Shrugging.", "Arching the back.", "Using a band that is too heavy."],
    regressions: ["Use a lighter band.", "Use a smaller range."],
    progressions: ["Add reps first.", "Use slightly more tension only if control stays clean."],
    avoid: commonControlledAvoid,
  },
  "Band Pull-Apart": {
    setup: ["Hold a light band at chest height.", "Keep ribs down and arms long but not locked hard."],
    steps: ["Pull the band apart under control.", "Pause briefly with shoulder blades set.", "Return slowly."],
    cues: ["Light tension.", "Shoulders down.", "Smooth reps."],
    commonMistakes: ["Shrugging.", "Arching the back.", "Using a band that is too heavy."],
    regressions: ["Use a lighter band.", "Use a smaller range."],
    progressions: ["Add reps first.", "Use slightly more tension only if control stays clean."],
    avoid: commonControlledAvoid,
  },
  "Band Face Pull": {
    setup: ["Anchor a light band around face height.", "Hold the band with arms extended."],
    steps: ["Pull toward the face with elbows high but comfortable.", "Pause briefly.", "Return with control."],
    cues: ["Light and smooth.", "Shoulders away from ears.", "Feel upper back control."],
    commonMistakes: ["Going too heavy.", "Yanking the band.", "Flaring ribs to finish the pull."],
    regressions: ["Use a lighter band.", "Use a shorter pull."],
    progressions: ["Add reps before tension."],
    avoid: commonControlledAvoid,
  },
  "Face Pull": {
    setup: ["Use a light cable or band around face height.", "Stand tall with ribs down."],
    steps: ["Pull toward the face.", "Pause with shoulder blades controlled.", "Return slowly."],
    cues: ["Light load.", "Elbows comfortable.", "Own the shoulder position."],
    commonMistakes: ["Turning it into a heavy row.", "Shrugging.", "Rushing reps."],
    regressions: ["Use less resistance.", "Use a smaller range."],
    progressions: ["Add reps first.", "Increase tension only if position stays clean."],
    avoid: commonControlledAvoid,
  },
  "Push Up": {
    setup: ["Set hands under shoulders or slightly wider.", "Use floor, bench, or rack height that feels easy."],
    steps: ["Brace lightly.", "Lower under control.", "Press up smoothly without grinding."],
    cues: ["Easy reps.", "Straight line.", "Stop well before fatigue."],
    commonMistakes: ["Going near failure.", "Sagging hips.", "Flaring elbows aggressively."],
    regressions: ["Use an incline.", "Use fewer reps."],
    progressions: ["Use the floor only if it stays easy."],
    avoid: commonControlledAvoid,
  },
  "Push-Up": {
    setup: ["Set hands under shoulders or slightly wider.", "Use floor, bench, or rack height that feels easy."],
    steps: ["Brace lightly.", "Lower under control.", "Press up smoothly without grinding."],
    cues: ["Easy reps.", "Straight line.", "Stop well before fatigue."],
    commonMistakes: ["Going near failure.", "Sagging hips.", "Flaring elbows aggressively."],
    regressions: ["Use an incline.", "Use fewer reps."],
    progressions: ["Use the floor only if it stays easy."],
    avoid: commonControlledAvoid,
  },
  "Scap Push Up": {
    setup: ["Set a push-up position from floor, bench, or rack.", "Keep elbows mostly straight."],
    steps: ["Let shoulder blades move together slightly.", "Push the floor away to spread them.", "Repeat slowly."],
    cues: ["Move shoulder blades, not elbows.", "Keep ribs down.", "Use easy reps."],
    commonMistakes: ["Bending into a push-up.", "Sagging the torso.", "Rushing reps."],
    regressions: ["Use an incline.", "Use fewer reps."],
    progressions: ["Use a lower incline only if control stays clean."],
    avoid: commonControlledAvoid,
  },
  "Wall Slide": {
    setup: ["Stand with back near a wall or use a comfortable unsupported stance.", "Keep ribs down."],
    steps: ["Slide or reach arms upward.", "Pause where control stays clean.", "Return slowly."],
    cues: ["Reach up, not back.", "Keep neck relaxed.", "Use a comfortable range."],
    commonMistakes: ["Forcing overhead range.", "Arching the back.", "Shrugging hard."],
    regressions: ["Use a shorter range.", "Move away from the wall."],
    progressions: ["Use a slightly longer controlled range."],
    avoid: commonControlledAvoid,
  },
  Pullover: pulloverGuide,
  "Light Pullover": pulloverGuide,
  "Dumbbell Pullover": pulloverGuide,
  "Deep Squat Hold": {
    setup: ["Stand with your normal squat stance.", "Hold a support if needed."],
    steps: ["Sit into a comfortable squat.", "Breathe and settle.", "Stand up with control."],
    cues: ["Keep feet grounded.", "Use only a range you can own.", "Stay relaxed but controlled."],
    commonMistakes: ["Forcing depth.", "Collapsing the knees inward.", "Holding your breath hard."],
    regressions: ["Hold a rack or post.", "Use a higher squat position."],
    progressions: ["Use longer holds.", "Use a light counterbalance."],
    avoid: commonControlledAvoid,
  },
  "Goblet Squat": {
    setup: ["Hold a light dumbbell or kettlebell at the chest.", "Stand in a comfortable squat stance."],
    steps: ["Sit into a controlled squat.", "Pause briefly where position feels solid.", "Stand smoothly."],
    cues: ["Easy load.", "Feet grounded.", "Own the bottom."],
    commonMistakes: ["Going too heavy.", "Bouncing.", "Letting knees collapse inward."],
    regressions: ["Use bodyweight.", "Hold a rack for support."],
    progressions: ["Add reps first.", "Use a slightly deeper controlled range."],
    avoid: commonControlledAvoid,
  },
  "Single Leg Glute Bridge": {
    setup: ["Lie on your back with one foot planted.", "Keep ribs down and hips level."],
    steps: ["Brace gently.", "Drive through the planted foot and lift hips.", "Lower with control before switching sides."],
    cues: ["Hips level.", "Glute drives the rep.", "Keep range easy."],
    commonMistakes: ["Twisting the pelvis.", "Overarching at the top.", "Rushing reps."],
    regressions: ["Use a two-leg glute bridge.", "Use fewer reps."],
    progressions: ["Add a brief pause.", "Add reps before load."],
    avoid: commonControlledAvoid,
  },
  "Ankle Floss": {
    setup: ["Place one foot forward near a wall or rack.", "Keep the heel down."],
    steps: ["Drive the knee forward over the toes.", "Return slowly.", "Repeat through a comfortable range."],
    cues: ["Heel stays heavy.", "Move smoothly.", "Keep the foot tripod."],
    commonMistakes: ["Letting heel lift early.", "Forcing range.", "Collapsing the arch."],
    regressions: ["Use a smaller range.", "Hold support."],
    progressions: ["Add a pause at end range.", "Use a light band only if it feels controlled."],
    avoid: commonControlledAvoid,
  },
  "Hip Flexor Kick Out": {
    setup: ["Stand tall and hold a rack or bench for balance if needed.", "Brace lightly and keep your pelvis level."],
    steps: ["Lift one knee toward hip height.", "Extend the lower leg forward into a controlled kick.", "Return under control and repeat.", "Alternate legs if prescribed."],
    cues: ["Stay tall.", "Avoid leaning backwards.", "Move slowly and under control.", "Feel the front of the hip working.", "Keep the core lightly braced."],
    commonMistakes: ["Leaning backwards.", "Letting the pelvis tilt or twist.", "Rushing the kick out."],
    regressions: ["Use a smaller kick.", "Hold rack or bench support."],
    progressions: ["Add a brief pause.", "Move more slowly."],
    avoid: commonControlledAvoid,
  },
  "Loaded Butterfly": {
    setup: ["Sit with soles of feet together.", "Hold a light load only if it helps you settle."],
    steps: ["Let knees open to a comfortable range.", "Breathe steadily.", "Come out slowly."],
    cues: ["Relax into control.", "Do not force the knees down.", "Keep the torso tall."],
    commonMistakes: ["Pushing aggressively on the knees.", "Using too much load.", "Rounding hard."],
    regressions: ["Use no load.", "Sit higher on a pad."],
    progressions: ["Add time before load.", "Use a slightly lower position if comfortable."],
    avoid: commonControlledAvoid,
  },
  "Couch Stretch": {
    setup: ["Place one knee near a wall or bench with the shin supported.", "Bring the other foot forward."],
    steps: ["Squeeze the back-leg glute lightly.", "Bring ribs down.", "Hold a comfortable position."],
    cues: ["Tall posture.", "Glute on.", "Breathe normally."],
    commonMistakes: ["Arching the low back.", "Forcing the knee angle.", "Holding too intensely."],
    regressions: ["Move the knee farther from the wall.", "Use a shorter hold."],
    progressions: ["Move closer only if position stays calm.", "Add gentle reaches."],
    avoid: commonControlledAvoid,
  },
  "Outer Hip Circuit": {
    setup: ["Use a mini-band if appropriate.", "Keep the pelvis level."],
    steps: ["Perform controlled side steps or abduction reps.", "Pause briefly at the end range.", "Return without losing tension."],
    cues: ["Control the pelvis.", "Move from the hip.", "Keep reps smooth."],
    commonMistakes: ["Rocking the torso.", "Letting knees cave.", "Using a band that changes position."],
    regressions: ["Use no band.", "Use fewer reps."],
    progressions: ["Add reps first.", "Use a slightly stronger band only when control stays clean."],
    avoid: commonControlledAvoid,
  },
  "Pigeon Strength": {
    setup: ["Start in a comfortable pigeon-style hip position.", "Use hands for support."],
    steps: ["Create light tension through the hip.", "Lift or shift only through a controlled range.", "Return slowly."],
    cues: ["Comfortable range.", "Slow tension.", "No forcing."],
    commonMistakes: ["Dropping into an aggressive stretch.", "Twisting the knee.", "Rushing reps."],
    regressions: ["Use a higher support.", "Shorten the range."],
    progressions: ["Add longer holds.", "Reduce hand support gradually."],
    avoid: commonControlledAvoid,
  },
  "Tibialis Raise": {
    setup: ["Stand with back to a wall or use a tibialis setup.", "Keep heels planted."],
    steps: ["Lift toes toward the shins.", "Pause briefly.", "Lower with control."],
    cues: ["Smooth reps.", "Keep heels down.", "Use full comfortable range."],
    commonMistakes: ["Bouncing.", "Turning feet out excessively.", "Doing partial rushed reps."],
    regressions: ["Stand more upright.", "Use fewer reps."],
    progressions: ["Step farther from the wall.", "Add reps before load."],
    avoid: commonControlledAvoid,
  },
  "Deep Calf Raise": {
    setup: ["Stand on a stable step or calf raise platform.", "Hold support if needed."],
    steps: ["Lower to a comfortable stretch.", "Press up through the big toe side.", "Pause briefly and lower under control."],
    cues: ["Control the bottom.", "Use steady tempo.", "Keep ankle path clean."],
    commonMistakes: ["Bouncing out of the bottom.", "Rolling ankles out.", "Cutting range short."],
    regressions: ["Use both legs.", "Use a smaller range."],
    progressions: ["Add reps first.", "Add load gradually."],
    avoid: commonControlledAvoid,
  },
  "Reverse Step Up": {
    setup: ["Stand on a low box or step.", "Keep one foot planted."],
    steps: ["Reach the free foot back toward the floor.", "Tap lightly.", "Drive through the working leg to stand."],
    cues: ["Control down.", "Knee tracks over toes.", "Use a box height you can own."],
    commonMistakes: ["Dropping quickly.", "Pushing off the floor hard.", "Letting the knee cave."],
    regressions: ["Use a lower box.", "Hold support."],
    progressions: ["Add reps first.", "Use a slightly higher box or light load."],
    avoid: commonControlledAvoid,
  },
  "Full Range Split Squat": {
    setup: ["Set a split stance with both feet stable.", "Hold support if needed."],
    steps: ["Lower through a comfortable full range.", "Keep torso controlled.", "Drive through the front foot to stand."],
    cues: ["Slow down.", "Own the bottom.", "Keep the front foot grounded."],
    commonMistakes: ["Bouncing.", "Letting the front heel lift unexpectedly.", "Using a stance that feels unstable."],
    regressions: ["Use support.", "Shorten the range."],
    progressions: ["Add reps before load.", "Use a deeper range only if control stays clean."],
    avoid: commonControlledAvoid,
  },
  "Active Hang": {
    setup: ["Hold a pull-up bar or stable handles.", "Keep feet supported if a full hang is too much."],
    steps: ["Let shoulders settle under control.", "Create light shoulder tension.", "Step down before grip or shoulder position fades."],
    cues: ["Controlled hang.", "No swinging.", "Keep it easy."],
    commonMistakes: ["Hanging too long.", "Swinging.", "Forcing shoulder range."],
    regressions: ["Keep feet on the floor.", "Use a shorter hold."],
    progressions: ["Use slightly longer comfortable holds."],
    avoid: commonControlledAvoid,
  },
  "Straight Arm Band Pulldown": {
    setup: ["Anchor a light band overhead.", "Hold arms mostly straight with ribs down."],
    steps: ["Pull the band down by moving from the shoulders.", "Pause briefly.", "Return slowly."],
    cues: ["Feel lats.", "Keep elbows quiet.", "Stay light."],
    commonMistakes: ["Turning it into a triceps pushdown.", "Arching the back.", "Using too much tension."],
    regressions: ["Use a lighter band.", "Use a smaller range."],
    progressions: ["Add reps before tension."],
    avoid: commonControlledAvoid,
  },
  "Scapular Pull Up": {
    setup: ["Hang from a bar with feet assisted if needed.", "Keep elbows mostly straight."],
    steps: ["Pull shoulder blades down slightly.", "Pause briefly.", "Return under control."],
    cues: ["Small motion.", "No elbow pull.", "Stop before grip fatigue."],
    commonMistakes: ["Turning it into a pull-up.", "Swinging.", "Using too much range."],
    regressions: ["Keep feet on the floor.", "Use a pulldown version."],
    progressions: ["Use a slightly longer pause."],
    avoid: commonControlledAvoid,
  },
  "Scapular Pull Down": {
    setup: ["Use a light pulldown or band.", "Arms stay mostly straight overhead."],
    steps: ["Pull shoulder blades down.", "Pause briefly.", "Return under control."],
    cues: ["Small smooth motion.", "Keep ribs down.", "Feel shoulder blades move."],
    commonMistakes: ["Bending elbows too much.", "Leaning back hard.", "Using too much load."],
    regressions: ["Use a lighter band.", "Shorten range."],
    progressions: ["Add reps before load."],
    avoid: commonControlledAvoid,
  },
  "Band Pushdown": {
    setup: ["Anchor a light band overhead.", "Keep elbows close to the sides."],
    steps: ["Press hands down.", "Pause briefly.", "Return under control."],
    cues: ["Easy elbow warm-up.", "Keep shoulders quiet.", "Use smooth reps."],
    commonMistakes: ["Locking out aggressively.", "Letting elbows drift.", "Using a band that is too heavy."],
    regressions: ["Use a lighter band.", "Use fewer reps."],
    progressions: ["Add reps before band tension."],
    avoid: commonControlledAvoid,
  },
  "Light Curl": {
    setup: ["Hold a light band or dumbbells.", "Stand tall with elbows by the sides."],
    steps: ["Curl smoothly.", "Pause briefly.", "Lower under control."],
    cues: ["Easy elbow warm-up.", "No swinging.", "Smooth range."],
    commonMistakes: ["Going too heavy.", "Swinging the torso.", "Rushing the lowering."],
    regressions: ["Use a lighter band.", "Use shorter range."],
    progressions: ["Add reps before load."],
    avoid: commonControlledAvoid,
  },
  "Controlled Range Drill": {
    setup: ["Choose a comfortable position for the focus area.", "Keep the movement slow and easy."],
    steps: ["Move through a controlled range.", "Pause briefly where you still have control.", "Return slowly."],
    cues: ["Easy effort.", "Clean range.", "Stop before compensation."],
    commonMistakes: ["Forcing range.", "Rushing reps.", "Treating placeholder work like a hard session."],
    regressions: ["Use a smaller range.", "Do fewer reps."],
    progressions: ["Add reps only when movement stays clean."],
    avoid: commonControlledAvoid,
  },
  "Neck Bridge Progression": {
    setup: ["Advanced only. Start with easier neck control work first.", "Use a soft surface and no external loading."],
    steps: ["Use a very small range.", "Keep breathing steady.", "Stop well before fatigue changes control."],
    cues: ["Conservative control.", "No aggressive loading.", "Slow transitions."],
    commonMistakes: ["Using a large range too soon.", "Adding load.", "Pushing through warning signs."],
    regressions: ["Use supine neck isometrics.", "Use quadruped head nods.", "Use shorter holds."],
    progressions: ["Increase time only after several comfortable exposures.", "Do not add load unless coached in person."],
    avoid: [
      "Stop if discomfort, dizziness, nerve symptoms, or pain occurs.",
      "Avoid aggressive loading.",
      "Avoid this progression if you cannot control easier neck drills.",
    ],
  },
};

export function getMovementGuide(exerciseName: string): MovementGuide {
  return guides[exerciseName] ?? guides["Controlled Range Drill"]!;
}

export function listMovementGuideNames(): string[] {
  return Object.keys(guides);
}
