export const gauntletScenarios = [
  // Level 1 - Normal Progression
  scenario(1, "l1_clean_progression", "Clean progression with high recovery", "intermediate_strength_hypertrophy", {
    performanceTrend: "improving",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "bench_press", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["push", "hold"], ["recover", "stop_movement", "stop_session"], ["low", "moderate"], "clear")),
  scenario(1, "l1_above_range_first_signal", "Above range once, avoid reckless jump", "intermediate_strength_hypertrophy", {
    performanceTrend: "improving",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "lat_pulldown", signal: "above_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["hold"], ["push", "recover", "stop_movement", "stop_session"], ["low"], "clear", {
    rationale: "A single above-range signal should not automatically create a push; upward progression requires stronger evidence.",
  })),
  scenario(1, "l1_bare_minimum_success", "Bare minimum success should not over-push", "beginner_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "machine_chest_press", signal: "inside_range", severity: "none" }],
    systemicSignals: ["none"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(1, "l1_productive_heavier_load", "Heavier load stays inside target range", "intermediate_strength_hypertrophy", {
    performanceTrend: "improving",
    fatigueState: "moderate",
    recoveryState: "good",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "spider_curl", signal: "productive_fatigue", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["consolidate", "hold"], ["reduce", "recover", "stop_session"], ["low"], "clear")),
  scenario(1, "l1_same_load_stable", "Same load stable with good recovery", "intermediate_strength_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "row", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  scenario(1, "l1_local_miss", "One local lift misses range", "intermediate_strength_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "bench_press", signal: "below_range", severity: "moderate" }],
    systemicSignals: ["none"],
  }, expect(["reduce"], ["recover", "stop_session", "push"], ["low"], "caution")),
  scenario(1, "l1_local_dropoff", "Local drop-off without systemic signal", "intermediate_strength_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "leg_extension", signal: "dropoff", severity: "moderate" }],
    systemicSignals: ["none"],
  }, expect(["hold", "reduce"], ["recover", "stop_session", "push"], ["low"], "caution")),
  scenario(1, "l1_accessory_stall", "Accessory exercise stagnant but safe", "beginner_hypertrophy", {
    performanceTrend: "stagnant",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "biceps_curl", signal: "inside_range", severity: "none" }],
    systemicSignals: ["good_readiness"],
  }, expect(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  scenario(1, "l1_duration_progress", "Duration exercise progressing", "beginner_hypertrophy", {
    performanceTrend: "improving",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "front_plank", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["push", "hold"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  scenario(1, "l1_clear_repeated_success", "Repeated success with strong momentum", "advanced_powerlifting", pushReadyEvidence({
    exerciseName: "squat",
    movementPattern: "squat/lower-body pattern",
  }), expect(["push"], ["recover", "stop_session"], ["moderate"], "clear")),
  scenario(1, "l1_low_evidence_new_block", "New block with sparse evidence", "beginner_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "low",
    trainingContinuity: "interrupted",
    localLiftSignals: [{ lift: "all", signal: "none", severity: "none" }],
    systemicSignals: ["none"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(1, "l1_minor_technique_limit", "Minor technique limit", "beginner_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "goblet_squat", signal: "technique_limit", severity: "low" }],
    systemicSignals: ["none"],
  }, expect(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),

  // Level 2 - Real Life
  scenario(2, "l2_missed_week", "Missed week after busy period", "busy_parent_time_constrained", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "low",
    trainingContinuity: "missed_week",
    localLiftSignals: [{ lift: "all", signal: "none", severity: "none" }],
    systemicSignals: ["missed_sessions", "time_constraint"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(2, "l2_time_constrained_stable", "Time constrained but stable training", "busy_parent_time_constrained", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "all", signal: "inside_range", severity: "none" }],
    systemicSignals: ["time_constraint", "low_frequency"],
  }, expect(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  scenario(2, "l2_poor_readiness_strong_performance", "Poor readiness, strong performance", "intermediate_strength_hypertrophy", {
    performanceTrend: "improving",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "bench_press", signal: "above_range", severity: "moderate" }],
    systemicSignals: ["good_readiness"],
    subjectiveContext: subjective({ readiness: "poor", stress: "moderate", sleep: "mixed" }),
  }, expect(["push", "hold"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  scenario(2, "l2_feels_great_declining", "Feels great but objective decline", "advanced_powerlifting", {
    performanceTrend: "declining",
    fatigueState: "high",
    recoveryState: "poor",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "squat", signal: "below_range", severity: "high" }],
    systemicSignals: ["multiple_lifts_down"],
    subjectiveContext: subjective({ readiness: "great", stress: "low", sleep: "good", motivation: "high" }),
  }, expect(["recover", "consolidate", "reduce"], ["push"], ["very_low", "low"], "restrict")),
  scenario(2, "l2_high_stress_stable", "High stress, objective data stable", "busy_parent_time_constrained", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "leg_press", signal: "inside_range", severity: "low" }],
    systemicSignals: ["time_constraint"],
    subjectiveContext: subjective({ readiness: "mixed", stress: "high", sleep: "mixed" }),
  }, expect(["hold"], ["recover", "stop_session", "push"], ["low"], "clear")),
  scenario(2, "l2_low_motivation_consistent", "Low motivation, consistent sessions", "beginner_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "machine_chest_press", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
    subjectiveContext: subjective({ motivation: "low", readiness: "good", sleep: "good" }),
  }, expect(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  scenario(2, "l2_sleep_poor_performance_ok", "Poor sleep report, performance okay", "intermediate_strength_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "row", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
    subjectiveContext: subjective({ sleep: "poor", readiness: "mixed" }),
  }, expect(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  scenario(2, "l2_repeated_skips_time", "Repeated skipped accessories from time", "busy_parent_time_constrained", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "all", signal: "inside_range", severity: "none" }],
    systemicSignals: ["time_constraint"],
  }, expect(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  scenario(2, "l2_travel_interruption", "Travel interruption, no clear performance loss", "busy_parent_time_constrained", {
    performanceTrend: "mixed",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "low",
    trainingContinuity: "interrupted",
    localLiftSignals: [{ lift: "all", signal: "none", severity: "none" }],
    systemicSignals: ["missed_sessions"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(2, "l2_recovery_work_completed", "Recovery work completed and training stable", "recovery_limited_lifter", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "leg_press", signal: "inside_range", severity: "none" }],
    systemicSignals: ["none"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(2, "l2_cardio_added_no_strength_drop", "Cardio added, strength stable", "intermediate_strength_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "bench_press", signal: "inside_range", severity: "none" }],
    systemicSignals: ["good_readiness"],
  }, expect(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  scenario(2, "l2_late_session_density", "Training compressed but work completed", "busy_parent_time_constrained", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "all", signal: "inside_range", severity: "low" }],
    systemicSignals: ["time_constraint"],
  }, expect(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  scenario(2, "l2_one_bad_day", "One bad day after normal progress", "intermediate_strength_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "bench_press", signal: "below_range", severity: "low" }],
    systemicSignals: ["none"],
  }, expect(["reduce", "hold"], ["recover", "stop_session", "push"], ["low"], "caution")),
  scenario(2, "l2_equipment_swap", "Equipment swap but training completed", "beginner_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "machine_row", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),

  // Level 3 - Coaching Judgement
  scenario(3, "l3_adaptation_high_recovery_low", "Adaptation high, recovery low", "advanced_powerlifting", {
    performanceTrend: "improving",
    fatigueState: "high",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "squat", signal: "inside_range", severity: "low" }],
    systemicSignals: ["high_soreness", "sleep_disrupted"],
  }, expect(["consolidate"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(3, "l3_systemic_fatigue", "Systemic fatigue across multiple lifts", "advanced_powerlifting", {
    performanceTrend: "declining",
    fatigueState: "high",
    recoveryState: "poor",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [
      { lift: "squat", signal: "below_range", severity: "high" },
      { lift: "deadlift", signal: "below_range", severity: "high" }
    ],
    systemicSignals: ["multiple_lifts_down", "high_soreness", "sleep_disrupted"],
  }, expect(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  scenario(3, "l3_repeated_same_load_collapse", "Repeated same-load collapse", "recovery_limited_lifter", {
    performanceTrend: "declining",
    fatigueState: "high",
    recoveryState: "poor",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "squat", signal: "same_load_collapse", severity: "high" }],
    systemicSignals: ["multiple_lifts_down", "high_soreness"],
  }, expect(["substitute", "reduce", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  scenario(3, "l3_repeated_shutdown_same_pattern", "Repeated shutdown same pattern", "advanced_powerlifting", {
    performanceTrend: "declining",
    fatigueState: "high",
    recoveryState: "poor",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "deadlift", signal: "repeated_shutdown", severity: "high" }],
    systemicSignals: ["multiple_lifts_down"],
  }, expect(["substitute", "reduce", "recover"], ["push"], ["very_low", "low"], "restrict")),
  scenario(3, "l3_local_failure_not_systemic", "Local failure should stay local", "intermediate_strength_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "overhead_press", signal: "below_range", severity: "moderate" }],
    systemicSignals: ["none"],
  }, expect(["reduce"], ["recover", "push", "stop_session"], ["low"], "caution")),
  scenario(3, "l3_momentum_low_recovery_good", "Momentum low, recovery good", "beginner_hypertrophy", {
    performanceTrend: "stagnant",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "interrupted",
    localLiftSignals: [{ lift: "machine_chest_press", signal: "inside_range", severity: "none" }],
    systemicSignals: ["missed_sessions"],
    subjectiveContext: subjective({ motivation: "low", readiness: "good" }),
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(3, "l3_confidence_low_stable_objective", "Confidence low, objective stable", "beginner_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "goblet_squat", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
    subjectiveContext: subjective({ motivation: "low", readiness: "mixed" }),
  }, expect(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  scenario(3, "l3_low_evidence_promising", "Low evidence but promising performance", "beginner_hypertrophy", {
    performanceTrend: "improving",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "low",
    trainingContinuity: "interrupted",
    localLiftSignals: [{ lift: "leg_press", signal: "above_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(3, "l3_good_progress_high_soreness", "Good progress with high soreness", "recovery_limited_lifter", {
    performanceTrend: "improving",
    fatigueState: "high",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "leg_press", signal: "inside_range", severity: "low" }],
    systemicSignals: ["high_soreness"],
  }, expect(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(3, "l3_minor_pain_no_performance_loss", "Mild pain report, no performance loss", "intermediate_strength_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "bench_press", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
    subjectiveContext: subjective({ safetyFlag: "pain", readiness: "good" }),
  }, expect(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  scenario(3, "l3_worsening_pain", "Worsening pain across sessions", "recovery_limited_lifter", {
    performanceTrend: "declining",
    fatigueState: "high",
    recoveryState: "poor",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "deadlift", signal: "below_range", severity: "moderate" }],
    systemicSignals: ["multiple_lifts_down", "high_soreness"],
    subjectiveContext: subjective({ safetyFlag: "worsening_pain", readiness: "poor", sleep: "poor" }),
  }, expect(["stop_session", "stop_movement"], ["push", "recover"], ["very_low"], "stop", {
    rationale: "Worsening pain should route through a stronger safety response than ordinary recovery bias.",
  })),
  scenario(3, "l3_sharp_pain_movement", "Sharp pain on squat pattern", "advanced_powerlifting", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "squat", signal: "technique_limit", severity: "moderate" }],
    systemicSignals: ["none"],
    subjectiveContext: subjective({ safetyFlag: "sharp_pain", readiness: "good" }),
  }, expect(["stop_movement"], ["push", "recover"], ["very_low"], "stop")),

  // Level 4 - Expert Coaching
  scenario(4, "l4_advanced_powerlifter_peak_fatigue", "Advanced lifter progressing but fatigue cost high", "advanced_powerlifting", {
    performanceTrend: "improving",
    fatigueState: "high",
    recoveryState: "mixed",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "squat", signal: "inside_range", severity: "low" }],
    systemicSignals: ["high_soreness", "sleep_disrupted"],
  }, expect(["consolidate"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(4, "l4_bodybuilder_local_failure", "Bodybuilder local isolation failure", "recovery_limited_lifter", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "lateral_raise", signal: "below_range", severity: "moderate" }],
    systemicSignals: ["none"],
  }, expect(["reduce"], ["recover", "stop_session", "push"], ["low"], "caution")),
  scenario(4, "l4_compound_axial_stack", "High cost compound fatigue stack", "advanced_powerlifting", {
    performanceTrend: "declining",
    fatigueState: "high",
    recoveryState: "poor",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [
      { lift: "squat", signal: "dropoff", severity: "high" },
      { lift: "deadlift", signal: "dropoff", severity: "high" }
    ],
    systemicSignals: ["multiple_lifts_down", "high_soreness"],
  }, expect(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  scenario(4, "l4_productive_isolation_fatigue", "High-rep isolation productive fatigue", "intermediate_strength_hypertrophy", {
    performanceTrend: "improving",
    fatigueState: "moderate",
    recoveryState: "good",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "spider_curl", signal: "productive_fatigue", severity: "low" }],
    systemicSignals: ["good_readiness"],
  }, expect(["consolidate", "hold"], ["reduce", "recover", "stop_session"], ["low"], "clear")),
  scenario(4, "l4_low_frequency_stimulus", "Low frequency requires clear but not brutal work", "busy_parent_time_constrained", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "all", signal: "inside_range", severity: "none" }],
    systemicSignals: ["low_frequency", "time_constraint"],
  }, expect(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  scenario(4, "l4_return_after_illness", "Return after interruption with low evidence", "recovery_limited_lifter", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "low",
    trainingContinuity: "missed_week",
    localLiftSignals: [{ lift: "all", signal: "none", severity: "none" }],
    systemicSignals: ["missed_sessions"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  scenario(4, "l4_unsafe_report", "User explicitly reports unsafe training", "intermediate_strength_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "bench_press", signal: "inside_range", severity: "low" }],
    systemicSignals: ["good_readiness"],
    subjectiveContext: subjective({ safetyFlag: "unsafe", readiness: "good" }),
  }, expect(["stop_session"], ["push"], ["very_low"], "stop")),
  scenario(4, "l4_dizziness_systemic", "Dizziness reported during session", "beginner_hypertrophy", {
    performanceTrend: "stable",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "all", signal: "none", severity: "none" }],
    systemicSignals: ["none"],
    subjectiveContext: subjective({ safetyFlag: "dizziness", readiness: "mixed" }),
  }, expect(["stop_session"], ["push", "recover"], ["very_low"], "stop")),
  scenario(4, "l4_repeated_swap_possible_pain", "Repeated swap with technique concern", "intermediate_strength_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "moderate",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "overhead_press", signal: "technique_limit", severity: "moderate" }],
    systemicSignals: ["none"],
  }, expect(["hold", "reduce", "substitute"], ["push", "recover", "stop_session"], ["low"], "caution")),
  scenario(4, "l4_long_run_of_success", "Long successful run with no fatigue concern", "intermediate_strength_hypertrophy", pushReadyEvidence({
    exerciseName: "bench_press",
    movementPattern: "pressing pattern",
    secondaryExerciseName: "row",
    secondaryMovementPattern: "hinge/pull pattern",
  }), expect(["push"], ["recover", "stop_session"], ["moderate"], "clear")),
  scenario(4, "l4_conflicting_signals", "Strong upper body, lower body down", "advanced_powerlifting", {
    performanceTrend: "mixed",
    fatigueState: "moderate",
    recoveryState: "mixed",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [
      { lift: "bench_press", signal: "above_range", severity: "low" },
      { lift: "squat", signal: "below_range", severity: "moderate" }
    ],
    systemicSignals: ["none"],
  }, expect(["reduce", "hold"], ["push", "recover", "stop_session"], ["low"], "caution")),
  scenario(4, "l4_recovery_week_needed", "Systemic decline after overload", "recovery_limited_lifter", {
    performanceTrend: "declining",
    fatigueState: "high",
    recoveryState: "poor",
    evidenceQuality: "high",
    trainingContinuity: "consistent",
    localLiftSignals: [
      { lift: "squat", signal: "below_range", severity: "high" },
      { lift: "bench_press", signal: "below_range", severity: "moderate" },
      { lift: "deadlift", signal: "dropoff", severity: "high" }
    ],
    systemicSignals: ["multiple_lifts_down", "high_soreness", "sleep_disrupted"],
  }, expect(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  scenario(4, "l4_not_enough_data_do_not_overfit", "Not enough data, do not overfit", "beginner_hypertrophy", {
    performanceTrend: "mixed",
    fatigueState: "low",
    recoveryState: "good",
    evidenceQuality: "low",
    trainingContinuity: "consistent",
    localLiftSignals: [{ lift: "all", signal: "none", severity: "none" }],
    systemicSignals: ["good_readiness"],
  }, expect(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
];

function scenario(level, id, title, athleteProfileId, evidence, expected) {
  return {
    id,
    level,
    level_label: levelLabel(level),
    title,
    athleteProfileId,
    evidence: {
      id,
      scenario: title,
      athleteProfileId,
      status: "research_fixture",
      notes: [`Gauntlet ${levelLabel(level)} scenario.`],
      approvalStatus: "draft_requires_aaron_approval",
      ...evidence,
    },
    expected,
    rationale: expected.rationale,
    confidence: expected.confidence_min,
    charter_alignment: expected.charter_alignment,
  };
}

function expect(allowedTypes, forbiddenTypes, allowedAggressiveness, safetyStatus, overrides = {}) {
  return {
    recommendation_types: allowedTypes,
    forbidden_recommendation_types: forbiddenTypes,
    aggressiveness: allowedAggressiveness,
    safety_gate_status: safetyStatus,
    confidence_min: overrides.confidence_min ?? 45,
    rationale: overrides.rationale ?? "Expected output should follow the Charter, prioritise objective evidence, and use the smallest effective intervention.",
    charter_alignment: overrides.charter_alignment ?? {
      long_term_progress: true,
      adaptation: true,
      recovery: true,
      confidence: true,
      enjoyment: true,
      momentum: true,
    },
  };
}

function subjective(values) {
  return {
    readiness: values.readiness ?? "mixed",
    stress: values.stress ?? "moderate",
    sleep: values.sleep ?? "mixed",
    motivation: values.motivation ?? "moderate",
    soreness: values.soreness ?? "moderate",
    safetyFlag: values.safetyFlag ?? "none",
    notes: values.notes ?? "Gauntlet subjective context.",
  };
}

function pushReadyEvidence({ exerciseName, movementPattern, secondaryExerciseName = null, secondaryMovementPattern = null }) {
  const primary = pushReadyExercise({ exerciseName, movementPattern });
  const exercises = secondaryExerciseName
    ? [primary, pushReadyExercise({ exerciseName: secondaryExerciseName, movementPattern: secondaryMovementPattern, aboveRangeEvents: 2 })]
    : [primary];

  return {
    evidenceModelVersion: "v0.7",
    sessionHistory: {
      plannedSessionsCompleted: 5,
      plannedSessionsMissed: 0,
      extraSessionsCompleted: 0,
      sessionSpacing: "normal",
      completedSets: 15,
      skippedExercises: 0,
      sessionDurationMinutes: 60,
      sessionCompletionQuality: "good",
    },
    exerciseHistory: exercises,
    swapHistory: null,
    consolidationHistory: {
      recentPushOccurred: false,
      plannedConsolidationDue: false,
      consolidationCompleted: true,
      ownsNewLoad: true,
      repeatedSuccessfulExposuresAtNewLoad: 3,
    },
    frequencyStimulus: {
      trainingDaysAvailable: 4,
      currentFrequency: 4,
      sessionDensity: "moderate",
      compoundDensity: "moderate",
      weeklyHardSetEstimate: 14,
      axialLoadingDensity: "moderate",
      highFatigueMovementClustering: "low",
      lowFrequencyHighDensityWarning: false,
      highFrequencyFatigue: false,
      hiddenOverreachRisk: false,
    },
    safetyContext: {
      affectedArea: "none",
      affectedMovementPattern: "none",
      painTrend: "none",
      painSeverity: "none",
      techniqueBreakdown: false,
      systemicRedFlags: [],
      safetyIssueScope: "none",
    },
    evidenceConfidence: {
      plannedEvidenceCount: 5,
      comparableExposureCount: 3,
      recency: "recent",
      dataCompleteness: "high",
      evidenceSourceQuality: "high",
    },
  };
}

function pushReadyExercise({ exerciseName, movementPattern, aboveRangeEvents = 2 }) {
  return {
    exerciseName,
    movementPattern,
    targetRange: { min: 8, max: 12, unit: "reps" },
    loads: [100, 100, 100],
    repsOrSeconds: [12, 12, 12],
    withinRange: true,
    comparableLoadTrend: "improving",
    loadEvents: [],
    shutdowns: 0,
    belowMinimumEvents: 0,
    aboveRangeEvents,
    productiveFatigue: false,
    newExercise: false,
    techniqueBreakdown: "none",
    repeatedSuccessfulExposuresAtLoad: 3,
  };
}

function levelLabel(level) {
  if (level === 1) return "Level 1 - Normal Progression";
  if (level === 2) return "Level 2 - Real Life";
  if (level === 3) return "Level 3 - Coaching Judgement";
  return "Level 4 - Expert Coaching";
}
