import { gauntletScenarios } from "./scenarios.mjs";

const expandedScenarios = [
  // Level 1 - Normal Progression
  s(1, "v02_l1_steady_double_progression", "Steady load and rep progression", "intermediate_strength_hypertrophy", e("improving", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }, { lift: "row", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["push", "hold"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(1, "v02_l1_repeated_rep_prs", "Repeated rep PRs across sessions", "intermediate_strength_hypertrophy", e("improving", "low", "good", "high", "consistent", [{ lift: "leg_press", signal: "above_range", severity: "moderate" }, { lift: "lat_pulldown", signal: "above_range", severity: "moderate" }], ["good_readiness"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_single_rep_pr_hold", "One rep PR only", "beginner_hypertrophy", e("improving", "low", "good", "moderate", "consistent", [{ lift: "machine_row", signal: "above_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_productive_fatigue_upper", "Productive fatigue after upper-body load increase", "intermediate_strength_hypertrophy", e("improving", "moderate", "good", "high", "consistent", [{ lift: "incline_press", signal: "productive_fatigue", severity: "low" }], ["good_readiness"]), x(["consolidate", "hold"], ["reduce", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_planned_consolidation_after_push", "Planned consolidation after a push", "advanced_powerlifting", e("improving", "moderate", "mixed", "high", "consistent", [{ lift: "squat", signal: "inside_range", severity: "low" }], ["high_soreness", "planned_consolidation"]), x(["consolidate"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_successful_recovery_week_return", "Successful return after recovery week", "recovery_limited_lifter", e("stable", "low", "good", "moderate", "consistent", [{ lift: "leg_press", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(1, "v02_l1_accessory_progress_no_compound_change", "Accessory improves while compounds stable", "intermediate_strength_hypertrophy", e("stable", "low", "good", "moderate", "consistent", [{ lift: "lateral_raise", signal: "above_range", severity: "moderate" }, { lift: "bench_press", signal: "inside_range", severity: "none" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(1, "v02_l1_duration_hold_progress", "Duration hold improves", "beginner_hypertrophy", e("improving", "low", "good", "moderate", "consistent", [{ lift: "side_plank", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(1, "v02_l1_barely_in_range_high_fatigue", "Barely in range with fatigue", "intermediate_strength_hypertrophy", e("stable", "high", "mixed", "moderate", "consistent", [{ lift: "hack_squat", signal: "inside_range", severity: "none" }], ["high_soreness"]), x(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_clean_low_frequency_progress", "Clean progress on low frequency", "busy_parent_time_constrained", e("improving", "low", "good", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["good_readiness", "low_frequency"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(1, "v02_l1_high_frequency_clean_but_tired", "High frequency clean performance but tired", "advanced_powerlifting", e("improving", "moderate", "mixed", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }, { lift: "squat", signal: "inside_range", severity: "low" }], ["high_soreness"]), x(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_new_exercise_uncertain_success", "New exercise success but uncertain", "beginner_hypertrophy", e("mixed", "low", "good", "low", "consistent", [{ lift: "machine_chest_press", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_repeated_success_no_pr", "No PRs but steady work", "intermediate_strength_hypertrophy", e("stable", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }, { lift: "row", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_momentum_positive_not_aggressive", "Momentum positive but no need to chase", "beginner_hypertrophy", e("improving", "moderate", "mixed", "moderate", "consistent", [{ lift: "leg_extension", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_above_range_repeated_is_earned", "Repeated above range is earned progression", "intermediate_strength_hypertrophy", e("improving", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "above_range", severity: "moderate" }, { lift: "bench_press", signal: "above_range", severity: "moderate" }], ["good_readiness"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_productive_fatigue_not_recovery", "Productive fatigue should not become recovery", "intermediate_strength_hypertrophy", e("improving", "moderate", "mixed", "high", "consistent", [{ lift: "spider_curl", signal: "productive_fatigue", severity: "low" }], ["high_soreness"]), x(["consolidate", "hold"], ["recover", "reduce", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_mild_dropoff_after_pr", "Mild drop-off after a PR", "intermediate_strength_hypertrophy", e("mixed", "moderate", "mixed", "moderate", "consistent", [{ lift: "lat_pulldown", signal: "above_range", severity: "low" }, { lift: "lat_pulldown", signal: "dropoff", severity: "low" }], ["none"]), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(1, "v02_l1_recovery_week_completed_stable", "Recovery week completed, stable return", "recovery_limited_lifter", e("stable", "low", "good", "high", "consistent", [{ lift: "machine_row", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(1, "v02_l1_strength_skill_stable", "Strength skill stable, avoid novelty", "advanced_powerlifting", e("stable", "low", "good", "moderate", "consistent", [{ lift: "squat", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(1, "v02_l1_beginner_confidence_win", "Beginner needs a confidence win", "beginner_hypertrophy", e("stable", "low", "good", "moderate", "consistent", [{ lift: "leg_press", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ motivation: "low", readiness: "good" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),

  // Level 2 - Real Life
  s(2, "v02_l2_holiday_two_sessions_missed", "Holiday with two missed sessions", "busy_parent_time_constrained", e("mixed", "low", "good", "low", "interrupted", [{ lift: "all", signal: "none", severity: "none" }], ["missed_sessions"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_illness_return_low_evidence", "Illness return with low evidence", "recovery_limited_lifter", e("mixed", "moderate", "mixed", "low", "missed_week", [{ lift: "all", signal: "none", severity: "none" }], ["missed_sessions"], subj({ readiness: "poor", sleep: "poor" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_work_stress_but_strong_sets", "Work stress but strong sets", "busy_parent_time_constrained", e("improving", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ stress: "high", sleep: "mixed" })), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(2, "v02_l2_shift_work_sleep_poor_stable", "Shift work poor sleep, stable training", "busy_parent_time_constrained", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "leg_press", signal: "inside_range", severity: "low" }], ["time_constraint"], subj({ sleep: "poor", stress: "high" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_new_baby_consistent_short_sessions", "New baby, consistent short sessions", "busy_parent_time_constrained", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["time_constraint"], subj({ sleep: "poor", motivation: "moderate" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_inconsistent_schedule_good_performance", "Inconsistent schedule but good performance", "busy_parent_time_constrained", e("improving", "low", "good", "moderate", "interrupted", [{ lift: "row", signal: "inside_range", severity: "low" }], ["missed_sessions"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_short_training_week_one_good_session", "Short week with one good session", "intermediate_strength_hypertrophy", e("improving", "low", "good", "low", "interrupted", [{ lift: "bench_press", signal: "above_range", severity: "low" }], ["missed_sessions"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_claims_fatigue_keeps_progressing", "Claims fatigue but keeps progressing", "intermediate_strength_hypertrophy", e("improving", "low", "good", "high", "consistent", [{ lift: "squat", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ readiness: "poor", soreness: "high" })), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(2, "v02_l2_low_motivation_high_adherence", "Low motivation but high adherence", "intermediate_strength_hypertrophy", e("stable", "low", "good", "high", "consistent", [{ lift: "machine_press", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ motivation: "low" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_feels_awful_hits_targets", "Feels awful but hits targets", "recovery_limited_lifter", e("stable", "low", "good", "high", "consistent", [{ lift: "lat_pulldown", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ readiness: "poor", sleep: "poor", stress: "high" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_feels_great_misses_targets", "Feels great but misses targets", "intermediate_strength_hypertrophy", e("declining", "high", "poor", "high", "consistent", [{ lift: "bench_press", signal: "below_range", severity: "high" }], ["multiple_lifts_down"], subj({ readiness: "great", motivation: "high" })), x(["recover", "reduce", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  s(2, "v02_l2_stress_high_performance_stable", "High stress, performance stable", "busy_parent_time_constrained", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "hack_squat", signal: "inside_range", severity: "low" }], ["time_constraint"], subj({ stress: "high", readiness: "mixed" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_missed_sessions_after_overload", "Missed sessions after overload", "recovery_limited_lifter", e("mixed", "high", "poor", "moderate", "missed_week", [{ lift: "all", signal: "none", severity: "none" }], ["missed_sessions"], subj({ readiness: "poor" })), x(["hold", "consolidate"], ["push", "stop_session"], ["low"], "caution")),
  s(2, "v02_l2_session_cut_short_no_failure", "Session cut short without failure", "busy_parent_time_constrained", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "all", signal: "inside_range", severity: "none" }], ["time_constraint"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_after_travel_first_week_back", "First week back after travel", "intermediate_strength_hypertrophy", e("mixed", "moderate", "mixed", "low", "interrupted", [{ lift: "all", signal: "none", severity: "none" }], ["missed_sessions"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_holiday_then_pr", "Holiday then one PR", "intermediate_strength_hypertrophy", e("improving", "low", "good", "low", "interrupted", [{ lift: "leg_press", signal: "above_range", severity: "moderate" }], ["missed_sessions", "good_readiness"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_work_trip_sleep_poor_declining", "Work trip poor sleep and declining lifts", "busy_parent_time_constrained", e("declining", "high", "poor", "high", "interrupted", [{ lift: "bench_press", signal: "below_range", severity: "moderate" }, { lift: "row", signal: "below_range", severity: "moderate" }], ["multiple_lifts_down", "missed_sessions"], subj({ sleep: "poor", stress: "high" })), x(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  s(2, "v02_l2_family_disruption_stable", "Family disruption, stable behaviour", "busy_parent_time_constrained", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["time_constraint"], subj({ stress: "high", motivation: "low" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_inconsistent_but_no_decline", "Inconsistent but no decline", "beginner_hypertrophy", e("stable", "low", "good", "low", "interrupted", [{ lift: "machine_row", signal: "inside_range", severity: "low" }], ["missed_sessions"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(2, "v02_l2_short_sessions_progressing", "Short sessions progressing", "busy_parent_time_constrained", e("improving", "low", "good", "moderate", "consistent", [{ lift: "leg_press", signal: "inside_range", severity: "low" }], ["time_constraint", "good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),

  // Level 3 - Coaching Judgement
  s(3, "v02_l3_bench_stalls_lower_improves", "Bench stalls while lower body improves", "intermediate_strength_hypertrophy", e("mixed", "moderate", "mixed", "high", "consistent", [{ lift: "bench_press", signal: "below_range", severity: "moderate" }, { lift: "leg_press", signal: "inside_range", severity: "low" }], ["none"]), x(["reduce"], ["recover", "push", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_squat_stalls_accessories_improve", "Squat stalls, accessories improve", "advanced_powerlifting", e("mixed", "moderate", "mixed", "high", "consistent", [{ lift: "squat", signal: "below_range", severity: "moderate" }, { lift: "leg_extension", signal: "above_range", severity: "moderate" }], ["none"]), x(["reduce", "hold"], ["recover", "push", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_deadlift_fatigue_accumulates", "Deadlift fatigue accumulates", "advanced_powerlifting", e("mixed", "high", "mixed", "high", "consistent", [{ lift: "deadlift", signal: "dropoff", severity: "high" }], ["high_soreness"]), x(["reduce", "substitute", "consolidate"], ["push", "recover", "stop_session"], ["very_low", "low"], "restrict")),
  s(3, "v02_l3_isolation_stall_only", "Isolation exercise stalls only", "beginner_hypertrophy", e("stagnant", "low", "good", "moderate", "consistent", [{ lift: "biceps_curl", signal: "below_range", severity: "low" }], ["good_readiness"]), x(["reduce", "hold"], ["recover", "stop_session", "push"], ["low"], "caution")),
  s(3, "v02_l3_swap_improves_performance", "Exercise swap improves performance", "intermediate_strength_hypertrophy", e("improving", "low", "good", "moderate", "consistent", [{ lift: "machine_chest_press", signal: "inside_range", severity: "low" }], ["good_readiness", "post_swap_improvement"]), x(["consolidate"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(3, "v02_l3_new_exercise_uncertainty", "New exercise uncertainty", "beginner_hypertrophy", e("mixed", "moderate", "mixed", "low", "consistent", [{ lift: "hack_squat", signal: "inside_range", severity: "none" }], ["none"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(3, "v02_l3_multiple_lifts_declining", "Multiple lifts declining", "advanced_powerlifting", e("declining", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "below_range", severity: "high" }, { lift: "bench_press", signal: "below_range", severity: "moderate" }], ["multiple_lifts_down", "high_soreness"]), x(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  s(3, "v02_l3_repeated_shutdowns_same_pattern", "Repeated shutdowns same pattern", "advanced_powerlifting", e("declining", "high", "mixed", "high", "consistent", [{ lift: "deadlift", signal: "repeated_shutdown", severity: "high" }], ["high_soreness"]), x(["substitute", "reduce"], ["push", "recover", "stop_session"], ["very_low", "low"], "restrict")),
  s(3, "v02_l3_dropping_despite_rest", "Performance dropping despite rest", "recovery_limited_lifter", e("declining", "high", "poor", "high", "consistent", [{ lift: "bench_press", signal: "below_range", severity: "high" }, { lift: "leg_press", signal: "below_range", severity: "moderate" }], ["multiple_lifts_down"]), x(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  s(3, "v02_l3_recovery_week_needed", "Recovery week appears needed", "recovery_limited_lifter", e("declining", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "dropoff", severity: "high" }, { lift: "row", signal: "below_range", severity: "moderate" }], ["multiple_lifts_down", "high_soreness", "sleep_disrupted"]), x(["recover"], ["push", "stop_session"], ["very_low"], "restrict")),
  s(3, "v02_l3_recovery_week_not_needed_one_bad_lift", "Recovery week not needed from one bad lift", "intermediate_strength_hypertrophy", e("mixed", "moderate", "mixed", "moderate", "consistent", [{ lift: "bench_press", signal: "below_range", severity: "moderate" }], ["none"]), x(["reduce"], ["recover", "push", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_mild_discomfort_improving", "Mild discomfort with improving performance", "intermediate_strength_hypertrophy", e("improving", "low", "good", "high", "consistent", [{ lift: "squat", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ safetyFlag: "pain", readiness: "good" })), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_pain_improving_performance", "Pain report but performance improving", "advanced_powerlifting", e("improving", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ safetyFlag: "pain", readiness: "great" })), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_pain_declining_performance", "Pain with declining performance", "recovery_limited_lifter", e("declining", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "below_range", severity: "high" }], ["multiple_lifts_down"], subj({ safetyFlag: "pain", readiness: "poor" })), x(["reduce", "substitute"], ["push", "recover", "stop_session"], ["very_low", "low"], "restrict")),
  s(3, "v02_l3_tech_breakdown_bench", "Bench technique breakdown", "intermediate_strength_hypertrophy", e("mixed", "moderate", "mixed", "high", "consistent", [{ lift: "bench_press", signal: "technique_limit", severity: "moderate" }], ["none"]), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_tech_breakdown_deadlift", "Deadlift technique breakdown", "advanced_powerlifting", e("mixed", "high", "mixed", "high", "consistent", [{ lift: "deadlift", signal: "technique_limit", severity: "high" }], ["high_soreness"]), x(["substitute", "reduce"], ["push", "recover", "stop_session"], ["very_low", "low"], "caution")),
  s(3, "v02_l3_stop_movement_not_session", "Movement-specific stop, not session stop", "intermediate_strength_hypertrophy", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "squat", signal: "technique_limit", severity: "moderate" }], ["none"], subj({ safetyFlag: "sharp_pain", readiness: "good" })), x(["stop_movement"], ["push", "recover", "stop_session"], ["very_low"], "stop")),
  s(3, "v02_l3_session_stop_systemic_red_flag", "Session-wide stop for systemic red flag", "beginner_hypertrophy", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "all", signal: "none", severity: "none" }], ["none"], subj({ safetyFlag: "dizziness", readiness: "mixed" })), x(["stop_session"], ["push", "recover"], ["very_low"], "stop")),
  s(3, "v02_l3_confidence_low_after_failed_lift", "Confidence low after failed lift", "beginner_hypertrophy", e("mixed", "moderate", "mixed", "moderate", "consistent", [{ lift: "machine_press", signal: "below_range", severity: "moderate" }], ["none"], subj({ motivation: "low", readiness: "poor" })), x(["reduce", "hold"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_confidence_high_weak_evidence", "Confidence high but evidence weak", "beginner_hypertrophy", e("improving", "low", "good", "low", "consistent", [{ lift: "leg_press", signal: "above_range", severity: "low" }], ["good_readiness"], subj({ motivation: "high", readiness: "great" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(3, "v02_l3_needs_clear_win", "Needs a clear win after stagnation", "busy_parent_time_constrained", e("stagnant", "low", "good", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "none" }], ["good_readiness"], subj({ motivation: "low" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(3, "v02_l3_variety_needed_adherence", "Variety needed for adherence but performance okay", "busy_parent_time_constrained", e("stable", "low", "good", "moderate", "consistent", [{ lift: "machine_row", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ motivation: "low" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(3, "v02_l3_6_to_3_days_constraint", "Six days to three days constraint", "busy_parent_time_constrained", e("mixed", "moderate", "mixed", "moderate", "interrupted", [{ lift: "all", signal: "inside_range", severity: "none" }], ["time_constraint", "low_frequency"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(3, "v02_l3_3_to_5_days_progressing", "Three to five days, progressing", "intermediate_strength_hypertrophy", e("improving", "low", "good", "moderate", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(3, "v02_l3_high_frequency_fatigue", "High frequency accumulating fatigue", "advanced_powerlifting", e("mixed", "high", "mixed", "high", "consistent", [{ lift: "squat", signal: "dropoff", severity: "moderate" }, { lift: "deadlift", signal: "dropoff", severity: "moderate" }], ["high_soreness", "high_frequency"]), x(["consolidate", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(3, "v02_l3_low_frequency_progressing", "Low frequency lifter progressing", "busy_parent_time_constrained", e("improving", "low", "good", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["low_frequency", "good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(3, "v02_l3_long_sessions_quality_dropping", "Long sessions causing quality drop", "advanced_powerlifting", e("mixed", "high", "mixed", "high", "consistent", [{ lift: "accessory_work", signal: "dropoff", severity: "high" }], ["high_soreness"]), x(["reduce", "consolidate"], ["push", "recover", "stop_session"], ["low"], "restrict")),
  s(3, "v02_l3_short_sessions_no_issue", "Short sessions without issue", "busy_parent_time_constrained", e("stable", "low", "good", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["time_constraint", "good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),

  // Level 4 - Expert Coaching
  s(4, "v02_l4_advanced_plateau_no_fatigue", "Advanced plateau without fatigue", "advanced_powerlifting", e("stagnant", "low", "good", "high", "consistent", [{ lift: "squat", signal: "inside_range", severity: "none" }], ["good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_repeated_deload_requests_no_need", "Repeated deload requests without objective need", "recovery_limited_lifter", e("stable", "low", "good", "high", "consistent", [{ lift: "leg_press", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ readiness: "poor", motivation: "low" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_aggressive_progress_hidden_fatigue", "Aggressive progress with hidden fatigue", "advanced_powerlifting", e("improving", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "above_range", severity: "moderate" }, { lift: "deadlift", signal: "dropoff", severity: "moderate" }], ["high_soreness", "sleep_disrupted"]), x(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_high_performing_bored", "High-performing but bored athlete", "intermediate_strength_hypertrophy", e("improving", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ motivation: "low", readiness: "good" })), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(4, "v02_l4_successful_but_high_joint_cost", "Technically successful but high long-term cost", "advanced_powerlifting", e("stable", "high", "mixed", "high", "consistent", [{ lift: "deadlift", signal: "inside_range", severity: "low" }], ["high_soreness"]), x(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_too_many_compounds_low_frequency", "Too many compounds in low-frequency plan", "busy_parent_time_constrained", e("mixed", "high", "mixed", "moderate", "consistent", [{ lift: "squat", signal: "dropoff", severity: "moderate" }, { lift: "bench_press", signal: "inside_range", severity: "low" }, { lift: "deadlift", signal: "dropoff", severity: "moderate" }], ["low_frequency", "high_soreness", "compound_density_high"]), x(["reduce", "consolidate"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_excessive_isolation_volume", "Excessive isolation volume", "beginner_hypertrophy", e("mixed", "moderate", "mixed", "moderate", "consistent", [{ lift: "lateral_raise", signal: "dropoff", severity: "moderate" }, { lift: "biceps_curl", signal: "dropoff", severity: "moderate" }], ["high_soreness"]), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_returning_after_time_away", "Returning after time away", "intermediate_strength_hypertrophy", e("mixed", "moderate", "mixed", "low", "missed_week", [{ lift: "all", signal: "none", severity: "none" }], ["missed_sessions"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_cutting_phase_stable", "Cutting phase, stable performance", "intermediate_strength_hypertrophy", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["none"], subj({ motivation: "moderate", sleep: "mixed" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_cutting_phase_decline", "Cutting phase, performance declining", "intermediate_strength_hypertrophy", e("declining", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "below_range", severity: "moderate" }, { lift: "bench_press", signal: "below_range", severity: "moderate" }], ["multiple_lifts_down", "high_soreness"]), x(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  s(4, "v02_l4_maintenance_low_stress", "Maintenance phase low stress", "busy_parent_time_constrained", e("stable", "low", "good", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_recomposition_slow_progress", "Recomposition slow progress", "intermediate_strength_hypertrophy", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "leg_press", signal: "inside_range", severity: "none" }], ["none"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_peaking_high_fatigue", "Peaking with high fatigue", "advanced_powerlifting", e("improving", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "inside_range", severity: "low" }, { lift: "bench_press", signal: "inside_range", severity: "low" }], ["high_soreness", "sleep_disrupted"]), x(["consolidate"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_post_peak_return", "Post-peak return", "advanced_powerlifting", e("mixed", "moderate", "mixed", "low", "interrupted", [{ lift: "squat", signal: "inside_range", severity: "none" }], ["none"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_powerlifter_mild_pain_good_lifts", "Powerlifter mild pain with good lifts", "advanced_powerlifting", e("improving", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ safetyFlag: "pain", readiness: "great" })), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_bodybuilder_local_pump_dropoff", "Bodybuilder local pump drop-off", "beginner_hypertrophy", e("mixed", "moderate", "good", "moderate", "consistent", [{ lift: "pec_deck", signal: "dropoff", severity: "low" }], ["good_readiness"]), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_advanced_hidden_overreach", "Advanced hidden overreach", "advanced_powerlifting", e("improving", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "above_range", severity: "low" }, { lift: "bench_press", signal: "above_range", severity: "low" }, { lift: "deadlift", signal: "dropoff", severity: "high" }], ["high_soreness", "sleep_disrupted", "hidden_overreach"]), x(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "restrict")),
  s(4, "v02_l4_repeated_swap_avoidance", "Repeated swaps may signal avoidance", "busy_parent_time_constrained", e("mixed", "moderate", "mixed", "moderate", "consistent", [{ lift: "squat", signal: "technique_limit", severity: "low" }], ["time_constraint"], subj({ motivation: "low" })), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_high_load_low_reps_joint_cost", "High-load low-rep work with joint cost", "advanced_powerlifting", e("stable", "high", "mixed", "high", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["high_soreness"]), x(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_multiple_small_wins_after_slump", "Multiple small wins after slump", "beginner_hypertrophy", e("improving", "low", "good", "moderate", "consistent", [{ lift: "machine_press", signal: "inside_range", severity: "low" }, { lift: "leg_press", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(4, "v02_l4_weak_evidence_big_claims", "Weak evidence with big claims", "intermediate_strength_hypertrophy", e("improving", "low", "good", "low", "consistent", [{ lift: "bench_press", signal: "above_range", severity: "moderate" }], ["good_readiness"], subj({ readiness: "great", motivation: "high" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_systemic_red_flag_good_performance", "Systemic red flag despite good performance", "advanced_powerlifting", e("improving", "low", "good", "high", "consistent", [{ lift: "squat", signal: "inside_range", severity: "low" }], ["good_readiness"], subj({ safetyFlag: "unusual_symptoms", readiness: "great" })), x(["stop_session"], ["push", "recover"], ["very_low"], "stop")),
  s(4, "v02_l4_worsening_pain_no_systemic", "Worsening pain without systemic red flags", "intermediate_strength_hypertrophy", e("stable", "moderate", "mixed", "high", "consistent", [{ lift: "row", signal: "inside_range", severity: "low" }], ["none"], subj({ safetyFlag: "worsening_pain", readiness: "mixed" })), x(["stop_movement"], ["push", "recover", "stop_session"], ["very_low"], "stop")),
  s(4, "v02_l4_worsening_pain_with_systemic", "Worsening pain with unsafe feeling", "recovery_limited_lifter", e("declining", "high", "poor", "high", "consistent", [{ lift: "all", signal: "none", severity: "none" }], ["multiple_lifts_down"], subj({ safetyFlag: "unsafe", readiness: "poor" })), x(["stop_session"], ["push", "recover"], ["very_low"], "stop")),
  s(4, "v02_l4_good_week_after_deload", "Good week after deload", "recovery_limited_lifter", e("improving", "low", "good", "high", "consistent", [{ lift: "leg_press", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(4, "v02_l4_deload_requested_after_one_bad_day", "Deload requested after one bad day", "intermediate_strength_hypertrophy", e("mixed", "moderate", "mixed", "moderate", "consistent", [{ lift: "bench_press", signal: "below_range", severity: "low" }], ["none"], subj({ readiness: "poor", motivation: "low" })), x(["reduce", "hold"], ["recover", "push", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_recovery_week_completed_but_still_declining", "Recovery week completed but still declining", "recovery_limited_lifter", e("declining", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "below_range", severity: "high" }, { lift: "row", signal: "below_range", severity: "moderate" }], ["multiple_lifts_down", "high_soreness"]), x(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  s(4, "v02_l4_progressing_but_adherence_fragile", "Progressing but adherence fragile", "busy_parent_time_constrained", e("improving", "low", "good", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["good_readiness", "time_constraint"], subj({ motivation: "low" })), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_high_volume_not_failure", "High volume completed, not failure", "intermediate_strength_hypertrophy", e("stable", "moderate", "mixed", "high", "consistent", [{ lift: "leg_extension", signal: "inside_range", severity: "low" }, { lift: "pec_deck", signal: "inside_range", severity: "low" }], ["high_soreness"]), x(["hold", "consolidate"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_compound_cost_high_accessory_available", "Compound cost high, accessory available", "recovery_limited_lifter", e("mixed", "high", "mixed", "high", "consistent", [{ lift: "squat", signal: "dropoff", severity: "high" }, { lift: "leg_extension", signal: "inside_range", severity: "low" }], ["high_soreness"]), x(["reduce", "substitute"], ["push", "recover", "stop_session"], ["very_low", "low"], "restrict")),
  s(4, "v02_l4_technical_success_bad_cost", "Technical success with bad fatigue cost", "advanced_powerlifting", e("stable", "high", "poor", "high", "consistent", [{ lift: "deadlift", signal: "inside_range", severity: "low" }], ["high_soreness", "sleep_disrupted"]), x(["consolidate", "hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_post_illness_too_eager", "Post-illness too eager", "beginner_hypertrophy", e("mixed", "moderate", "mixed", "low", "missed_week", [{ lift: "all", signal: "none", severity: "none" }], ["missed_sessions"], subj({ readiness: "great", motivation: "high" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_powerlifting_peak_success_no_extra", "Powerlifting peak success, no extra fatigue", "advanced_powerlifting", e("improving", "moderate", "mixed", "high", "consistent", [{ lift: "squat", signal: "inside_range", severity: "low" }, { lift: "bench_press", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold", "push"], ["recover", "stop_session"], ["low", "moderate"], "clear")),
  s(4, "v02_l4_body_recomp_stress_high_stable", "Recomp with high stress but stable", "busy_parent_time_constrained", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["time_constraint"], subj({ stress: "high", sleep: "mixed" })), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_maintenance_after_busy_month", "Maintenance after busy month", "busy_parent_time_constrained", e("stable", "low", "good", "low", "interrupted", [{ lift: "full_body", signal: "inside_range", severity: "low" }], ["missed_sessions"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_advanced_plateau_with_good_recovery", "Advanced plateau with good recovery", "advanced_powerlifting", e("stagnant", "low", "good", "high", "consistent", [{ lift: "deadlift", signal: "inside_range", severity: "none" }], ["good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_hidden_pain_plus_pr", "PR paired with hidden pain", "intermediate_strength_hypertrophy", e("improving", "low", "good", "high", "consistent", [{ lift: "bench_press", signal: "above_range", severity: "moderate" }], ["good_readiness"], subj({ safetyFlag: "pain", readiness: "great" })), x(["hold", "reduce"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_new_exercise_pr_not_true_adaptation", "New exercise PR is not true adaptation", "beginner_hypertrophy", e("improving", "low", "good", "low", "consistent", [{ lift: "hack_squat", signal: "above_range", severity: "moderate" }], ["good_readiness"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_local_failure_after_big_block", "Local failure after big block", "advanced_powerlifting", e("mixed", "moderate", "mixed", "high", "consistent", [{ lift: "bench_press", signal: "below_range", severity: "moderate" }], ["high_soreness"]), x(["reduce", "hold"], ["push", "recover", "stop_session"], ["low"], "caution")),
  s(4, "v02_l4_systemic_fatigue_without_pain", "Systemic fatigue without pain", "recovery_limited_lifter", e("declining", "high", "poor", "high", "consistent", [{ lift: "leg_press", signal: "below_range", severity: "moderate" }, { lift: "row", signal: "dropoff", severity: "high" }], ["multiple_lifts_down", "sleep_disrupted"]), x(["recover", "consolidate"], ["push", "stop_session"], ["very_low", "low"], "restrict")),
  s(4, "v02_l4_unusual_symptoms_mid_session", "Unusual symptoms mid-session", "beginner_hypertrophy", e("stable", "moderate", "mixed", "moderate", "consistent", [{ lift: "all", signal: "none", severity: "none" }], ["none"], subj({ safetyFlag: "unusual_symptoms" })), x(["stop_session"], ["push", "recover"], ["very_low"], "stop")),
  s(4, "v02_l4_low_back_capacity_success", "Low Back Capacity success should not drive main push", "recovery_limited_lifter", e("stable", "low", "good", "moderate", "consistent", [{ lift: "bird_dog", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["push", "recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_cardio_recovery_good_strength_stable", "Cardio recovery good, strength stable", "intermediate_strength_hypertrophy", e("stable", "low", "good", "moderate", "consistent", [{ lift: "bench_press", signal: "inside_range", severity: "low" }], ["good_readiness"]), x(["hold"], ["recover", "stop_session"], ["low"], "clear")),
  s(4, "v02_l4_cardio_interference_signal", "Cardio interference signal", "recovery_limited_lifter", e("declining", "high", "poor", "high", "consistent", [{ lift: "squat", signal: "below_range", severity: "moderate" }, { lift: "deadlift", signal: "dropoff", severity: "moderate" }], ["multiple_lifts_down", "high_soreness"]), x(["recover", "consolidate"], ["push"], ["very_low", "low"], "restrict")),
  s(4, "v02_l4_final_stress_test_mixed_everything", "Mixed evidence stress test", "advanced_powerlifting", e("mixed", "high", "mixed", "high", "consistent", [{ lift: "bench_press", signal: "above_range", severity: "low" }, { lift: "squat", signal: "below_range", severity: "moderate" }, { lift: "deadlift", signal: "dropoff", severity: "high" }], ["high_soreness"], subj({ stress: "high", sleep: "poor", readiness: "great" })), x(["reduce", "consolidate", "substitute"], ["push", "recover", "stop_session"], ["very_low", "low"], "restrict")),
];

export const gauntletScenariosV0_2 = [...gauntletScenarios, ...expandedScenarios];

function s(level, id, title, athleteProfileId, evidence, expected) {
  return {
    id,
    level,
    level_label: label(level),
    title,
    athleteProfileId,
    evidence: {
      id,
      scenario: title,
      athleteProfileId,
      status: "research_fixture",
      notes: [`Coaching Gauntlet v0.2 ${label(level)} scenario.`],
      approvalStatus: "draft_requires_aaron_approval",
      ...evidence,
    },
    expected,
    rationale: expected.rationale,
    confidence: expected.confidence_min,
    charter_alignment: expected.charter_alignment,
  };
}

function e(performanceTrend, fatigueState, recoveryState, evidenceQuality, trainingContinuity, localLiftSignals, systemicSignals, subjectiveContext = undefined) {
  return {
    performanceTrend,
    fatigueState,
    recoveryState,
    evidenceQuality,
    trainingContinuity,
    localLiftSignals,
    systemicSignals,
    ...(subjectiveContext ? { subjectiveContext } : {}),
  };
}

function x(allowedTypes, forbiddenTypes, allowedAggressiveness, safetyStatus, overrides = {}) {
  return {
    recommendation_types: allowedTypes,
    forbidden_recommendation_types: forbiddenTypes,
    aggressiveness: allowedAggressiveness,
    safety_gate_status: safetyStatus,
    confidence_min: overrides.confidence_min ?? 45,
    rationale: overrides.rationale ?? "Expected output should follow the Charter, prioritise objective evidence, and use the smallest effective intervention.",
    charter_alignment: overrides.charter_alignment ?? {
      long_term_progress: true,
      adaptation: true,
      recovery: true,
      confidence: true,
      enjoyment: true,
      momentum: true,
    },
  };
}

function subj(values) {
  return {
    readiness: values.readiness ?? "mixed",
    stress: values.stress ?? "moderate",
    sleep: values.sleep ?? "mixed",
    motivation: values.motivation ?? "moderate",
    soreness: values.soreness ?? "moderate",
    safetyFlag: values.safetyFlag ?? "none",
    notes: values.notes ?? "Gauntlet v0.2 subjective context.",
  };
}

function label(level) {
  if (level === 1) return "Level 1 - Normal Progression";
  if (level === 2) return "Level 2 - Real Life";
  if (level === 3) return "Level 3 - Coaching Judgement";
  return "Level 4 - Expert Coaching";
}
