"use client";

import { useEffect, useState } from "react";

type ScreenId = "today" | "programme" | "preview" | "active" | "superset" | "intervention" | "substitute" | "complete" | "insight" | "recovery";
const screens: Array<{ id: ScreenId; label: string; moment: string }> = [
  { id: "today", label: "Today / Train", moment: "Know what matters now" },
  { id: "programme", label: "Programme", moment: "See the path ahead" },
  { id: "preview", label: "Preview + readiness", moment: "Understand today’s decision" },
  { id: "active", label: "Active workout", moment: "Execute without friction" },
  { id: "superset", label: "Advanced method", moment: "Follow complex work simply" },
  { id: "intervention", label: "Coach intervention", moment: "Respond to evidence" },
  { id: "substitute", label: "Substitution", moment: "Handle gym reality" },
  { id: "complete", label: "Completion", moment: "Make progress tangible" },
  { id: "insight", label: "Long-term insight", moment: "Build continuity" },
  { id: "recovery", label: "Restoration states", moment: "Stay usable and truthful" },
];

export default function Home() {
  const [selected, setSelected] = useState<ScreenId>("today");
  const [compact, setCompact] = useState(false);
  useEffect(() => {
    const q = new URLSearchParams(window.location.search).get("screen") as ScreenId | null;
    setCompact(new URLSearchParams(window.location.search).get("size") === "compact");
    if (q && screens.some((screen) => screen.id === q)) setSelected(q);
  }, []);
  const pick = (id: ScreenId) => {
    setSelected(id);
    window.history.replaceState({}, "", `?screen=${id}`);
  };
  return (
    <main className="studio">
      <aside className="rail">
        <div className="brand"><span className="brandMark">A</span><div><strong>ASC / NORTH STAR</strong><small>Prototype studio · data is illustrative</small></div></div>
        <div className="railIntro"><p>THE LIVING PROGRAMME</p><h1>Elite decisions.<br/>Visible progress.<br/>Zero gym friction.</h1><span>Original target direction — not production UI.</span></div>
        <nav aria-label="Prototype states">{screens.map((screen, index) => <button key={screen.id} className={selected === screen.id ? "selected" : ""} onClick={() => pick(screen.id)}><span>{String(index + 1).padStart(2,"0")}</span><div><b>{screen.label}</b><small>{screen.moment}</small></div></button>)}</nav>
        <div className="principles"><span>LOCAL-FIRST</span><span>COACHING RECEIPTS</span><span>ONE PRIMARY ACTION</span></div>
      </aside>
      <section className="stage">
        <header className="stageHead"><div><span>ATHLETE MOMENT</span><h2>{screens.find(s => s.id === selected)?.label}</h2></div><div className="criteria"><span>390 × 844</span><span>AA contrast</span><span>Large-copy stress</span></div></header>
        <div className="phoneWrap"><Phone compact={compact}><Screen id={selected}/></Phone></div>
        <p className="caption">Prototype-only athlete: Maya Chen · Intermediate powerbuilding · kilograms · Week 4 of 12</p>
      </section>
    </main>
  );
}

function Phone({ children, compact }: { children: React.ReactNode; compact: boolean }) { return <div className={`phone ${compact ? "compact" : ""}`}><div className="island"/><div className="phoneScreen">{children}</div></div>; }
function Status({ eyebrow, title, action }: { eyebrow: string; title: string; action?: string }) { return <header className="screenHeader"><div><span>{eyebrow}</span><h3>{title}</h3></div>{action && <button className="iconButton" aria-label={action}>{action}</button>}</header>; }
function Nav({ active }: { active: string }) { return <div className="bottomNav">{[["⌂","Today"],["▥","Programme"],["●","Train"],["↗","Progress"]].map(([icon,label])=><div className={label===active?"active":""} key={label}><b>{icon}</b><span>{label}</span></div>)}</div>; }
function Metric({ value, label, tone }: { value: string; label: string; tone?: string }) { return <div className={`metric ${tone ?? ""}`}><b>{value}</b><span>{label}</span></div>; }
function Screen({ id }: { id: ScreenId }) {
  if (id === "today") return <Today/>;
  if (id === "programme") return <Programme/>;
  if (id === "preview") return <Preview/>;
  if (id === "active") return <Active/>;
  if (id === "superset") return <Superset/>;
  if (id === "intervention") return <Intervention/>;
  if (id === "substitute") return <Substitute/>;
  if (id === "complete") return <Complete/>;
  if (id === "insight") return <Insight/>;
  return <Recovery/>;
}

function Today() { return <div className="screen withNav"><Status eyebrow="THURSDAY · WEEK 4" title="Good afternoon, Maya" action="◉"/><section className="objective"><div className="objectiveTop"><span className="pulse">READY TO BUILD</span><span>58 min</span></div><h4>Upper strength</h4><p>Move the bench press forward. Keep back work productive, not exhausting.</p><div className="adaptRow"><div className="adaptGauge"><b>92</b><span>readiness</span></div><div><b>Prescription held</b><p>Sleep and recent performance support the planned load.</p><button>Why this session →</button></div></div><button className="primary">Start workout <span>→</span></button></section><div className="weekLine"><span>WEEK 4</span><b>3 of 4 sessions</b><div className="dots"><i className="done"/><i className="done"/><i className="done"/><i className="next"/><i/><i/><i/></div></div><section className="nextUp"><div><span>NEXT</span><h5>Lower hypertrophy</h5><p>Saturday · 64 min · 6 exercises</p></div><b>→</b></section><section className="coachNote"><span>COACH NOTE</span><p>Bench volume is landing well. One more quality exposure unlocks next week’s progression.</p></section><Nav active="Today"/></div>; }

function Programme() { return <div className="screen withNav"><Status eyebrow="POWERBUILD 12" title="Build strength. Keep size." action="•••"/><section className="blockHero"><div><span>BLOCK 2 · ACCUMULATE</span><b>4</b><small>of 6 weeks</small></div><div className="arc"><i/><i/><i/><i className="now"/><i/><i/></div><p>Strength practice rises while accessory volume stays high enough to grow.</p></section><div className="programmeStats"><Metric value="+3.8%" label="Bench e1RM" tone="green"/><Metric value="18/20" label="Sessions"/><Metric value="86%" label="Productive sets"/></div><section className="focusMap"><div className="sectionTitle"><span>BLOCK EMPHASIS</span><button>How it adapts</button></div><div className="focusRow"><b>Bench strength</b><div><i style={{width:"88%"}}/></div><span>High</span></div><div className="focusRow"><b>Upper back</b><div><i style={{width:"68%"}}/></div><span>Build</span></div><div className="focusRow"><b>Leg size</b><div><i style={{width:"56%"}}/></div><span>Hold</span></div></section><section className="timeline"><div className="sectionTitle"><span>THE PATH</span><b>8 weeks remain</b></div><div className="phase done"><i>✓</i><div><b>Foundation</b><small>Weeks 1–3 · complete</small></div></div><div className="phase active"><i>02</i><div><b>Accumulate</b><small>Weeks 4–6 · you are here</small></div><span>NOW</span></div><div className="phase"><i>03</i><div><b>Intensify</b><small>Weeks 7–10</small></div></div><div className="phase"><i>04</i><div><b>Realise</b><small>Weeks 11–12</small></div></div></section><Nav active="Programme"/></div>; }

function Preview() { return <div className="screen"><Status eyebrow="TODAY · UPPER STRENGTH" title="A strong day to press" action="×"/><section className="decision"><div className="decisionScore"><b>92</b><span>READY</span></div><div><h4>Run the plan as written</h4><p>No meaningful recovery signal warrants a reduction.</p></div></section><section className="receipt"><span>COACHING RECEIPT</span><div><b>Sleep</b><strong>7h 42</strong><em>supports plan</em></div><div><b>Bench trend</b><strong>+2.1%</strong><em>progressing</em></div><div><b>Upper fatigue</b><strong>Low</strong><em>recovered</em></div><button>Adjust how you feel today</button></section><section className="sessionRoute"><div className="routeHead"><span>58 MIN · 19 WORK SETS</span><button>Modify</button></div><ExerciseLine n="01" name="Barbell Bench Press" detail="4 × 5 · 82.5 kg" tag="MAIN"/><ExerciseLine n="02" name="Chest-Supported Row" detail="3 × 8–10 · 72.5 kg"/><ExerciseLine n="03" name="Incline Dumbbell Press" detail="3 × 8–10 · 27.5 kg"/><ExerciseLine n="+3" name="Accessories" detail="Delts, lats and triceps"/></section><div className="stickyStart"><div><b>Plan held</b><span>3 reasons reviewed</span></div><button>Begin warm-up →</button></div></div>; }

function ExerciseLine({n,name,detail,tag}:{n:string;name:string;detail:string;tag?:string}) { return <div className="exerciseLine"><i>{n}</i><div><b>{name}</b><span>{detail}</span></div>{tag?<em>{tag}</em>:<strong>›</strong>}</div>; }

function Active() { return <div className="screen training"><div className="trainingTop"><button>⌄</button><div><span>UPPER STRENGTH · 18:42</span><b>2 of 6 exercises</b></div><button>•••</button></div><div className="sessionProgress"><i style={{width:"31%"}}/></div><section className="exerciseHero"><div className="exerciseOrdinal"><span>02</span><i>BACK · HORIZONTAL PULL</i></div><h3>Chest-Supported<br/>T-Bar Row</h3><div className="heroMeta"><span>3 working sets</span><span>90 sec rest</span><button>Technique ↗</button></div></section><section className="previous"><span>LAST COMPARABLE</span><b>70 kg × 10, 9, 8</b><em>12 days ago</em></section><section className="setFocus"><div className="setLabel"><span>SET 2 OF 3</span><b>Target 8–10</b></div><div className="loadEntry"><button>−</button><div><b>72.5</b><span>kg</span></div><button>+</button></div><div className="repEntry"><span>REPS</span><button>8</button><button className="chosen">9</button><button>10</button><button>•••</button></div><button className="completeSet">Complete set <span>✓</span></button></section><div className="setRail"><span className="done">1 <b>10</b></span><span className="active">2 <b>Now</b></span><span>3 <b>Next</b></span></div><div className="coachWhisper"><i>↗</i><p><b>Same load, one more clean rep.</b><br/>That keeps this set productive.</p></div></div>; }

function Superset() { return <div className="screen training"><div className="trainingTop"><button>⌄</button><div><span>UPPER STRENGTH · 37:18</span><b>Block 4 of 6</b></div><button>•••</button></div><div className="methodTag">SUPERSET · 3 ROUNDS</div><section className="pairTitle"><span>ROUND 2</span><h3>Shoulders + lats</h3><p>Move directly from A to B, then rest 75 seconds.</p></section><div className="pairCard done"><i>A</i><div><b>Cable Lateral Raise</b><span>12.5 kg × 14</span></div><strong>✓</strong></div><div className="connector"><i/>NO REST<i/></div><div className="pairCard current"><i>B</i><div><span>NOW</span><b>Half-Kneeling Single-Arm Lat Pulldown</b><small>Target 10–12 each side</small></div><strong>Technique ↗</strong></div><section className="compactEntry"><div><span>LOAD</span><b>32.5 <small>kg</small></b></div><div><span>REPS / SIDE</span><b>11</b></div><button>Complete B <strong>✓</strong></button></section><div className="roundRail"><span className="done">R1 ✓</span><span className="active">R2 · B</span><span>R3</span></div><div className="methodHelp"><b>Method intent</b><p>Keep the transition under 20 seconds. Stop one rep before technique breaks.</p></div></div>; }

function Intervention() { return <div className="screen intervention"><div className="interventionBackdrop"><div className="miniTop">SET 3 · BARBELL BENCH PRESS</div><h3>82.5 kg</h3><div className="ghostSets"><span>5 reps ✓</span><span>5 reps ✓</span><span className="low">3 reps</span></div></div><section className="coachSheet"><div className="coachSignal"><i>↘</i><div><span>COACH INTERVENTION</span><h3>Performance dropped earlier than expected</h3></div></div><p>You completed 3 reps against a 5-rep target after two stable sets. One set remains.</p><div className="evidenceCompare"><div><span>EXPECTED</span><b>5 reps</b></div><i>→</i><div className="warn"><span>ACTUAL</span><b>3 reps</b></div></div><div className="recommendation"><span>RECOMMENDED</span><h4>Reduce to 77.5 kg</h4><p>Preserve the strength stimulus without forcing a low-quality final set.</p></div><button className="primary">Apply 77.5 kg <span>→</span></button><button className="textAction">Keep 82.5 kg · tell coach why</button></section></div>; }

function Substitute() { return <div className="screen"><Status eyebrow="MODIFY EXERCISE 03" title="Replace incline press" action="×"/><section className="reasonPicker"><span>WHAT CHANGED?</span><div><button className="on">Equipment busy</button><button>Discomfort</button><button>Preference</button><button>Other</button></div></section><section className="subCoach"><i>↔</i><div><span>COACH MATCH</span><p>These options preserve upper-chest emphasis and today’s pressing volume.</p></div></section><div className="subList"><SubChoice score="96" name="Low-Incline Smith Press" meta="Same pattern · stable load" load="55 kg · 3 × 8–10" best/><SubChoice score="91" name="Low-Incline Dumbbell Press" meta="Same intent · more stability demand" load="27.5 kg · 3 × 8–10"/><SubChoice score="84" name="Cable Incline Press" meta="Similar muscle bias · lighter loading" load="22.5 kg/side · 3 × 10–12"/></div><button className="searchAll">Search all compatible exercises</button><div className="subFooter"><span>Original stays in your programme</span><button>Use Smith press →</button></div></div>; }
function SubChoice({score,name,meta,load,best}:{score:string;name:string;meta:string;load:string;best?:boolean}) { return <button className={`subChoice ${best?"best":""}`}><i>{score}<small>%</small></i><div><span>{best?"BEST MATCH":"COMPATIBLE"}</span><b>{name}</b><p>{meta}</p><strong>{load}</strong></div><em>{best?"✓":"○"}</em></button>; }

function Complete() { return <div className="screen completion"><div className="completeGlow"/><button className="closeComplete">×</button><section className="completeHero"><span>UPPER STRENGTH · COMPLETE</span><h3>Today moved the<br/>programme forward.</h3><p>52 min · 19 work sets · 8,420 kg</p></section><div className="prSeal"><span>NEW</span><b>+2.4%</b><strong>BENCH WORK-CAPACITY PR</strong><small>Best four-set result at 82.5 kg</small></div><section className="progressReceipt"><span>WHAT CHANGED</span><div className="delta"><i>Bench</i><b>82.5 × 5, 5, 5, 4</b><strong>↑</strong></div><div className="delta"><i>Back volume</i><b>9 productive sets</b><strong>✓</strong></div><div className="delta"><i>Plan</i><b>Next bench load +2.5 kg</b><strong>→</strong></div></section><section className="nextObjective"><span>NEXT OBJECTIVE</span><h4>Recover, then build lower-body volume.</h4><p>Saturday · Lower hypertrophy · prescription ready</p></section><div className="completeActions"><button className="primary">View progress <span>→</span></button><button>Share privately</button></div></div>; }

function Insight() { return <div className="screen withNav"><Status eyebrow="COACH INSIGHT · 12 WEEKS" title="Your strength is becoming repeatable" action="⌄"/><section className="insightHero"><div><span>BENCH e1RM</span><b>103.8 <small>kg</small></b><strong>+8.6%</strong></div><div className="chart"><i/><i/><i/><i/><i/><i/><i/><span>100</span><span>90</span></div><p>Not a single-session spike: your last four exposures all support the trend.</p></section><section className="coachRead"><span>COACH READ</span><h4>Your pressing responds best to two exposures per week.</h4><p>Progress slowed when fatigue rose in Week 7, then resumed after volume was reduced—not after intensity was removed.</p><button>See the evidence →</button></section><div className="outcomes"><Metric value="11" label="Verified PRs" tone="green"/><Metric value="94%" label="Adherence"/><Metric value="7" label="Weeks progressing"/></div><section className="continuity"><div className="sectionTitle"><span>NEXT BLOCK DECISION</span><b>in 2 weeks</b></div><div className="decisionLine"><i>01</i><p><b>Keep bench frequency</b><br/>High-confidence response</p><strong>LOCKED</strong></div><div className="decisionLine"><i>02</i><p><b>Shift accessory bias</b><br/>More triceps, less chest isolation</p><strong>LIKELY</strong></div></section><Nav active="Progress"/></div>; }

function Recovery() { const [state,setState]=useState<"restoring"|"offline"|"error">("restoring"); return <div className="screen recovery"><Status eyebrow="SAFE STARTUP" title="Your training stays available"/><div className="stateTabs"><button className={state==="restoring"?"on":""} onClick={()=>setState("restoring")}>Restoring</button><button className={state==="offline"?"on":""} onClick={()=>setState("offline")}>Offline</button><button className={state==="error"?"on":""} onClick={()=>setState("error")}>Error</button></div>{state==="restoring"?<><section className="restoreStatus"><div className="restoreIcon"><i/></div><span>RESTORING IN BACKGROUND</span><h3>Your local programme is ready</h3><p>We’re checking account history and settings. You can train now; restored changes will be reconciled safely.</p><div className="restoreSteps"><div className="done"><i>✓</i><span><b>Local programme</b><small>Available now</small></span></div><div className="working"><i/><span><b>Account history</b><small>Checking 142 sessions…</small></span></div><div><i>3</i><span><b>Reconcile changes</b><small>Runs only if needed</small></span></div></div></section><button className="primary">Continue to Today <span>→</span></button><button className="textAction">Keep checking in background</button></>:state==="offline"?<section className="offlineState"><div className="bigIcon">⌁</div><span>OFFLINE · LOCAL-FIRST</span><h3>Train without a connection</h3><p>Your programme, active workout and recent history are on this device. New work will sync when you reconnect.</p><div className="available"><b>Available now</b><span>Today’s workout</span><span>Set logging and rest timing</span><span>Programme and recent history</span></div><button className="primary">Start today’s workout →</button></section>:<section className="errorState"><div className="bigIcon">!</div><span>ACCOUNT RESTORE PAUSED</span><h3>Nothing was overwritten</h3><p>We couldn’t finish checking your account history. Your local programme and workouts remain safe.</p><div className="errorActions"><button className="primary">Try account restore again</button><button>Continue with local data</button><button>View recovery details</button></div><small>Error reference: RESTORE–HISTORY–TIMEOUT</small></section>}</div>; }
