import { canonicalRestTimerRepository, type CanonicalRestTimerSnapshot } from "@/data/local/canonical-rest-timer-repository";
export type RestTimerClock = Readonly<{ now(): number }>;
export const systemRestTimerClock: RestTimerClock = { now: () => Date.now() };
export function startCanonicalRestTimer(input: Readonly<{ workoutId: string; setId: string; durationSeconds: number; clock?: RestTimerClock }>) { const now = (input.clock ?? systemRestTimerClock).now(); return canonicalRestTimerRepository.save({ schemaVersion: "canonical_rest_timer_v1", workoutId: input.workoutId, setId: input.setId, prescribedDurationSeconds: input.durationSeconds, startedAt: now, expiresAt: now + input.durationSeconds * 1000, state: "running", expiryAcknowledged: false }); }
export function restoreCanonicalRestTimer(workoutId: string, clock: RestTimerClock = systemRestTimerClock) { return canonicalRestTimerRepository.reconcile(workoutId, clock.now()); }
export function pauseCanonicalRestTimer(workoutId: string, clock: RestTimerClock = systemRestTimerClock) { const current = restoreCanonicalRestTimer(workoutId, clock); if (!current || current.state !== "running") return current; const remainingSeconds = Math.max(0, Math.ceil((current.expiresAt - clock.now()) / 1000)); return canonicalRestTimerRepository.save({ ...current, state: "paused", remainingSeconds }); }
export function resumeCanonicalRestTimer(workoutId: string, clock: RestTimerClock = systemRestTimerClock) { const current = restoreCanonicalRestTimer(workoutId, clock); if (!current || current.state !== "paused") return current; const now = clock.now(); return canonicalRestTimerRepository.save({ ...current, state: "running", startedAt: now, expiresAt: now + (current.remainingSeconds ?? 0) * 1000, remainingSeconds: undefined }); }
export function addCanonicalRestTime(workoutId: string, seconds: number, clock: RestTimerClock = systemRestTimerClock) { const current = restoreCanonicalRestTimer(workoutId, clock); if (!current || current.state === "expired" || current.state === "skipped") return current; const now = clock.now(); return canonicalRestTimerRepository.save({ ...current, expiresAt: Math.max(current.expiresAt, now) + Math.max(0, seconds) * 1000, prescribedDurationSeconds: current.prescribedDurationSeconds + Math.max(0, seconds) }); }
export function skipCanonicalRestTimer(workoutId: string) { const current = canonicalRestTimerRepository.get(workoutId); return current ? canonicalRestTimerRepository.save({ ...current, state: "skipped", expiryAcknowledged: true }) : null; }
export function acknowledgeCanonicalRestExpiry(workoutId: string) { const current = canonicalRestTimerRepository.get(workoutId); return current ? canonicalRestTimerRepository.save({ ...current, expiryAcknowledged: true }) : null; }
