import { createMacrocycle, macrocycleEngineForGoal } from "@/domain/training/macrocycle-engine";
import { selectMesocycles } from "@/domain/training/mesocycle-library";
import { createMicrocycle, type CanonicalTrainingDaysPerWeek } from "@/domain/training/microcycle-scheduler";
import { assembleCanonicalActivePlan, type CanonicalActivePlanCarrier, type CanonicalPlannedSessionSnapshot } from "@/domain/training/canonical-active-plan-carrier";
import { resolveMesocyclePrescriptionPolicy } from "@/domain/training/mesocycle-prescription-policy";
import { constructCanonicalSession, resolveCanonicalSessionIdentity } from "@/domain/training/canonical-session-construction-pipeline";
import type { Equipment, ExperienceLevel, Exercise, ProgrammeGoal, UnitSystem, WorkoutHistorySummary } from "@/domain/training/models";
import { canonicalConstructionReferencesForPlan } from "@/application/training/canonical-construction-facts";
import type { CanonicalLoadEvidence } from "@/domain/training/canonical-load-prescription";
import { allocateCanonicalMicrocycleVolume } from "@/domain/training/canonical-microcycle-volume-allocator";
import { certifyCanonicalConstructedMicrocycle } from "@/domain/training/canonical-constructed-microcycle-certification";
import { canonicalGoalStrategies, validateCanonicalPlanningActivation } from "@/domain/training/canonical-adaptive-planning-system";
import type { ExercisePreferenceRecord } from "@/domain/training/exercise-preferences";
import { resolveCanonicalCardioPrescription } from "@/domain/training/canonical-cardio-prescription";
import type { RecoveryCardioPreference } from "@/domain/training/plan-setup";
import { defaultCanonicalStartingVolumeContext, type CanonicalStartingVolumeContext } from "@/domain/training/canonical-hypertrophy-volume-policy";
import { estimateCanonicalSessionDuration, normalizeCanonicalSessionDuration, type CanonicalSessionDurationMinutes } from "@/domain/training/canonical-session-duration";

export type CanonicalConstructionInput = Readonly<{ planId: string; createdAt: string; updatedAt: string; goal: ProgrammeGoal; macrocycleGoal: Parameters<typeof createMacrocycle>[0]; experienceLevel: ExperienceLevel; daysPerWeek: CanonicalTrainingDaysPerWeek; preferredSplit: Parameters<typeof createMicrocycle>[0]["split"]; equipment: readonly Equipment[]; units: UnitSystem; targetDate?: string; recoveryCardioPreference?: RecoveryCardioPreference; availableSessionMinutes?: CanonicalSessionDurationMinutes; startingVolumeContext?: CanonicalStartingVolumeContext; microcycleSequenceNumber?: number; plannedSessions: readonly CanonicalPlannedSessionSnapshot[] }>;
export type CanonicalConstructionResult = Readonly<{ status: "constructed"; carrier: CanonicalActivePlanCarrier } | { status: "invalid_input" | "no_initial_mesocycle" | "session_role_mismatch" | "carrier_validation_failed"; reason: string }>;

export type CanonicalGeneratedPlanInput = Readonly<Omit<CanonicalConstructionInput, "plannedSessions"> & { exercises: readonly Exercise[]; limitations?: readonly string[]; exercisePreferences?: Readonly<Record<string, ExercisePreferenceRecord>>; history?: readonly WorkoutHistorySummary[]; establishedLoads?: Readonly<Record<string, number>>; loadEvidence?: Readonly<Record<string, CanonicalLoadEvidence>> }>;

/** Normal construction path: planned sessions are generated by Session Construction, never supplied by callers. */
export function constructCanonicalActivePlanFromCanonicalInputs(input: CanonicalGeneratedPlanInput): CanonicalConstructionResult {
  if (!input.planId || !input.createdAt || !input.updatedAt || !input.equipment.length || !input.exercises.length) return { status: "invalid_input", reason: "missing_required_canonical_inputs" };
  const bodyweightExcluded = input.limitations?.includes("exclude_equipment:bodyweight");
  const effectiveEquipment = !bodyweightExcluded && !input.equipment.includes("bodyweight") ? [...input.equipment, "bodyweight" as const] : input.equipment;
  const activation = validateCanonicalPlanningActivation({ goal: input.macrocycleGoal, experience: input.experienceLevel, daysPerWeek: input.daysPerWeek, preferredSplit: input.preferredSplit, equipment: effectiveEquipment, units: input.units, createdAt: input.createdAt, targetDate: input.targetDate, limitations: input.limitations });
  if (activation.status !== "valid") return { status: "invalid_input", reason: `${activation.reason}:${activation.detail}` };
  const macrocycle = createMacrocycle(input.macrocycleGoal, input.experienceLevel, input.targetDate, input.createdAt);
  const mesocycle = selectMesocycles(macrocycleEngineForGoal(input.macrocycleGoal), input.experienceLevel)[0];
  if (!mesocycle) return { status: "no_initial_mesocycle", reason: "no_eligible_initial_mesocycle" };
  const policyResult = resolveMesocyclePrescriptionPolicy(mesocycle.id, { goal: input.macrocycleGoal });
  if (policyResult.status !== "resolved") return { status: "no_initial_mesocycle", reason: policyResult.reason };
  const microcycle = createMicrocycle({ parentMesocycleId: mesocycle.id, trainingDays: input.daysPerWeek, split: input.preferredSplit, sequenceNumber: input.microcycleSequenceNumber });
  // Older callers without the new intake receive a provisional declared-
  // training baseline. Missing app history still requires load calibration,
  // but is not treated as beginner/detrained status or low work capacity.
  const startingVolumeContext: CanonicalStartingVolumeContext = input.startingVolumeContext
    ?? defaultCanonicalStartingVolumeContext(input.daysPerWeek);
  const availableSessionMinutes = normalizeCanonicalSessionDuration(input.availableSessionMinutes);
  const allocation = allocateCanonicalMicrocycleVolume({
    macrocycleGoal: input.macrocycleGoal,
    mesocycleId: mesocycle.id,
    mesocyclePurpose: mesocycle.adaptation,
    microcyclePriority: microcycle.priority,
    microcycleSequence: microcycle.sequenceNumber,
    experience: input.experienceLevel,
    frequency: input.daysPerWeek,
    split: input.preferredSplit,
    equipment: effectiveEquipment,
    recoveryRestricted: startingVolumeContext.recovery === "low_acceptable",
    establishedLoadExerciseIds: Object.keys(input.establishedLoads ?? {}).sort(),
    sessionRoles: microcycle.sessionRoles,
    sessionTypes: microcycle.sessionTypes,
    startingVolumeContext,
    availableSessionMinutes,
  });
  if (allocation.certification.status !== "passed") return { status: "carrier_validation_failed", reason: `microcycle_allocation:${allocation.certification.failures.join(",")}` };
  const microcycleId = `${input.planId}:microcycle:${microcycle.sequenceNumber}`;
  const sessions: CanonicalPlannedSessionSnapshot[] = [];
  const weeklyExerciseUsage: Record<string, number> = {};
  for (const [index, role] of microcycle.sessionRoles.entries()) {
    const sessionInput = {
      schemaVersion: "canonical_session_construction_input_v1" as const,
      macrocycle: { goal: input.macrocycleGoal, targetDate: input.targetDate, rolling: macrocycle.rolling },
      mesocycle: { id: policyResult.policy.mesocycleId, policy: policyResult.policy, position: 0 },
      microcycle: { id: microcycleId, output: microcycle, sessionId: "", planSessionIndex: index, sessionRole: role, sessionOrder: index, stressIntent: microcycle.priority, recoveryDays: microcycle.recoveryDays, kind: "planned" as const },
      athlete: { experienceLevel: input.experienceLevel, preferredSplit: input.preferredSplit, equipment: effectiveEquipment, limitations: input.limitations ?? [], exercisePreferences: input.exercisePreferences, units: input.units, exercises: input.exercises },
      progress: { evidenceVersion: "progress_v1", history: input.history ?? [], establishedLoads: input.establishedLoads, loadEvidence: input.loadEvidence },
      operational: { constructionVersion: "canonical_plan_v3", seed: `${input.planId}:${index}`, identity: "", revision: input.updatedAt },
      allocation,
      selectionContext: { weeklyExerciseUsage: { ...weeklyExerciseUsage } },
    };
    const identity = resolveCanonicalSessionIdentity(sessionInput);
    const constructed = constructCanonicalSession({ ...sessionInput, microcycle: { ...sessionInput.microcycle, sessionId: identity }, operational: { ...sessionInput.operational, identity } });
    if (constructed.status !== "constructed") return { status: "carrier_validation_failed", reason: `session_${index}:${constructed.reason}` };
    if (constructed.snapshot.schemaVersion !== "canonical_session_snapshot_v3") return { status: "carrier_validation_failed", reason: `session_${index}:current_construction_requires_v3_snapshot` };
    const allocated = allocation.slots.filter((slot) => slot.sessionIndex === index);
    const exactDuration = estimateCanonicalSessionDuration(constructed.snapshot.slots.map((slot) => {
      const source = allocated.find((entry) => entry.order === slot.index);
      if (!source) throw new Error(`duration_slot_linkage_missing:${index}:${slot.index}`);
      return { constructionRole: source.constructionRole, workingSets: slot.settings.requiredSets ?? slot.settings.requiredWorkSets, movementPatterns: source.movementPatterns, method: slot.method, prescribedRestSeconds: slot.rest.seconds, loadConfidence: slot.loadPrescription.state === "established" ? "established" as const : "calibration_required" as const };
    }), startingVolumeContext.loadConfidence);
    if (exactDuration.minutes > availableSessionMinutes) return { status: "carrier_validation_failed", reason: `session_${index}:exact_duration_exceeds_${availableSessionMinutes}_minutes` };
    for (const slot of constructed.snapshot.slots) weeklyExerciseUsage[slot.exerciseId] = (weeklyExerciseUsage[slot.exerciseId] ?? 0) + 1;
    sessions.push({ id: identity, microcycleId, planSessionIndex: index, role, kind: "planned", status: "planned", constructionVersion: "canonical_plan_v3", revision: 0, prescriptionSnapshot: constructed.snapshot });
  }
  const constructedCertification = certifyCanonicalConstructedMicrocycle({ allocation, sessions: sessions.map((session) => session.prescriptionSnapshot as import("@/domain/training/canonical-session-construction-pipeline").CanonicalSessionSnapshotV3), exercises: input.exercises });
  if (constructedCertification.status !== "passed") return { status: "carrier_validation_failed", reason: `constructed_microcycle:${constructedCertification.failures.join(",")}` };
  const result = constructCanonicalActivePlan({ ...input, equipment: effectiveEquipment, availableSessionMinutes, startingVolumeContext, plannedSessions: sessions });
  if (result.status !== "constructed") return result;
  const strategyGoal = input.macrocycleGoal === "powerlifting_meet" ? "build_strength" : input.macrocycleGoal;
  const goalStrategyId = canonicalGoalStrategies.find((strategy) => strategy.goal === strategyGoal)?.strategyId ?? `unsupported_goal:${input.macrocycleGoal}`;
  return { ...result, carrier: { ...result.carrier, constructionInputs: canonicalConstructionReferencesForPlan(result.carrier), planningRationale: { schemaVersion: "canonical_planning_rationale_v1", goalStrategyId, rotationReasons: [...activation.reasonCodes, `mesocycle:${mesocycle.id}`, `schedule:${microcycle.scheduleMode}`], sessionReasons: sessions.map((session) => ({ planSessionIndex: session.planSessionIndex, role: session.role, reasons: [`microcycle_role:${session.role}`, `mesocycle_purpose:${mesocycle.adaptation}`, ...((session.prescriptionSnapshot as import("@/domain/training/canonical-session-construction-pipeline").CanonicalSessionSnapshotV3).slots.map((slot) => `slot:${slot.index}:${slot.reason}`))] })), changeReasons: ["initial_canonical_construction", "no_progress_intervention_applied"] }, cycleLineage: [{ schemaVersion: "canonical_session_lineage_v1", planId: result.carrier.planId, macrocycleId: result.carrier.macrocycle.id, mesocycleId: result.carrier.mesocycle.id, microcycleId: result.carrier.microcycle.id, revision: result.carrier.revision, sequenceNumber: result.carrier.microcycle.output.sequenceNumber, status: "current" as const }] } };
}

/** Orchestrates existing owners; prescription snapshots must be supplied by Session Construction. */
export function constructCanonicalActivePlan(input: CanonicalConstructionInput): CanonicalConstructionResult {
  if (!input.planId || !input.createdAt || !input.updatedAt || input.equipment.length === 0) return { status: "invalid_input", reason: "missing_required_identity_or_equipment" };
  const macrocycle = createMacrocycle(input.macrocycleGoal, input.experienceLevel, input.targetDate, input.createdAt);
  const mesocycle = selectMesocycles(macrocycleEngineForGoal(input.macrocycleGoal), input.experienceLevel)[0];
  if (!mesocycle) return { status: "no_initial_mesocycle", reason: "no_eligible_initial_mesocycle" };
  const microcycle = createMicrocycle({ parentMesocycleId: mesocycle.id, trainingDays: input.daysPerWeek, split: input.preferredSplit, sequenceNumber: input.microcycleSequenceNumber });
  if (input.plannedSessions.some((session) => !microcycle.sessionRoles[session.planSessionIndex] || microcycle.sessionRoles[session.planSessionIndex] !== session.role)) return { status: "session_role_mismatch", reason: "planned_session_role_not_in_microcycle" };
  const conditioning = resolveCanonicalCardioPrescription({ planId: input.planId, goal: input.macrocycleGoal, preference: input.recoveryCardioPreference ?? "recommended", experience: input.experienceLevel, liftingDays: input.daysPerWeek, liftingDayOffsets: microcycle.sessionDayOffsets });
  const assembled = assembleCanonicalActivePlan({ planId: input.planId, createdAt: input.createdAt, updatedAt: input.updatedAt, macrocycle, mesocycle, microcycle: { ...microcycle, id: `${input.planId}:microcycle:${microcycle.sequenceNumber}`, constructionVersion: "microcycle_v1" }, plannedSessions: input.plannedSessions, progress: { evidenceVersion: "progress_v1", revision: 0 }, conditioning, constraints: { goal: input.goal, experienceLevel: input.experienceLevel, daysPerWeek: input.daysPerWeek, preferredSplit: input.preferredSplit, equipment: [...input.equipment], units: input.units, targetDate: input.targetDate, recoveryCardioPreference: input.recoveryCardioPreference ?? "recommended", availableSessionMinutes: normalizeCanonicalSessionDuration(input.availableSessionMinutes), startingVolumeContext: input.startingVolumeContext } });
  return assembled.status === "valid" ? { status: "constructed", carrier: assembled.carrier } : { status: "carrier_validation_failed", reason: assembled.reason };
}
