import { createMacrocycle, macrocycleEngineForGoal } from "@/domain/training/macrocycle-engine";
import { selectMesocycles } from "@/domain/training/mesocycle-library";
import { createMicrocycle, type CanonicalTrainingDaysPerWeek } from "@/domain/training/microcycle-scheduler";
import { assembleCanonicalActivePlan, type CanonicalActivePlanCarrier, type CanonicalPlannedSessionSnapshot } from "@/domain/training/canonical-active-plan-carrier";
import { resolveMesocyclePrescriptionPolicy } from "@/domain/training/mesocycle-prescription-policy";
import { constructCanonicalSession, resolveCanonicalSessionIdentity } from "@/domain/training/canonical-session-construction-pipeline";
import type { Equipment, ExperienceLevel, Exercise, ProgrammeGoal, UnitSystem, WorkoutHistorySummary } from "@/domain/training/models";
import { canonicalConstructionReferencesForPlan } from "@/application/training/canonical-construction-facts";
import type { CanonicalLoadEvidence } from "@/domain/training/canonical-load-prescription";

export type CanonicalConstructionInput = Readonly<{ planId: string; createdAt: string; updatedAt: string; goal: ProgrammeGoal; macrocycleGoal: Parameters<typeof createMacrocycle>[0]; experienceLevel: ExperienceLevel; daysPerWeek: CanonicalTrainingDaysPerWeek; preferredSplit: Parameters<typeof createMicrocycle>[0]["split"]; equipment: readonly Equipment[]; units: UnitSystem; targetDate?: string; plannedSessions: readonly CanonicalPlannedSessionSnapshot[] }>;
export type CanonicalConstructionResult = Readonly<{ status: "constructed"; carrier: CanonicalActivePlanCarrier } | { status: "invalid_input" | "no_initial_mesocycle" | "session_role_mismatch" | "carrier_validation_failed"; reason: string }>;

export type CanonicalGeneratedPlanInput = Readonly<Omit<CanonicalConstructionInput, "plannedSessions"> & { exercises: readonly Exercise[]; limitations?: readonly string[]; history?: readonly WorkoutHistorySummary[]; establishedLoads?: Readonly<Record<string, number>>; loadEvidence?: Readonly<Record<string, CanonicalLoadEvidence>> }>;

/** Normal construction path: planned sessions are generated by Session Construction, never supplied by callers. */
export function constructCanonicalActivePlanFromCanonicalInputs(input: CanonicalGeneratedPlanInput): CanonicalConstructionResult {
  if (!input.planId || !input.createdAt || !input.updatedAt || !input.equipment.length || !input.exercises.length) return { status: "invalid_input", reason: "missing_required_canonical_inputs" };
  const macrocycle = createMacrocycle(input.macrocycleGoal, input.experienceLevel, input.targetDate, input.createdAt);
  const mesocycle = selectMesocycles(macrocycleEngineForGoal(input.macrocycleGoal), input.experienceLevel)[0];
  if (!mesocycle) return { status: "no_initial_mesocycle", reason: "no_eligible_initial_mesocycle" };
  const policyResult = resolveMesocyclePrescriptionPolicy(mesocycle.id, { goal: input.macrocycleGoal });
  if (policyResult.status !== "resolved") return { status: "no_initial_mesocycle", reason: policyResult.reason };
  const microcycle = createMicrocycle({ parentMesocycleId: mesocycle.id, trainingDays: input.daysPerWeek, split: input.preferredSplit });
  const microcycleId = `${input.planId}:microcycle:1`;
  const sessions: CanonicalPlannedSessionSnapshot[] = [];
  for (const [index, role] of microcycle.sessionRoles.entries()) {
    const sessionInput = {
      schemaVersion: "canonical_session_construction_input_v1" as const,
      macrocycle: { goal: input.macrocycleGoal, targetDate: input.targetDate, rolling: macrocycle.rolling },
      mesocycle: { id: policyResult.policy.mesocycleId, policy: policyResult.policy, position: 0 },
      microcycle: { id: microcycleId, output: microcycle, sessionId: "", planSessionIndex: index, sessionRole: role, sessionOrder: index, stressIntent: microcycle.priority, recoveryDays: microcycle.recoveryDays, kind: "planned" as const },
      athlete: { experienceLevel: input.experienceLevel, preferredSplit: input.preferredSplit, equipment: input.equipment, limitations: input.limitations ?? [], units: input.units, exercises: input.exercises },
      progress: { evidenceVersion: "progress_v1", history: input.history ?? [], establishedLoads: input.establishedLoads, loadEvidence: input.loadEvidence },
      operational: { constructionVersion: "canonical_plan_v3", seed: `${input.planId}:${index}`, identity: "", revision: input.updatedAt },
    };
    const identity = resolveCanonicalSessionIdentity(sessionInput);
    const constructed = constructCanonicalSession({ ...sessionInput, microcycle: { ...sessionInput.microcycle, sessionId: identity }, operational: { ...sessionInput.operational, identity } });
    if (constructed.status !== "constructed") return { status: "carrier_validation_failed", reason: `session_${index}:${constructed.reason}` };
    sessions.push({ id: identity, microcycleId, planSessionIndex: index, role, kind: "planned", status: "planned", constructionVersion: "canonical_plan_v3", revision: 0, prescriptionSnapshot: constructed.snapshot });
  }
  const result = constructCanonicalActivePlan({ ...input, plannedSessions: sessions });
  if (result.status !== "constructed") return result;
  return { ...result, carrier: { ...result.carrier, constructionInputs: canonicalConstructionReferencesForPlan(result.carrier), cycleLineage: [{ schemaVersion: "canonical_session_lineage_v1", planId: result.carrier.planId, macrocycleId: result.carrier.macrocycle.id, mesocycleId: result.carrier.mesocycle.id, microcycleId: result.carrier.microcycle.id, revision: result.carrier.revision, sequenceNumber: result.carrier.microcycle.output.sequenceNumber, status: "current" as const }] } };
}

/** Orchestrates existing owners; prescription snapshots must be supplied by Session Construction. */
export function constructCanonicalActivePlan(input: CanonicalConstructionInput): CanonicalConstructionResult {
  if (!input.planId || !input.createdAt || !input.updatedAt || input.equipment.length === 0) return { status: "invalid_input", reason: "missing_required_identity_or_equipment" };
  const macrocycle = createMacrocycle(input.macrocycleGoal, input.experienceLevel, input.targetDate, input.createdAt);
  const mesocycle = selectMesocycles(macrocycleEngineForGoal(input.macrocycleGoal), input.experienceLevel)[0];
  if (!mesocycle) return { status: "no_initial_mesocycle", reason: "no_eligible_initial_mesocycle" };
  const microcycle = createMicrocycle({ parentMesocycleId: mesocycle.id, trainingDays: input.daysPerWeek, split: input.preferredSplit });
  if (input.plannedSessions.some((session) => !microcycle.sessionRoles[session.planSessionIndex] || microcycle.sessionRoles[session.planSessionIndex] !== session.role)) return { status: "session_role_mismatch", reason: "planned_session_role_not_in_microcycle" };
  const assembled = assembleCanonicalActivePlan({ planId: input.planId, createdAt: input.createdAt, updatedAt: input.updatedAt, macrocycle, mesocycle, microcycle: { ...microcycle, id: `${input.planId}:microcycle:1`, constructionVersion: "microcycle_v1" }, plannedSessions: input.plannedSessions, progress: { evidenceVersion: "progress_v1", revision: 0 }, constraints: { goal: input.goal, experienceLevel: input.experienceLevel, daysPerWeek: input.daysPerWeek, preferredSplit: input.preferredSplit, equipment: [...input.equipment], units: input.units, targetDate: input.targetDate } });
  return assembled.status === "valid" ? { status: "constructed", carrier: assembled.carrier } : { status: "carrier_validation_failed", reason: assembled.reason };
}
